function setCookie(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; expires=Tue, 31-Dec-2030 23:59:59; "}function setCookieOneTime(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; "}function setCookieWeek(a,b,c){dateExp=new Date;dateExp.setTime(dateExp.getTime()+6048E5);c=a+"="+encodeURIComponent(b)+"; ";c=c+"path=/; "+("expires="+dateExp.toGMTString());document.cookie=c}
function getCookie(a){var b=a+"=";a=document.cookie;var c=a.indexOf(b);if(0>c)return null;b=c+b.length;c=a.indexOf(";",b);-1==c&&(c=a.length);return decodeURIComponent(a.substring(b,c))}function deleteCookie(a,b){dTime=new Date;dTime.setTime(0);b=a+"="+encodeURIComponent("0")+"; ";b=b+"path=/; "+("expires="+dTime.toGMTString()+"; ");document.cookie=b}
function ChLang(a){0<a.length?setCookie("MK_LANG",a):deleteCookie("MK_LANG");$.ajaxSingle({type:"post",data:{LD:"ja"==a?1:0},url:"/FUpdateLanguage.jsp",success:function(a){location.reload(!0)}})}function SearchIllustByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchIllustByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}function SearchTagByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchTagByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}
function SearchUserByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchUserByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}var sendObjectMessage=function(a){var b=document.createElement("iframe");b.setAttribute("src","myurlscheme://"+a);document.documentElement.appendChild(b);b.parentNode.removeChild(b)};
$.fn.autoLink=function(a){var b=0==a?"/SearchIllustByTagV.jsp":"/SearchIllustByTagPcV.jsp";return this.each(function(){var a=this.innerHTML;a=a.replace(/((http|https):\/\/[\w\.\-\/:;&?,=#!~]+)/gi,"<a class='AutoLink' href='$1' target='_blank'>$1</a>");this.innerHTML=a.replace(/(#|\uff03)[\w]*[a-zA-Z0-9\u3041-\u30fe\u30fc-\u9fa5\u8c48-\u9db4]+/g,function(a){a=a.replace(/[#\uff03]/,"");return" <a class='AutoLink' href='"+b+"?KWD="+encodeURIComponent(a)+"'>#"+a+"</a>"})})};
function GotoLogin(){location.href="/LoginFormV.jsp"}function DispMsg(a){$("#DispMsg").html(a);$("#DispMsg").slideDown(200,function(){setTimeout(function(){$("#DispMsg").slideUp(200)},3E3)})}function DispMsgStatic(a){setTimeout(function(){$("#DispMsg").html(a);$("#DispMsg").show()},0)}function HideMsgStatic(){setTimeout(function(){$("#DispMsg").hide()},1E3)}
$(function(){jQuery.extend({ajaxSingle:function(a){var b=!1;return function(a){try{b||(b=!0,a.complete=function(){return function(a,c){b=!1}}(),$.ajax(a))}catch(d){b=!1}}}()});$(window).on("scroll",function(){75<=$(this).scrollTop()?$(".MainMenu").addClass("Fixed"):$(".MainMenu").removeClass("Fixed")})});function CreateIllustThumb(a){return CreateIllustThumbBase(a,0)}function CreateIllustThumbPc(a){return CreateIllustThumbBase(a,1)}
function CreateIllustThumbBase(a,b){b=0==b?"/IllustViewV.jsp":"/IllustViewPcV.jsp";b=$("<a/>").addClass("IllustThumb").attr("href",b+"?ID="+a.user_id+"&TD="+a.content_id);var c=$("<span/>").addClass("Category C"+a.category_id).html(a.category);a=$("<img/>").addClass("IllustThumbImg").attr("src",a.file_name+"_360.jpg");b.append(c);b.append(a);return b}function CreateIllustItem(a,b){return CreateIllustItemBase(a,b,0)}function CreateIllustItemPc(a,b){return CreateIllustItemBase(a,b,1)}
function CreateIllustItemBase(a,b,c){var d=0==c?"/IllustListV.jsp":"/IllustListPcV.jsp",k=0==c?"/ReportFormV.jsp":"/ReportFormPcV.jsp",g=0==c?"/IllustDetailV.jsp":"/IllustDetailPcV.jsp",h=$("<div/>").addClass("IllustItem").attr("id","IllustItem_"+a.content_id),l=$("<div/>").addClass("IllustItemUser"),f=$("<a/>").addClass("IllustItemUserThumb").attr("href",d+"?ID="+a.user_id),e=$("<img/>").addClass("IllustItemUserThumbImg").attr("src",a.user_file_name+"_120.jpg");d=$("<a/>").addClass("IllustItemUserName").attr("href",
d+"?ID="+a.user_id).html(a.nickname);f.append(e);l.append(f);l.append(d);f=$("<div/>").addClass("IllustItemCommand");e=$("<span/>").addClass("Category C"+a.category_id).html(a.category);f.append(e);e=$("<div/>").addClass("IllustItemCommandSub");d="https://twitter.com/share?url="+encodeURIComponent("https://poipiku.com/"+a.user_id+"/"+a.content_id+".html");d=$("<a/>").addClass("IllustItemCommandTweet fab fa-twitter-square").attr("href",d);var m=$("<a/>").addClass("IllustItemCommandDelete far fa-trash-alt").attr("data-id",
a.content_id).attr("href","javascript:void(0)").click(function(){DeleteContent($(this).data("id"))});k=$("<a/>").addClass("IllustItemCommandInfo fas fa-info-circle").attr("href",k+"?TD="+a.content_id);e.append(d);a.user_id==b?e.append(m):e.append(k);f.append(e);b=$("<div/>").addClass("IllustItemDesc").html(a.description).autoLink();g=$("<a/>").addClass("IllustItemThumb").attr("href",g+"?TD="+a.content_id);1==c&&g.attr("target","_blank");a=$("<img/>").addClass("IllustItemThumbImg").attr("src",a.file_name+
"_640.jpg");g.append(a);h.append(l);h.append(f);h.append(b);h.append(g);return h}function SendComment(a,b,c){if(!(0>=b.length))return $.ajax({type:"post",data:{IID:a,DES:b,UID:c},url:"/f/SendCommentF.jsp",success:function(c){c=$("<span/>").addClass("ResEmoji").html(b);$("#ResEmojiAdd_"+a).before(c)}}),!1}
function DeleteContentBase(a,b){$.ajaxSingle({type:"post",data:{UID:a,CID:b},url:"/f/DeleteContentF.jsp",dataType:"json",success:function(a){$("#IllustItem_"+b).remove()},error:function(a,b,k){DispMsg("Delete Error")}})};
