$(function(){jQuery.extend({ajaxSingle:function(a){var b=!1;return function(a){try{b||(b=!0,a.complete=function(){return function(a,c){b=!1}}(),$.ajax(a))}catch(d){b=!1}}}()})});var vg=null;function setCookie(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; expires=Tue, 31-Dec-2030 23:59:59; "}function setCookieOneTime(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; "}
function setCookieWeek(a,b,c){dateExp=new Date;dateExp.setTime(dateExp.getTime()+6048E5);c=a+"="+encodeURIComponent(b)+"; ";c=c+"path=/; "+("expires="+dateExp.toGMTString());document.cookie=c}function getCookie(a){var b=a+"=";a=document.cookie;var c=a.indexOf(b);if(0>c)return null;b=c+b.length;c=a.indexOf(";",b);-1==c&&(c=a.length);return decodeURIComponent(a.substring(b,c))}
function deleteCookie(a,b){dTime=new Date;dTime.setTime(0);b=a+"="+encodeURIComponent("0")+"; ";b=b+"path=/; "+("expires="+dTime.toGMTString()+"; ");document.cookie=b}function ChLang(a){0<a.length?setCookie("LANG",a):deleteCookie("LANG");$.ajaxSingle({type:"post",data:{LD:"ja"==a?1:0},url:"/f/UpdateLanguageF.jsp",success:function(a){location.reload(!0)}})}function setLocalStrage(a,b){b={val:b};b=JSON.stringify(b);localStorage.setItem(a,b)}
function getLocalStrage(a){a=localStorage.getItem(a);return a?(a=JSON.parse(a))?a.val:null:null}function SearchIllustByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchIllustByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}function SearchTagByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchTagByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}
function SearchUserByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchUserByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}var sendObjectMessage=function(a){var b=document.createElement("iframe");b.setAttribute("src","myurlscheme://"+a);document.documentElement.appendChild(b);b.parentNode.removeChild(b)};
$.fn.autoLink=function(a){var b=0==a?"/SearchIllustByTagV.jsp":"/SearchIllustByTagPcV.jsp";return this.each(function(){var a=this.innerHTML;a=a.replace(/((http|https):\/\/[\w\.\-\/:;&?,=#!~]+)/gi,"<a class='AutoLink' href='$1' target='_blank'>$1</a>");this.innerHTML=a.replace(/(#|\uff03)[\w]*[a-zA-Z0-9\u3041-\u30fe\u30fc-\u9fa5\u8c48-\u9db4]+/g,function(a){a=a.replace(/[#\uff03]/,"");return" <a class='AutoLink' href='"+b+"?KWD="+encodeURIComponent(a)+"'>#"+a+"</a>"})})};
function GotoLogin(){location.href="/LoginFormV.jsp"}function DispMsg(a){0>=$("#DispMsg").length&&$("body").append($("<div/>").attr("id","DispMsg"));$("#DispMsg").html(a);$("#DispMsg").slideDown(200,function(){setTimeout(function(){$("#DispMsg").slideUp(200)},3E3)})}function DispMsgStatic(a){setTimeout(function(){$("#DispMsg").html(a);$("#DispMsg").show()},0)}function HideMsgStatic(){setTimeout(function(){$("#DispMsg").hide()},1E3)}
function SendEmojiAjax(a,b,c,d,e,f,g){var k="",l="",m="";null!=e&&(k=e);null!=f&&(l=f);null!=g&&(m=g);$.ajax({type:"post",data:{IID:a,EMJ:b,UID:c,AMT:d,MDK:k,EXP:l,SEC:m},url:"/f/SendEmojiF.jsp",dataType:"json"}).then(function(b){0<b.result_num&&(b=$("<span/>").addClass("ResEmoji").html(b.result),$("#ResEmojiAdd_"+a).before(b),vg&&vg.vgrefresh(),0<d&&DispMsg(d+"\u5186\u306e\u3054\u652f\u63f4\u3042\u308a\u304c\u3068\u3046\u3054\u3056\u3044\u307e\u3057\u305f\uff01"))})}
function SendEmoji(a,b,c,d,e){d=$(d).parent().parent().children(".ResEmojiNagesen");var f=d.children(".NagesenAmount"),g=f.val();"none"!==d.css("display")&&0<g?(console.log("\u6709\u6599\u30ea\u30a2\u30af\u30b7\u30e7\u30f3"),$.ajax({type:"get",url:"/f/CheckMDKTokenF.jsp",dataType:"json"}).then(function(d){console.log(d);d=d.result;if("undefined"===typeof d||null==d||-1==d)return!1;0==d?(console.log("\u30af\u30ec\u30ab\u5165\u529b\u30c0\u30a4\u30a2\u30ed\u30b0\u3092\u8868\u793a"),Swal.fire({title:"\u30ab\u30fc\u30c9\u60c5\u5831\u3092\u5165\u529b\u3057\u3066\u304f\u3060\u3055\u3044",
html:'\n\u30ab\u30fc\u30c9\u756a\u53f7<input id="card_number" class="swal2-input" value="4111111111111111"/>\n\u6709\u52b9\u671f\u9650(MM/YY)<input id="cc_exp" class="swal2-input" value="02/22"/>\n\u30bb\u30ad\u30e5\u30ea\u30c6\u30a3\u30fc\u30b3\u30fc\u30c9<input id="cc_csc" class="swal2-input" value="012"/>\n<input type="checkbox"/><div>\u5229\u7528\u898f\u7d04\u306b\u540c\u610f\u3057\u307e\u3059</div>\n<input type="checkbox"/><div>\u9078\u629e\u3057\u305f\u91d1\u984d\u3067\u30ea\u30a2\u30af\u30b7\u30e7\u30f3\u3059\u308b\u3068\u81ea\u52d5\u6c7a\u6e08\u3059\u308b\u3053\u3068\u306b\u540c\u610f\u3057\u307e\u3059</div>\n',
focusConfirm:!1,showCloseButton:!0,showCancelButton:!0,preConfirm:function(){return[$("#card_number").val(),$("#cc_exp").val(),$("#cc_csc").val()]}}).then(function(d){if(d.dismiss)return!1;var e=d.value[1],k=d.value[2];d={token_api_key:"cd76ca65-7f54-4dec-8ba3-11c12e36a548",card_number:d.value[0],card_expire:e,security_code:k,lang:"ja"};var h=new XMLHttpRequest;h.open("POST","https://api.veritrans.co.jp/4gtoken",!0);h.setRequestHeader("Accept","application/json");h.setRequestHeader("Content-Type",
"application/json; charset=utf-8");h.addEventListener("loadend",function(){if(0===h.status)alert("\u30c8\u30fc\u30af\u30f3\u30b5\u30fc\u30d0\u30fc\u3068\u306e\u63a5\u7d9a\u306b\u5931\u6557\u3057\u307e\u3057\u305f");else{var d=JSON.parse(h.response);200==h.status?(console.log(d.token),SendEmojiAjax(a,b,c,g,d.token,e,k),f.val("0")):alert(d.message)}});h.send(JSON.stringify(d))})):1==d?(console.log("\u4e0e\u4fe1\u6e08\u307f"),SendEmojiAjax(a,b,c,g,null,null,null),f.val("0")):console.log("\u305d\u306e\u4ed6\u30a8\u30e9\u30fc")},
function(a){console.log("CheckMDKTokenF error"+a)})):SendEmojiAjax(a,b,c,null,null);return!1}function DeleteContentInteractive(a,b,c,d,e,f,g,k,l){Swal.fire({title:"",text:d,type:"question",showCancelButton:!0,confirmButtonText:e,cancelButtonText:f}).then(function(d){d.value&&(c?Swal.fire({title:"",text:g,type:"question",showCancelButton:!0,confirmButtonText:k,cancelButtonText:l}).then(function(c){c.value?DeleteContentBase(a,b,!0):DeleteContentBase(a,b,!1)}):DeleteContentBase(a,b,!1))})}
function DeleteContentBase(a,b,c){$.ajaxSingle({type:"post",data:{UID:a,CID:b,DELTW:c?1:0},url:"/f/DeleteContentF.jsp",dataType:"json",success:function(a){$("#IllustItem_"+b).slideUp(300,function(){$("#IllustItem_"+b).remove();vg&&vg.vgrefresh()})},error:function(a,b,c){DispMsg("Delete Error")}})}
function switchEmojiKeyboard(a,b,c){var d=$(a).parent().parent().children(".ResEmojiBtnList");d.hide();$EmojiNagesen=$(a).parent().parent().children(".ResEmojiNagesen");3===c?$EmojiNagesen.show():$EmojiNagesen.hide();var e=d.eq(c);e.loading||(e.loading=!0,d=$("<div/>").addClass("Waiting"),e.empty(),e.append(d),$.ajax({type:"post",data:{IID:b,CAT:c},url:"/f/GetEmojiListF.jsp",dataType:"html",success:function(a){e.html(a);e.loading=!1;vg&&vg.vgrefresh()},error:function(a,b,c){$(".Waiting").remove();
DispMsg("emoji loading Error");e.loading=!1}}));e.show();$(a).parent().children(".ResBtnSetItem").removeClass("Selected");$(a).addClass("Selected")}function EditDesc(a){$("#IllustItemDesc_"+a).hide();$("#IllustItemTag_"+a).hide();$("#IllustItemDescEdit_"+a).show();$("#IllustItemCategory_"+a).hide();$("#IllustItemCategoryEdit_"+a).show()}
function UpdateDesc(a,b,c){var d=$("#EditCategory_"+b).val(),e=$.trim($("#IllustItemDescEdit_"+b+" .IllustItemDescEditTxt").val());e=e.substr(0,200);var f=$.trim($("#IllustItemDescEdit_"+b+" .IllustItemTagEditTxt").val());f=f.substr(0,100);$.ajaxSingle({type:"post",data:{UID:a,IID:b,CAT:d,DES:e,TAG:f,MOD:c},url:"/f/UpdateDescF.jsp",dataType:"json",success:function(a){$("#IllustItemDesc_"+b).html(a.html);$("#IllustItemDescEdit_"+b+" .IllustItemDescEditTxt").val(a.text);$("#IllustItemTag_"+b).html(a.htmlTag);
$("#IllustItemDescEdit_"+b+" .IllustItemTagEditTxt").val(a.textTag);$("#IllustItemDesc_"+b).show();$("#IllustItemTag_"+b).show();$("#IllustItemDescEdit_"+b).hide();$("#IllustItemCategory_"+b+" .Category").removeClass().addClass("Category C"+d).text(a.category_name);a=$("#IllustItemCategory_"+b+" .Category").attr("href");a=a.replace(/CD=\d+/i,"CD="+d);$("#IllustItemCategory_"+b+" .Category").attr("href",a);$("#IllustItemCategory_"+b).show();$("#IllustItemCategoryEdit_"+b).hide()},error:function(a,
b,c){DispMsg("Connection error")}})}function UpdateFollowTag(a,b,c){$.ajaxSingle({type:"post",data:{UID:a,TXT:b,TYP:c},url:"/f/UpdateFollowTagF.jsp",dataType:"json",success:function(a){0>a.result?DispMsg(a.message):1==a.result?$(".TitleCmdFollow").addClass("Selected"):0==a.result?$(".TitleCmdFollow").removeClass("Selected"):DispMsg("You need to login")},error:function(a,b,c){DispMsg("Connection error")}})}
function UpdateBookmark(a,b){$.ajaxSingle({type:"post",data:{UID:a,IID:b},url:"/f/UpdateBookmarkF.jsp",dataType:"json",success:function(a){1==a.result?$("#IllustItemBookmarkBtn_"+b).addClass("Selected"):0==a.result?$("#IllustItemBookmarkBtn_"+b).removeClass("Selected"):DispMsg("You need to login")},error:function(a,b,e){DispMsg("Connection error")}})}function fixedEncodeURIComponent(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16)})}
function moveTagSearch(a,b){location.href=a+fixedEncodeURIComponent(b)}function updateCategoryMenuPos(a){if($("#CategoryMenu").length&&$("#CategoryMenu .CategoryBtn.Selected").length){var b=$("#CategoryMenu").outerWidth(),c=$("#CategoryMenu").scrollLeft(),d=$("#CategoryMenu .CategoryBtn.Selected").outerWidth();b=$("#CategoryMenu .CategoryBtn.Selected").position().left+c+(d-b)/2;$("#CategoryMenu").animate({scrollLeft:b},a)}}
function ShowAllReaction(a,b){$.ajax({type:"post",data:{IID:a},url:"/f/ShowAllReactionF.jsp",dataType:"json",success:function(c){console.log(c);0<c.result_num?($(b).hide(),$("#IllustItemResList_"+a+" .ResEmoji").remove(),$("#ResEmojiAdd_"+a).before(c.html),vg&&vg.vgrefresh()):$(b).html(c.html)}});return!1}
function generateShowAppendFile(){var a={};return function(b,c,d,e){console.log("twitter friendships: "+a);var f=$("#IllustItem_"+c+' input[name="PAS"]').val(),g=a[b];g||(g=-1);$.ajax({type:"post",data:{UID:b,IID:c,PAS:f,MD:d,TWF:g},url:"/f/ShowAppendFileF.jsp",dataType:"json",success:function(d){console.log(d);0<d.result_num?($("#IllustItem_"+c+" .IllustItemThubExpand").html(d.html),$(e).parent().hide(),$("#IllustItem_"+c).removeClass("R15 R18 R18G Password Login Follower TFollower TFollow TEach TList"),
$("#IllustItem_"+c+" .IllustItemThubExpand").slideDown(300,function(){vg&&vg.vgrefresh()})):DispMsg(d.html);0<=d.tw_friendship&&(a[b]=d.tw_friendship)},error:function(a){console.log(a)}})}}var ShowAppendFile=generateShowAppendFile();
function TweetMyBox(a,b,c,d){a='<h2 class="TweetMyBoxTitle" style="padding: 10px 0 0 0;">'+c.TweetTitle+'</h2><h3 class="TweetMyBoxSubTitle">'+c.TweetStep1+'</h3><div class="TweetMyBoxInfo"><a class="BtnBase Selected TweetMyBoxBtn" href="'+b+'" target="_blank"><i class="fab fa-twitter"></i> '+c.TweetTweet+'</a><i class="fa fa-info-circle"></i> '+c.TweetInfo1+'</div><h3 class="TweetMyBoxSubTitle">'+c.TweetStep2+'</h3><div class="TweetMyBoxInfoStep2">'+c.TweetInfo2+'</div><div class="TweetMyBoxPinLink"><a href="/how_to/TwPinPcV.jsp" target="_blank">'+
c.TweetHowToPin+'</a></div><hr class="TweetMyBoxHr"/><h2 class="TweetMyBoxTitle">'+c.ShareURLTitle+'</h2><div><input id="MyBoxUrlTxt" type="text" readonly value="'+a+'"><a id="CopyMyBoxUrlBtn" class="BtnBase Selected" href="javascript:void(0);">'+c.ShareURLCopy+'</a></div><h2 class="TweetMyBoxTitle">'+c.ShareQRTitle+'</h2><div class="MyBoxQRCode"><div class="QRCode"><span id="QRCodeImg"></span>';d||(a+='<span class="DownloadMyBoxQR"><a id="DownloadMyBoxQRBtn" class="BtnBase Selected" href="javascript:void(0);">'+
c.ShareQRDownload+"</a></span>");Swal.fire({html:a+"</div></div>",showCloseButton:!0,showCancelButton:!1,showConfirmButton:!1,onOpen:function(){$("#QRCodeImg").qrcode({width:64,height:64,text:$("#MyBoxUrlTxt").val()});$("#CopyMyBoxUrlBtn").click(function(){$("#MyBoxUrlTxt").select();document.execCommand("Copy");alert(c.ShareURLCopied)});$("#DownloadMyBoxQRBtn").click(function(){var a=$("#QRCodeImg canvas")[0],b=document.createElement("a");b.href=a.toDataURL("image/png");b.download="poipiku_qrcode.png";
b.click()})}})};
