function setCookie(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; expires=Tue, 31-Dec-2030 23:59:59; "}function setCookieOneTime(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; "}function setCookieWeek(a,b,c){dateExp=new Date;dateExp.setTime(dateExp.getTime()+6048E5);c=a+"="+encodeURIComponent(b)+"; ";c=c+"path=/; "+("expires="+dateExp.toGMTString());document.cookie=c}
function getCookie(a){var b=a+"=";a=document.cookie;var c=a.indexOf(b);if(0>c)return null;b=c+b.length;c=a.indexOf(";",b);-1==c&&(c=a.length);return decodeURIComponent(a.substring(b,c))}function deleteCookie(a,b){dTime=new Date;dTime.setTime(0);b=a+"="+encodeURIComponent("0")+"; ";b=b+"path=/; "+("expires="+dTime.toGMTString()+"; ");document.cookie=b}
function ChLang(a){0<a.length?setCookie("MK_LANG",a):deleteCookie("MK_LANG");$.ajaxSingle({type:"post",data:{LD:"ja"==a?1:0},url:"/FUpdateLanguage.jsp",success:function(a){location.reload(!0)}})}function SearchIllustByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchIllustByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}function SearchTagByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchTagByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}
function SearchUserByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchUserByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}var sendObjectMessage=function(a){var b=document.createElement("iframe");b.setAttribute("src","myurlscheme://"+a);document.documentElement.appendChild(b);b.parentNode.removeChild(b)};
$.fn.autoLink=function(a){var b=0==a?"/SearchIllustByTagV.jsp":"/SearchIllustByTagPcV.jsp";return this.each(function(){var a=this.innerHTML;a=a.replace(/((http|https):\/\/[\w\.\-\/:;&?,=#!~]+)/gi,"<a class='AutoLink' href='$1' target='_blank'>$1</a>");this.innerHTML=a.replace(/(#|\uff03)[\w]*[a-zA-Z0-9\u3041-\u30fe\u30fc-\u9fa5\u8c48-\u9db4]+/g,function(a){a=a.replace(/[#\uff03]/,"");return" <a class='AutoLink' href='"+b+"?KWD="+encodeURIComponent(a)+"'>#"+a+"</a>"})})};
function GotoLogin(){location.href="/LoginFormV.jsp"}function DispMsg(a){$("#DispMsg").html(a);$("#DispMsg").slideDown(200,function(){setTimeout(function(){$("#DispMsg").slideUp(200)},3E3)})}function DispMsgStatic(a){setTimeout(function(){$("#DispMsg").html(a);$("#DispMsg").show()},0)}function HideMsgStatic(){setTimeout(function(){$("#DispMsg").hide()},1E3)}
$(function(){jQuery.extend({ajaxSingle:function(a){var b=!1;return function(a){try{b||(b=!0,a.complete=function(){return function(a,c){b=!1}}(),$.ajax(a))}catch(e){b=!1}}}()});$(window).on("scroll",function(){75<=$(this).scrollTop()?$(".MainMenu").addClass("Fixed"):$(".MainMenu").removeClass("Fixed")})});function CreateIllustThumb(a){return CreateIllustThumbBase(a,0)}function CreateIllustThumbPc(a){return CreateIllustThumbBase(a,1)}
function CreateIllustThumbBase(a,b){b=0==b?"/IllustViewV.jsp":"/IllustViewPcV.jsp";b=$("<a/>").addClass("IllustThumb").attr("href",b+"?ID="+a.user_id+"&TD="+a.content_id);var c=$("<span/>").addClass("Category C"+a.category_id).html(a.category);a=$("<img/>").addClass("IllustThumbImg").attr("src",a.file_name+"_360.jpg");b.append(c);b.append(a);return b}function CreateIllustItem(a,b){return CreateIllustItemBase(a,b,0)}function CreateIllustItemPc(a,b){return CreateIllustItemBase(a,b,1)}
function CreateIllustItemBase(a,b,c){var e=0==c?"/IllustListV.jsp":"/IllustListPcV.jsp",d=0==c?"/IllustCommentV.jsp":"/IllustCommentPcV.jsp",f=0==c?"/IllustHeartV.jsp":"/IllustHeartPcV.jsp",g=0==c?"/ReportFormV.jsp":"/ReportFormPcV.jsp",m=0==c?"/IllustDetailV.jsp":"/IllustDetailPcV.jsp",h=$("<div/>").addClass("IllustItem").attr("id","IllustItem_"+a.content_id),n=$("<div/>").addClass("IllustItemUser"),l=$("<a/>").addClass("IllustItemUserThumb").attr("href",e+"?ID="+a.user_id),k=$("<img/>").addClass("IllustItemUserThumbImg").attr("src",
a.user_file_name+"_120.jpg");e=$("<a/>").addClass("IllustItemUserName").attr("href",e+"?ID="+a.user_id).html(a.nickname);l.append(k);n.append(l);n.append(e);l=$("<span/>").addClass("Category C"+a.category_id).html(a.category);m=$("<a/>").addClass("IllustItemThumb").attr("href",m+"?TD="+a.content_id);1==c&&m.attr("target","_blank");k=$("<img/>").addClass("IllustItemThumbImg").attr("src",a.file_name+"_640.jpg");m.append(k);k=$("<div/>").addClass("IllustItemCommand");e=$("<a/>").addClass("IllustItemCommandComment").addClass("typcn").addClass("typcn-message").attr("href",
d+"?TD="+a.content_id);d=$("<a/>").attr("id","IllustItemCommandCommentNum_"+a.content_id).addClass("IllustItemCommandCommentNum").html("&nbsp;"+a.comment_num).attr("href",d+"?TD="+a.content_id);var p=$("<a/>").attr("id","IllustItemCommandHeart_"+a.content_id).addClass("IllustItemCommandHeart").addClass("typcn").addClass("typcn-heart-outline").attr("data-id",a.content_id).attr("href","javascript:void(0)").click(function(){UpdateBookmark($(this).data("id"))});1==a.bookmark&&p.removeClass("typcn-heart-outline").addClass("typcn-heart-full-outline").addClass("Selected");
f=$("<a/>").addClass("IllustItemCommandHeartNum").attr("id","IllustItemCommandHeartNum_"+a.content_id).html("&nbsp;"+a.bookmark_num).attr("href",f+"?ID="+a.user_id+"&TD="+a.content_id);k.append(e);k.append(d);k.append(p);k.append(f);f=$("<div/>").addClass("IllustItemCommandSub");d="https://twitter.com/share?url="+encodeURIComponent("https://poipiku.com/"+a.user_id+"/"+a.content_id+".html");d=$("<a/>").addClass("social-icon").addClass("Twitter").attr("href",d).html("&#229;");e=$("<a/>").addClass("IllustItemCommandDelete").addClass("typcn").addClass("typcn-trash").attr("data-id",
a.content_id).attr("href","javascript:void(0)").click(function(){DeleteContent($(this).data("id"))});g=$("<a/>").addClass("IllustItemCommandInfo").addClass("typcn").addClass("typcn-info-large").attr("href",g+"?TD="+a.content_id);f.append(d);a.user_id==b?f.append(e):f.append(g);k.append(f);g=$("<div/>").addClass("ItemComment").addClass("Home");d=!1;for(e=0;e<a.comment.length;e++)d=a.comment[e],f=CreateCommentItemBase(a.content_id,d.user_id,d.nickname,d.to_user_id,d.to_nickname,d.description,c),g.append(f),
d=a.user_id==b&&d.user_id!=b;f=$("<div/>").addClass("ItemCommentItem");b=$("<div/>").addClass("CommentTo").attr("id","CommentTo_"+a.content_id);p=$("<span/>").html("> ");c=$("<span/>").addClass("CommentToTxt").attr("id","CommentToTxt_"+a.content_id);e=$("<input/>").attr("id","CommentToId_"+a.content_id).attr("type","hidden").val(0);var q=$("<span/>").addClass("typcn typcn-times").attr("data-id",a.content_id).click(function(){DeleteRes($(this).data("id"))});b.append(p).append(c).append(e).append(q);
d&&(d=a.comment[a.comment.length-1],b.show(),c.html(d.nickname),e.val(d.user_id));c=$("<input/>").addClass("CommentDescTxt").attr("id","CommentDescTxt_"+a.content_id).attr("type","text").attr("maxlength","200").attr("data-id",a.content_id);d=$("<div/>").addClass("CommentDescBtn");a=$("<a/>").addClass("BtnBase typcn typcn-message").attr("data-id",a.content_id).click(function(){SendComment($(this).data("id"))});d.html(" ").append(a);f.append(c).append(d);g.append(b);g.append(f);h.append(n);h.append(l);
h.append(m);h.append(k);h.append(g);return h}function CreateCommentItem(a,b,c,e,d,f){return CreateCommentItemBase(a,b,c,e,d,f,0)}function CreateCommentItemPc(a,b,c,e,d,f){return CreateCommentItemBase(a,b,c,e,d,f,1)}
function CreateCommentItemBase(a,b,c,e,d,f,g){var m=0==g?"/IllustListV.jsp":"/IllustListPcV.jsp",h=$("<div/>").addClass("ItemCommentItem"),n=$("<a/>").addClass("CommentName").attr("href",m+"?ID="+b).html(c),l=$("<span/>").addClass("CommentDesc");0<e&&(e=$("<a/>").addClass("CommentName").attr("href",m+"?ID="+e).html("> "+d),l.append(e));f=$("<span/>").html(f+" ").autoLink(g);g=$("<span/>").addClass("CommentCmd");a=$("<a/>").addClass("fa fa-reply").attr("data-id",a).attr("data-uid",b).attr("data-nickname",
c).click(function(){ResComment($(this).data("id"),$(this).data("uid"),$(this).data("nickname"))});g.append(a);l.append(f);l.append(g);h.append(n);h.append(l);return h};
