function setCookie(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; expires=Tue, 31-Dec-2030 23:59:59; "}function setCookieOneTime(a,b,c){c=a+"="+encodeURIComponent(b)+"; ";document.cookie=c+"path=/; "}function setCookieWeek(a,b,c){dateExp=new Date;dateExp.setTime(dateExp.getTime()+6048E5);c=a+"="+encodeURIComponent(b)+"; ";c=c+"path=/; "+("expires="+dateExp.toGMTString());document.cookie=c}
function getCookie(a){var b=a+"=";a=document.cookie;var c=a.indexOf(b);if(0>c)return null;b=c+b.length;c=a.indexOf(";",b);-1==c&&(c=a.length);return decodeURIComponent(a.substring(b,c))}function deleteCookie(a,b){dTime=new Date;dTime.setTime(0);b=a+"="+encodeURIComponent("0")+"; ";b=b+"path=/; "+("expires="+dTime.toGMTString()+"; ");document.cookie=b}
function ChLang(a){0<a.length?setCookie("MK_LANG",a):deleteCookie("MK_LANG");$.ajaxSingle({type:"post",data:{LD:"ja"==a?1:0},url:"/FUpdateLanguage.jsp",success:function(a){location.reload(!0)}})}function SearchIllustByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchIllustByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}function SearchTagByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchTagByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}
function SearchUserByKeyword(){var a=$("#HeaderSearchBox").val();location.href="/SearchUserByKeywordPcV.jsp?KWD="+encodeURIComponent(a)}var sendObjectMessage=function(a){var b=document.createElement("iframe");b.setAttribute("src","myurlscheme://"+a);document.documentElement.appendChild(b);b.parentNode.removeChild(b)};
$.fn.autoLink=function(a){var b=0==a?"/SearchIllustByTagV.jsp":"/SearchIllustByTagPcV.jsp";return this.each(function(){var a=this.innerHTML;a=a.replace(/((http|https):\/\/[\w\.\-\/:;&?,=#!~]+)/gi,"<a class='AutoLink' href='$1' target='_blank'>$1</a>");this.innerHTML=a.replace(/(#|\uff03)[\w]*[a-zA-Z0-9\u3041-\u30fe\u30fc-\u9fa5\u8c48-\u9db4]+/g,function(a){a=a.replace(/[#\uff03]/,"");return" <a class='AutoLink' href='"+b+"?KWD="+encodeURIComponent(a)+"'>#"+a+"</a>"})})};
function GotoLogin(){location.href="/LoginFormV.jsp"}function DispMsg(a){$("#DispMsg").html(a);$("#DispMsg").slideDown(200,function(){setTimeout(function(){$("#DispMsg").slideUp(200)},3E3)})}function DispMsgStatic(a){setTimeout(function(){$("#DispMsg").html(a);$("#DispMsg").show()},0)}function HideMsgStatic(){setTimeout(function(){$("#DispMsg").hide()},1E3)}
$(function(){jQuery.extend({ajaxSingle:function(a){var b=!1;return function(a){try{b||(b=!0,a.complete=function(){return function(a,c){b=!1}}(),$.ajax(a))}catch(d){b=!1}}}()});$(window).on("scroll",function(){75<=$(this).scrollTop()?$(".MainMenu").addClass("Fixed"):$(".MainMenu").removeClass("Fixed")})});
function SendEmoji(a,b,c){$.ajax({type:"post",data:{IID:a,EMJ:b,UID:c},url:"/f/SendEmojiF.jsp",dataType:"json",success:function(b){0<b.result_num&&(b=$("<span/>").addClass("ResEmoji").html(b.result),$("#ResEmojiAdd_"+a).before(b))}});return!1}function DeleteContentBase(a,b){$.ajaxSingle({type:"post",data:{UID:a,CID:b},url:"/f/DeleteContentF.jsp",dataType:"json",success:function(a){$("#IllustItem_"+b).remove()},error:function(a,b,e){DispMsg("Delete Error")}})}
function switchEmojiKeyboard(a,b){$ResEmojiBtnList=$(a).parent().parent().children(".ResEmojiBtnList");$ResEmojiBtnList.hide();$ResEmojiBtnList.eq(b).show();$(a).parent().children(".ResBtnSetItem").removeClass("Selected");$(a).addClass("Selected")};
