$(function(){jQuery.extend({ajaxSingle:function(c){var a=!1;return function(b){try{a||(a=!0,b.complete=function(){return function(d,e){a=!1}}(),$.ajax(b))}catch(d){a=!1}}}()})});var vg=null;function setCookie(c,a,b){b=c+"="+encodeURIComponent(a)+"; ";document.cookie=b+"path=/; expires=Tue, 31-Dec-2030 23:59:59; "}function setCookieOneTime(c,a,b){b=c+"="+encodeURIComponent(a)+"; ";document.cookie=b+"path=/; "}
function setCookieWeek(c,a,b){dateExp=new Date;dateExp.setTime(dateExp.getTime()+6048E5);b=c+"="+encodeURIComponent(a)+"; ";b=b+"path=/; expires="+dateExp.toGMTString();document.cookie=b}function setCookieOneDay(c,a,b){dateExp=new Date;dateExp.setTime(dateExp.getTime()+864E5);b=c+"="+encodeURIComponent(a)+"; ";b=b+"path=/; expires="+dateExp.toGMTString();document.cookie=b}
function getCookie(c){var a=c+"=";c=document.cookie;var b=c.indexOf(a);if(0>b)return null;a=b+a.length;b=c.indexOf(";",a);-1==b&&(b=c.length);return decodeURIComponent(c.substring(a,b))}function deleteCookie(c,a){dTime=new Date;dTime.setTime(0);a=c+"="+encodeURIComponent("0")+"; ";a=a+"path=/; expires="+(dTime.toGMTString()+"; ");document.cookie=a}
function ChLang(c){0<c.length?setCookie("LANG",c):deleteCookie("LANG");$.ajaxSingle({type:"post",data:{LD:"ja"==c?1:0},url:"/f/UpdateLanguageF.jsp",success:function(a){location.reload(!0)}})}function setLocalStrage(c,a){a={val:a};a=JSON.stringify(a);localStorage.setItem(c,a)}function getLocalStrage(c){c=localStorage.getItem(c);return c?(c=JSON.parse(c))?c.val:null:null}
function SearchIllustByKeyword(){var c=$("#HeaderSearchBox").val();location.href="/SearchIllustByKeywordPcV.jsp?KWD="+encodeURIComponent(c)}function SearchTagByKeyword(){var c=$("#HeaderSearchBox").val();location.href="/SearchTagByKeywordPcV.jsp?KWD="+encodeURIComponent(c)}function SearchUserByKeyword(){var c=$("#HeaderSearchBox").val();location.href="/SearchUserByKeywordPcV.jsp?KWD="+encodeURIComponent(c)}
var sendObjectMessage=function(c){var a=document.createElement("iframe");a.setAttribute("src","myurlscheme://"+c);document.documentElement.appendChild(a);a.parentNode.removeChild(a)};
$.fn.autoLink=function(c){var a=0==c?"/SearchIllustByTagV.jsp":"/SearchIllustByTagPcV.jsp";return this.each(function(){var b=this.innerHTML;b=b.replace(/((http|https):\/\/[\w\.\-\/:;&?,=#!~]+)/gi,"<a class='AutoLink' href='$1' target='_blank'>$1</a>");this.innerHTML=b.replace(/(#|\uff03)[\w]*[a-zA-Z0-9\u3041-\u30fe\u30fc-\u9fa5\u8c48-\u9db4]+/g,function(d){d=d.replace(/[#\uff03]/,"");return" <a class='AutoLink' href='"+a+"?KWD="+encodeURIComponent(d)+"'>#"+d+"</a>"})})};
function GotoLogin(){location.href="/LoginFormV.jsp"}function DispMsg(c){0>=$("#DispMsg").length&&$("body").append($("<div/>").attr("id","DispMsg"));$("#DispMsg").html(c);$("#DispMsg").slideDown(200,function(){setTimeout(function(){$("#DispMsg").slideUp(200)},3E3)})}function DispMsgStatic(c){0>=$("#DispMsg").length&&$("body").append($("<div/>").attr("id","DispMsg"));setTimeout(function(){$("#DispMsg").html(c);$("#DispMsg").slideDown(200)},0)}
function HideMsgStatic(){setTimeout(function(){$("#DispMsg").slideUp(200)},1E3)}function DeleteContentInteractive(c,a,b,d,e,g,f,h,k){Swal.fire({title:"",text:d,type:"question",showCancelButton:!0,confirmButtonText:e,cancelButtonText:g}).then(function(l){l.value&&(b?Swal.fire({title:"",text:f,type:"question",showCancelButton:!0,confirmButtonText:h,cancelButtonText:k}).then(function(m){m.value?DeleteContentBase(c,a,!0):DeleteContentBase(c,a,!1)}):DeleteContentBase(c,a,!1))})}
function DeleteContentBase(c,a,b){$.ajaxSingle({type:"post",data:{UID:c,CID:a,DELTW:b?1:0},url:"/f/DeleteContentF.jsp",dataType:"json",success:function(d){$("#IllustItem_"+a).slideUp(300,function(){$("#IllustItem_"+a).remove();vg&&vg.vgrefresh()})},error:function(d,e,g){DispMsg("Delete Error")}})}
function switchEmojiKeyboard(c,a,b){var d=$(c).parent().parent().children(".ResEmojiBtnList");d.hide();var e=d.eq(b);e.loading||(e.loading=!0,d=$("<div/>").addClass("Waiting"),e.empty(),e.append(d),$.ajax({type:"post",data:{IID:a,CAT:b},url:"/f/GetEmojiListF.jsp",dataType:"html",success:function(g){e.html(g);e.loading=!1;vg&&vg.vgrefresh()},error:function(g,f,h){$(".Waiting").remove();DispMsg("emoji loading Error");e.loading=!1}}));e.show();$(c).parent().children(".ResBtnSetItem").removeClass("Selected");
$(c).addClass("Selected")}function EditDesc(c){$("#IllustItemDesc_"+c).hide();$("#IllustItemTag_"+c).hide();$("#IllustItemDescEdit_"+c).show();$("#IllustItemCategory_"+c).hide();$("#IllustItemCategoryEdit_"+c).show()}
function UpdateDesc(c,a,b){var d=$("#EditCategory_"+a).val(),e=$.trim($("#IllustItemDescEdit_"+a+" .IllustItemDescEditTxt").val());e=e.substr(0,200);var g=$.trim($("#IllustItemDescEdit_"+a+" .IllustItemTagEditTxt").val());g=g.substr(0,100);$.ajaxSingle({type:"post",data:{UID:c,IID:a,CAT:d,DES:e,TAG:g,MOD:b},url:"/f/UpdateDescF.jsp",dataType:"json",success:function(f){$("#IllustItemDesc_"+a).html(f.html);$("#IllustItemDescEdit_"+a+" .IllustItemDescEditTxt").val(f.text);$("#IllustItemTag_"+a).html(f.htmlTag);
$("#IllustItemDescEdit_"+a+" .IllustItemTagEditTxt").val(f.textTag);$("#IllustItemDesc_"+a).show();$("#IllustItemTag_"+a).show();$("#IllustItemDescEdit_"+a).hide();$("#IllustItemCategory_"+a+" .Category").removeClass().addClass("Category C"+d).text(f.category_name);f=$("#IllustItemCategory_"+a+" .Category").attr("href");f=f.replace(/CD=\d+/i,"CD="+d);$("#IllustItemCategory_"+a+" .Category").attr("href",f);$("#IllustItemCategory_"+a).show();$("#IllustItemCategoryEdit_"+a).hide()},error:function(f,
h,k){DispMsg("Connection error")}})}function UpdateFollowGenre(c,a){$.ajaxSingle({type:"post",data:{UID:c,GD:a},url:"/api/UpdateFollowGenreF.jsp",dataType:"json",success:function(b){1==b.result?$(".TitleCmdFollow").addClass("Selected"):0==b.result&&$(".TitleCmdFollow").removeClass("Selected");DispMsg(b.message)},error:function(b,d,e){DispMsg("Connection error")}})}
function UpdateFollowTag(c,a){$.ajaxSingle({type:"post",data:{UID:c,TXT:a},url:"/api/UpdateFollowTagF.jsp",dataType:"json",success:function(b){0>b.result?DispMsg(b.message):1==b.result?$(".TitleCmdFollow").addClass("Selected"):0==b.result?$(".TitleCmdFollow").removeClass("Selected"):DispMsg("You need to login")},error:function(b,d,e){DispMsg("Connection error")}})}
function UpdateBookmark(c,a){$.ajaxSingle({type:"post",data:{UID:c,IID:a},url:"/api/UpdateBookmarkF.jsp",dataType:"json",success:function(b){0==b.result?$("#IllustItemBookmarkBtn_"+a).removeClass("Selected"):1==b.result?$("#IllustItemBookmarkBtn_"+a).addClass("Selected"):2==b.result?DispMsg(b.msg):-2==b.result&&DispMsg(b.msg)},error:function(b,d,e){DispMsg("Connection error")}})}
function fixedEncodeURIComponent(c){return encodeURIComponent(c).replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16)})}function moveTagSearch(c,a){location.href=c+fixedEncodeURIComponent(a)}
function updateCategoryMenuPos(c){if($("#CategoryMenu").length&&$("#CategoryMenu .CategoryBtn.Selected").length){var a=$("#CategoryMenu").outerWidth(),b=$("#CategoryMenu").scrollLeft(),d=$("#CategoryMenu .CategoryBtn.Selected").outerWidth();a=$("#CategoryMenu .CategoryBtn.Selected").position().left+b+(d-a)/2;$("#CategoryMenu").animate({scrollLeft:a},c)}}
function ShowAllReaction(c,a){$.ajax({type:"post",data:{IID:c},url:"/f/ShowAllReactionF.jsp",dataType:"json",success:function(b){console.log(b);0<b.result_num?($(a).hide(),$("#IllustItemResList_"+c+" .ResEmoji").remove(),$("#ResEmojiAdd_"+c).before(b.html),vg&&vg.vgrefresh()):$(a).html(b.html)}});return!1}
function generateShowAppendFile(){var c={};return function(a,b,d,e){console.log(a,b,d);console.log("twitter friendships: "+c);var g=$("#IllustItem_"+b+' input[name="PAS"]').val(),f=c[a];f||(f=-1);$.ajax({type:"post",data:{UID:a,IID:b,PAS:g,MD:d,TWF:f},url:"/f/ShowAppendFileF.jsp",dataType:"json",success:function(h){0<h.result_num?($("#IllustItem_"+b+" .IllustItemThubExpand").html(h.html),$(e).parent().hide(),$("#IllustItem_"+b).removeClass("R15 R18 R18G Password Login Follower TFollower TFollow TEach TList"),
$("#IllustItem_"+b+" .IllustItemThubExpand").slideDown(300,function(){vg&&vg.vgrefresh()}),$("#IllustItemText_"+b).css("max-height","none")):DispMsg(h.html);0<=h.tw_friendship&&(c[a]=h.tw_friendship)},error:function(h){console.log(h)}})}}var ShowAppendFile=generateShowAppendFile();
function TweetMyBox(c,a,b,d){c='<h2 class="TweetMyBoxTitle" style="padding: 10px 0 0 0;">'+b.TweetTitle+'</h2><h3 class="TweetMyBoxSubTitle">'+b.TweetStep1+'</h3><div class="TweetMyBoxInfo"><a class="BtnBase Selected TweetMyBoxBtn" href="'+a+'" target="_blank"><i class="fab fa-twitter"></i> '+b.TweetTweet+'</a><i class="fa fa-info-circle"></i> '+b.TweetInfo1+'</div><h3 class="TweetMyBoxSubTitle">'+b.TweetStep2+'</h3><div class="TweetMyBoxInfoStep2">'+b.TweetInfo2+'</div><div class="TweetMyBoxPinLink"><a href="/how_to/TwPinPcV.jsp" target="_blank">'+
b.TweetHowToPin+'</a></div><hr class="TweetMyBoxHr"/><h2 class="TweetMyBoxTitle">'+b.ShareURLTitle+'</h2><div><input id="MyBoxUrlTxt" type="text" readonly value="'+c+'"><a id="CopyMyBoxUrlBtn" class="BtnBase Selected" href="javascript:void(0);">'+b.ShareURLCopy+'</a></div><h2 class="TweetMyBoxTitle">'+b.ShareQRTitle+'</h2><div class="MyBoxQRCode"><div class="QRCode"><span id="QRCodeImg"></span>';d||(c+='<span class="DownloadMyBoxQR"><a id="DownloadMyBoxQRBtn" class="BtnBase Selected" href="javascript:void(0);">'+
b.ShareQRDownload+"</a></span>");Swal.fire({html:c+"</div></div>",showCloseButton:!0,showCancelButton:!1,showConfirmButton:!1,onOpen:function(){$("#QRCodeImg").qrcode({width:64,height:64,text:$("#MyBoxUrlTxt").val()});$("#CopyMyBoxUrlBtn").click(function(){$("#MyBoxUrlTxt").select();document.execCommand("Copy");alert(b.ShareURLCopied)});$("#DownloadMyBoxQRBtn").click(function(){var e=$("#QRCodeImg canvas")[0],g=document.createElement("a");g.href=e.toDataURL("image/png");g.download="poipiku_qrcode.png";
g.click()})}})}var g_chartAnalyze;
function initGraph(c){return new Chart(c,{type:"doughnut",data:{labels:["https://img-cdn.poipiku.com/img/pc_top_title-03.png"],datasets:[{data:[100],backgroundColor:["#3498db"]}]},options:{legend:{position:"top",display:!1},animation:{animateScale:!0,animateRotate:!0},tooltips:{enabled:!1},events:[]},plugins:[{afterRender:function(a){var b=a.ctx;a.data.datasets.forEach(function(d,e){e=a.getDatasetMeta(e);e.hidden||e.data.forEach(function(g,f){if(a.data.labels[f]){var h=d.data[f].toString()+"%";b.fillStyle=
"#ffffff";b.font=Chart.helpers.fontString(14,"normal","Verdana");b.textAlign="center";b.textBaseline="middle";var k=g.tooltipPosition(),l=new Image;l.src=a.data.labels[f];l.onload=function(){b.drawImage(l,k.x-12,k.y-24,24,24)};b.fillText(h,k.x,k.y+10)}})});console.log("afterRender")}}]})}function setGraphData(c){g_chartAnalyze.data=c}function updateGraph(){g_chartAnalyze.clear();g_chartAnalyze.update()};
