function UpdateFileOrder(b,d,f){var e=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(a,c){e.push(parseInt(c))});$.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(e)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result);f&&0<f.length&&(completeMsg(),setTimeout(function(){location.href=f},1E3))},error:function(a){console.log(a)}})}
function UpdatePasteOrderAjax(b,d,f){return $.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(f)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(b,d,f,e){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+f,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:b,sizeLimit:1048576*d,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,c){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",a),this.setParams({UID:this.user_id,IID:this.content_id},a))},onComplete:function(a,c,g,h){append_id=g.append_id;$(".qq-file-id-"+a).attr("id",append_id)},onAllComplete:function(a,c){console.log("onAllComplete",a,c,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListPcV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(a){var c=this.getSubmittedSize(),g=this.getSubmittedNum();this.showTotalSize(c,g);c+=a.size;if(c>this.total_size)return!1;this.showTotalSize(c,g+1)},onStatusChange:function(a,c,g){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),c=0;$.each(a,function(){c+=this.size});return c};multiFileUploader.showTotalSize=function(a,c){var g="(jpeg|png|gif, "+b+"files, total "+d+"MByte)";0<a&&(g="("+c+"/"+b+"files "+Math.ceil(a/1024/1024)+"/"+d+"MByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(g)};multiFileUploader.sessionRequestComplete=function(a,c,g,h){alert(c)};multiFileUploader.total_size=52428800}
function Tweet(b,d,f,e){$.ajax({type:"post",data:{UID:b,IID:d,IMG:f,DELTW:e},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(a){tweetSucceeded(a.result)}})}
function UpdateFile(b,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var f=$("#TagInputItemData").val(),e=parseInt($("#EditCategory").val(),10),a=$.trim($("#EditDescription").val()),c=$.trim($("#EditTagList").val());c=c.substr(0,100);var g=parseInt($("#ContentOpenId").val(),10),h=parseInt($("#EditPublish").val(),10),u=$("#EditPassword").val(),p=$("#OptionCheerNg").prop("checked")?0:1,z=$("#OptionRecent").prop("checked")?1:0,v=$("#OptionTweet").prop("checked")?
1:0,x=$("#OptionImage").prop("checked")?1:0,k=$("#OptionDeleteTweet").prop("checked")?1:0,w=null,q=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),l=null,m=null;if(10===h){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}w=$("#EditTwitterList").val()}if(1===q&&(l=getPublishDateTime($("#EditTimeLimitedStart").val()),m=getPublishDateTime($("#EditTimeLimitedEnd").val()),!checkPublishDatetime(l,m,!1)))return;$("#TagInputItemData").length||(f=1);setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99===h&&(v=0);startMsg();var r=v;1===q&&(r=2===g||null!=strPublishStartPresent&&null!=strPublishEndPresent?1===v&&2!==g&&comparePublishDate(strPublishStartPresent,l)&&comparePublishDate(strPublishEndPresent,m)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:b,GD:f,CAT:e,DES:a,TAG:c,PID:h,PPW:u,PLD:w,LTP:q,REC:z,PST:l,PED:m,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:k,ED:0,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",
dataType:"json",success:function(n){n&&0<n.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=b,multiFileUploader.content_id=n.content_id,multiFileUploader.tweet=r,multiFileUploader.tweet_image=x,multiFileUploader.delete_tweet=k,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1===r?(UpdateFileOrder(b,n.content_id,null),Tweet(b,n.content_id,x,k)):UpdateFileOrder(b,n.content_id,"/MyIllustListPcV.jsp"):errorMsg()}})}}
function initUpdatePaste(b,d){updateTweetButton();var f=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==f&&$("#EditCategory").val(f)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(e,a){10>$(".InputFile").length&&(e=createPasteElm(a.dataURL),$("#PasteZone").append(e),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(e,a){a.url&&
alert("error data : "+a.url)}).on("pasteText",function(e,a){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:b,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(e){$.each(e,function(a,c){10>$(".InputFile").length&&(a=createPasteListItem(c.thumbnailUrl,c.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(b,d,f){b.parent().addClass("Done");b=b.attr("src").replace("data:image/png;base64,","");return 0>=b.length?null:$.ajax({type:"post",data:{UID:d,IID:f,DATA:b},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}
function UpdateFileRefTwitterFAjax(b,d,f,e,a,c,g,h,u,p,z,v,x,k,w,q,l){return $.ajax({type:"post",data:{UID:b,IID:d,GD:f,CAT:e,DES:a,TAG:c,PID:g,PPW:h,PLD:u,LTP:v,REC:z,PST:x,PED:k,TWT:w,TWI:q,DELTW:l,ED:1,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadTextRefTwitterFAjax(b,d,f,e,a,c,g,h,u,p,z,v,x,k,w,q,l,m){return $.ajax({type:"post",data:{UID:b,IID:d,GD:f,CAT:e,DES:a,BDY:c,TAG:g,PID:h,PPW:u,PLD:p,LTP:x,REC:v,PST:k,PED:w,TWT:q,TWI:l,DELTW:m,ED:1,CNG:z},url:"/f/UpdateTextRefTwitterF.jsp",dataType:"json"})}function UploadFileTweetFAjax(b,d,f,e){return $.ajax({type:"post",data:{UID:b,IID:d,IMG:f,DELTW:e},url:"/api/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var b=!1;return function(d,f){if(!b){b=!0;var e=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&e++});if(0>=e)b=!1;else{var a=$("#TagInputItemData").val(),c=parseInt($("#EditCategory").val(),10),g=$.trim($("#EditDescription").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var u=$("#ContentOpenId").val(),p=parseInt($("#EditPublish").val(),10),z=$("#EditPassword").val(),v=$("#OptionCheerNg").prop("checked")?0:1,x=$("#OptionRecent").prop("checked")?
1:0,k=$("#OptionTweet").prop("checked")?1:0,w=$("#OptionImage").prop("checked")?1:0,q=$("#OptionDeleteTweet").prop("checked")?1:0,l=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,n=null;if(10===p){if($("#TwitterListNotFound").is(":visible")){b=!1;twitterListNotFoundMsg();return}l=$("#EditTwitterList").val()}if(1===m&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),n=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),
strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(r,n,!0,strPublishStartPresent,strPublishEndPresent))){b=!1;return}$("#TagInputItemData").length||(a=1);setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99===p&&(k=0);var B=k;1===m&&(B=2===u||null!=strPublishStartPresent&&null!=strPublishEndPresent?1===k&&2!==u&&comparePublishDate(strPublishStartPresent,r)&&comparePublishDate(strPublishEndPresent,
n)?1:0:0);startMsg();var A=[],C=null;UpdateFileRefTwitterFAjax(d,f,a,c,g,h,p,z,l,v,x,m,r,n,getTweetSetting(),getTweetImageSetting(),q).done(function(y){var E=null;$(".imgView").each(function(){E=UpdatePasteAppendFAjax($(this),d,y.content_id);null!=E&&A.push(E)});C=1===B?UploadFileTweetFAjax(d,y.content_id,w,q):function(){var t=$.Deferred();t.resolve(1);return t.promise()};$.when.apply($,A).then(function(){var t=[];$.each($("#PasteZone").sortable("toArray"),function(H,G){t.push(parseInt(G))});for(var D=
0;D<arguments.length;D++){var F=void 0;F=1===t.length?arguments[0].append_id:arguments[D][0].append_id;0<=F&&(t[D]=F);if(1===t.length)break}return UpdatePasteOrderAjax(d,y.content_id,t)},function(t){errorMsg(-10)}).then(C,function(t){errorMsg(-11)}).then(function(t){tweetSucceeded(t)},function(t){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
function createUpdateText(){var b=!1;return function(d,f){if(!b){b=!0;var e=$("#TagInputItemData").val(),a=parseInt($("#EditCategory").val(),10),c=$.trim($("#EditDescription").val()),g=$.trim($("#EditTextBody").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var u=$("#ContentOpenId").val(),p=parseInt($("#EditPublish").val(),10),z=$("#EditPassword").val(),v=$("#OptionCheerNg").prop("checked")?0:1,x=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,w=$("#OptionDeleteTweet").prop("checked")?
1:0,q=null,l=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),m=null,r=null;if(10===p){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}q=$("#EditTwitterList").val()}if(1===l&&(m=getPublishDateTime($("#EditTimeLimitedStart").val()),r=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(m,r,!0,strPublishStartPresent,strPublishEndPresent))){b=
!1;return}$("#TagInputItemData").length||(e=1);setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99===p&&(k=0);var n=k;1===l&&(n=2===u||null!=strPublishStartPresent&&null!=strPublishEndPresent?1===k&&2!==u&&comparePublishDate(strPublishStartPresent,m)&&comparePublishDate(strPublishEndPresent,r)?1:0:0);startMsg();var B=[],A=null;UploadTextRefTwitterFAjax(d,f,e,a,c,g,h,p,z,q,v,x,l,m,r,getTweetSetting(),getTweetImageSetting(),
w).done(function(C){A=1===n?UploadFileTweetFAjax(d,C.content_id,0,w):function(){var y=$.Deferred();y.resolve(1);return y.promise()};$.when.apply($,B).then(A,function(y){errorMsg(-11)}).then(function(y){tweetSucceeded(y)},function(y){errorMsg(-12)})});return!1}}}var UpdateText=createUpdateText();
