function UpdateFileOrder(c,e){var b=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(a,d){b.push(parseInt(d))});$.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result)}})}
function UpdatePasteOrder(c,e){var b=[];$.each($("#PasteZone").sortable("toArray"),function(a,d){b.push(parseInt(d))});$.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result)},error:function(a){console.log(a)}})}function UpdatePasteOrderAjax(c,e,b){return $.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(c,e){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+c,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(b,a){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",b),this.setParams({UID:this.user_id,IID:this.illust_id},b))},onComplete:function(b,a,d,c){append_id=d.append_id;$(".qq-file-id-"+b).attr("id",append_id)},onAllComplete:function(b,a){console.log("onAllComplete",b,a,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?$.ajax({type:"post",data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");
completeMsg();setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)),UpdateFileOrder(this.user_id,this.illust_id)):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(b){var a=this.getSubmittedSize(),d=this.getSubmittedNum();this.showTotalSize(a,d);a+=b.size;if(a>this.total_size)return!1;this.showTotalSize(a,d+1)},onStatusChange:function(b,
a,d){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var b=this.getUploads({status:qq.status.SUBMITTED}),a=0;$.each(b,function(){a+=this.size});return a};multiFileUploader.showTotalSize=function(b,a){var d="(jpeg|png|gif, 200files, total 50MByte)";0<b&&(d="("+a+"/200,  "+Math.ceil((multiFileUploader.total_size-
b)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(d)};multiFileUploader.sessionRequestComplete=function(b,a,d,c){alert(a)};multiFileUploader.total_size=52428800}
function UpdateFile(c,e){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var b=$("#EditCategory").val(),a=$.trim($("#EditDescription").val());a=a.substr(0,200);var d=$.trim($("#EditTagList").val());d=d.substr(0,100);var f=$("#EditPublish").val(),k=$("#EditPassword").val(),l=$("#OptionRecent").prop("checked")?1:0,p=$("#OptionTweet").prop("checked")?1:0,r=$("#OptionImage").prop("checked")?1:0,m=null,n=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),
h=null,g=null;10==f&&(m=$("#EditTwitterList").val());if(1==n&&(h=getPublishDateTime($("#EditTimeLimitedStart").val()),g=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(h,g,!0,strPublishStartPresent,strPublishEndPresent)))return;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);
99==f&&(p=0);var q=p;1==n&&(q=0);startMsg();$.ajaxSingle({type:"post",data:{IID:e,UID:c,CAT:b,DES:a,TAG:d,PID:f,PPW:k,PLD:m,LTP:n,REC:l,PST:h,PED:g,TWT:getTweetSetting(),TWI:getTweetImageSetting(),ED:0},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(a){console.log("UpdateFileRefTwitterF:"+a.content_id);a&&0<a.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=c,multiFileUploader.illust_id=e,multiFileUploader.tweet=q,multiFileUploader.tweet_image=r,multiFileUploader.newfile_num=
multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):(UpdateFileOrder(c,e),location.href="/MyIllustListV.jsp"):errorMsg(a.result)}})}}
function initUpdatePaste(c,e){updateTweetButton();var b=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==b&&$("#EditCategory").val(b)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&
alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:c,TD:e},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(c,e,b){c.parent().addClass("Done");c=c.attr("src").replace("data:image/png;base64,","");return 0>=c.length?null:$.ajax({type:"post",data:{UID:e,IID:b,DATA:c},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}function UpdateFileRefTwitterFAjax(c,e,b,a,d,f,k,l,p,r,m,n,h,g){return $.ajax({type:"post",data:{UID:c,IID:e,CAT:b,DES:a,TAG:d,PID:f,PPW:k,PLD:l,LTP:r,REC:p,PST:m,PED:n,TWT:h,TWI:g,ED:1},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadFileTweetFAjax(c,e,b){return $.ajax({type:"post",data:{UID:c,IID:e,IMG:b},url:"/f/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var c=!1;return function(e,b){if(!c){c=!0;var a=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&a++});console.log(a);if(!(0>=a)){var d=$("#EditCategory").val(),f=$.trim($("#EditDescription").val());f=f.substr(0,200);var k=$.trim($("#EditTagList").val());k=k.substr(0,100);var l=$("#EditPublish").val(),p=$("#EditPassword").val(),r=$("#OptionRecent").prop("checked")?1:0,m=$("#OptionTweet").prop("checked")?1:0,n=$("#OptionImage").prop("checked")?1:0,
h=null,g=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),q=null,t=null;10==l&&(h=$("#EditTwitterList").val());if(1==g&&(q=getPublishDateTime($("#EditTimeLimitedStart").val()),t=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(q,t,!0,strPublishStartPresent,strPublishEndPresent)))return;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));
setLastCategorySetting(d);99==l&&(m=0);startMsg();var u=m;1==g&&(u=0);var v=[],w=null;UpdateFileRefTwitterFAjax(e,b,d,f,k,l,p,h,r,g,q,t,getTweetSetting(),getTweetImageSetting()).done(function(a){var b=null;$(".imgView").each(function(){b=UpdatePasteAppendFAjax($(this),e,a.content_id);null!=b&&v.push(b)});w=1==u?UploadFileTweetFAjax(e,a.content_id,n):function(){var a=$.Deferred();a.resolve();return a.promise()};$.when.apply($,v).then(function(){var b=[];$.each($("#PasteZone").sortable("toArray"),function(a,
c){b.push(parseInt(c))});for(var c=0;c<arguments.length;c++){var d=1==b.length?arguments[0].append_id:arguments[c][0].append_id;0<=d&&(b[c]=d);if(1==b.length)break}return UpdatePasteOrderAjax(e,a.content_id,b)},function(a){errorMsg(-10)}).then(w,function(a){errorMsg(-11)}).then(function(){completeMsg();setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)},function(a){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
