function UpdateFileOrder(b,d,e){var f=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(a,c){f.push(parseInt(c))});$.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(f)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result);e&&0<e.length&&(completeMsg(),setTimeout(function(){location.href=e},1E3))},error:function(a){console.log(a)}})}
function UpdatePasteOrderAjax(b,d,e){return $.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(e)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(b,d,e,f){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+f+"&ID="+e,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:b,sizeLimit:1048576*d,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,c){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",a),this.setParams({UID:this.user_id,IID:this.content_id},a))},onComplete:function(a,c,g,n){append_id=g.append_id;$(".qq-file-id-"+a).attr("id",append_id)},onAllComplete:function(a,c){console.log("onAllComplete",a,c,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListPcV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(a){var c=this.getSubmittedSize(),g=this.getSubmittedNum();this.showTotalSize(c,g);c+=a.size;if(c>this.total_size)return!1;this.showTotalSize(c,g+1)},onStatusChange:function(a,c,g){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),c=0;$.each(a,function(){c+=this.size});return c};multiFileUploader.showTotalSize=function(a,c){var g="(jpeg|png|gif, "+b+"files, total "+d+"MByte)";0<a&&(g="("+c+"/"+b+"files "+Math.ceil(a/1024/1024)+"/"+d+"MByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(g)};multiFileUploader.sessionRequestComplete=function(a,c,g,n){alert(c)};multiFileUploader.total_size=52428800}
function Tweet(b,d,e,f){$.ajax({type:"post",data:{UID:b,IID:d,IMG:e,DELTW:f},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(a){tweetSucceeded(a.result)}})}
function UpdateFile(b,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var e=$("#EditCategory").val(),f=$.trim($("#EditDescription").val()),a=$.trim($("#EditTagList").val());a=a.substr(0,100);var c=$("#ContentOpenId").val(),g=$("#EditPublish").val(),n=$("#EditPassword").val(),p=$("#OptionCheerNg").prop("checked")?0:1,y=$("#OptionRecent").prop("checked")?1:0,u=$("#OptionTweet").prop("checked")?1:0,v=$("#OptionImage").prop("checked")?1:0,k=$("#OptionDeleteTweet").prop("checked")?
1:0,w=null,q=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),l=null,m=null;if(10==g){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}w=$("#EditTwitterList").val()}if(1==q&&(l=getPublishDateTime($("#EditTimeLimitedStart").val()),m=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(l,m,!0,strPublishStartPresent,strPublishEndPresent)))return;
setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99==g&&(u=0);var r=u;1==q&&(r=2==c||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==u&&2!=c&&comparePublishDate(strPublishStartPresent,l)&&comparePublishDate(strPublishEndPresent,m)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:b,CAT:e,DES:f,TAG:a,PID:g,PPW:n,PLD:w,LTP:q,REC:y,PST:l,PED:m,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:k,
ED:0,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(h){console.log("UpdateFileRefTwitterF:"+h.content_id);h&&0<h.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=b,multiFileUploader.content_id=h.content_id,multiFileUploader.tweet=r,multiFileUploader.tweet_image=v,multiFileUploader.delete_tweet=k,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1==r?(UpdateFileOrder(b,h.content_id,null),Tweet(b,
h.content_id,v,k)):UpdateFileOrder(b,h.content_id,"/MyIllustListPcV.jsp"):errorMsg()}})}}
function initUpdatePaste(b,d){updateTweetButton();var e=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==e&&$("#EditCategory").val(e)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(f,a){10>$(".InputFile").length&&(f=createPasteElm(a.dataURL),$("#PasteZone").append(f),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(f,a){a.url&&
alert("error data : "+a.url)}).on("pasteText",function(f,a){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:b,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(f){$.each(f,function(a,c){10>$(".InputFile").length&&(a=createPasteListItem(c.thumbnailUrl,c.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(b,d,e){b.parent().addClass("Done");b=b.attr("src").replace("data:image/png;base64,","");return 0>=b.length?null:$.ajax({type:"post",data:{UID:d,IID:e,DATA:b},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}
function UpdateFileRefTwitterFAjax(b,d,e,f,a,c,g,n,p,y,u,v,k,w,q,l){return $.ajax({type:"post",data:{UID:b,IID:d,CAT:e,DES:f,TAG:a,PID:c,PPW:g,PLD:n,LTP:u,REC:y,PST:v,PED:k,TWT:w,TWI:q,DELTW:l,ED:1,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadTextRefTwitterFAjax(b,d,e,f,a,c,g,n,p,y,u,v,k,w,q,l,m){return $.ajax({type:"post",data:{UID:b,IID:d,CAT:e,DES:f,BDY:a,TAG:c,PID:g,PPW:n,PLD:p,LTP:v,REC:u,PST:k,PED:w,TWT:q,TWI:l,DELTW:m,ED:1,CNG:y},url:"/f/UpdateTextRefTwitterF.jsp",dataType:"json"})}function UploadFileTweetFAjax(b,d,e,f){return $.ajax({type:"post",data:{UID:b,IID:d,IMG:e,DELTW:f},url:"/api/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var b=!1;return function(d,e){if(!b){b=!0;var f=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&f++});if(0>=f)b=!1;else{var a=$("#EditCategory").val(),c=$.trim($("#EditDescription").val()),g=$.trim($("#EditTagList").val());g=g.substr(0,100);var n=$("#ContentOpenId").val(),p=$("#EditPublish").val(),y=$("#EditPassword").val(),u=$("#OptionCheerNg").prop("checked")?0:1,v=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,w=
$("#OptionImage").prop("checked")?1:0,q=$("#OptionDeleteTweet").prop("checked")?1:0,l=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,h=null;if(10==p){if($("#TwitterListNotFound").is(":visible")){b=!1;twitterListNotFoundMsg();return}l=$("#EditTwitterList").val()}if(1==m&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),h=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),
!checkPublishDatetime(r,h,!0,strPublishStartPresent,strPublishEndPresent))){b=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99==p&&(k=0);var z=k;1==m&&(z=2==n||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==k&&2!=n&&comparePublishDate(strPublishStartPresent,r)&&comparePublishDate(strPublishEndPresent,h)?1:0:0);startMsg();var C=[],A=null;UpdateFileRefTwitterFAjax(d,e,a,c,g,p,y,l,u,v,m,r,h,
getTweetSetting(),getTweetImageSetting(),q).done(function(B){var x=null;$(".imgView").each(function(){x=UpdatePasteAppendFAjax($(this),d,B.content_id);null!=x&&C.push(x)});A=1==z?UploadFileTweetFAjax(d,B.content_id,w,q):function(){var t=$.Deferred();t.resolve(1);return t.promise()};$.when.apply($,C).then(function(){var t=[];$.each($("#PasteZone").sortable("toArray"),function(G,F){t.push(parseInt(F))});for(var D=0;D<arguments.length;D++){var E=1==t.length?arguments[0].append_id:arguments[D][0].append_id;
0<=E&&(t[D]=E);if(1==t.length)break}return UpdatePasteOrderAjax(d,B.content_id,t)},function(t){errorMsg(-10)}).then(A,function(t){errorMsg(-11)}).then(function(t){tweetSucceeded(t)},function(t){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
function createUpdateText(){var b=!1;return function(d,e){if(!b){b=!0;var f=$("#EditCategory").val(),a=$.trim($("#EditDescription").val()),c=$.trim($("#EditTextBody").val()),g=$.trim($("#EditTagList").val());g=g.substr(0,100);var n=$("#ContentOpenId").val(),p=$("#EditPublish").val(),y=$("#EditPassword").val(),u=$("#OptionCheerNg").prop("checked")?0:1,v=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,w=$("#OptionImage").prop("checked")?1:0,q=$("#OptionDeleteTweet").prop("checked")?
1:0,l=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,h=null;if(10==p){if($("#TwitterListNotFound").is(":visible")){b=!1;twitterListNotFoundMsg();return}l=$("#EditTwitterList").val()}if(1==m&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),h=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(r,h,!0,strPublishStartPresent,
strPublishEndPresent))){b=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(f);99==p&&(k=0);var z=k;1==m&&(z=2==n||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==k&&2!=n&&comparePublishDate(strPublishStartPresent,r)&&comparePublishDate(strPublishEndPresent,h)?1:0:0);startMsg();var C=[],A=null;UploadTextRefTwitterFAjax(d,e,f,a,c,g,p,y,l,u,v,m,r,h,getTweetSetting(),getTweetImageSetting(),q).done(function(B){A=
1==z?UploadFileTweetFAjax(d,B.content_id,w,q):function(){var x=$.Deferred();x.resolve(1);return x.promise()};$.when.apply($,C).then(A,function(x){errorMsg(-11)}).then(function(x){tweetSucceeded(x)},function(x){errorMsg(-12)})});return!1}}}var UpdateText=createUpdateText();
