function UpdateFileOrder(a,d,c){var b=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(c,a){b.push(parseInt(a))});$.ajax({type:"post",data:{UID:a,IID:d,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(b){console.log("UploadFileOrderF:"+b.result);c&&0<c.length&&(completeMsg(),setTimeout(function(){location.href=c},1E3))},error:function(b){console.log(b)}})}
function UpdatePasteOrderAjax(a,d,c){return $.ajax({type:"post",data:{UID:a,IID:d,AID:JSON.stringify(c)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(a,d){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+d+"&ID="+a,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(c,b){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",c),this.setParams({UID:this.user_id,IID:this.content_id},c))},onComplete:function(c,b,a,d){append_id=a.append_id;$(".qq-file-id-"+c).attr("id",append_id)},onAllComplete:function(c,b){console.log("onAllComplete",c,b,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(c){var b=this.getSubmittedSize(),a=this.getSubmittedNum();this.showTotalSize(b,a);b+=c.size;if(b>this.total_size)return!1;this.showTotalSize(b,a+1)},onStatusChange:function(a,b,e){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var c="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(c="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.sessionRequestComplete=function(a,b,d,f){alert(b)};multiFileUploader.total_size=
52428800}function Tweet(a,d,c,b){$.ajax({type:"post",data:{UID:a,IID:d,IMG:c,DELTW:b},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){tweetSucceeded(a)}})}
function UpdateFile(a,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var c=$("#EditCategory").val(),b=$.trim($("#EditDescription").val());b=b.substr(0,200);var e=$.trim($("#EditTagList").val());e=e.substr(0,100);var f=$("#ContentOpenId").val(),g=$("#EditPublish").val(),r=$("#EditPassword").val(),p=$("#OptionRecent").prop("checked")?1:0,q=$("#OptionTweet").prop("checked")?1:0,t=$("#OptionImage").prop("checked")?1:0,h=$("#OptionDeleteTweet").prop("checked")?
1:0,u=null,l=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),k=null,m=null;if(10==g){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}u=$("#EditTwitterList").val()}if(1==l&&(k=getPublishDateTime($("#EditTimeLimitedStart").val()),m=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(k,m,!0,strPublishStartPresent,strPublishEndPresent)))return;
setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99==g&&(q=0);var n=q;1==l&&(n=2==f||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==q&&2!=f&&comparePublishDate(strPublishStartPresent,k)&&comparePublishDate(strPublishEndPresent,m)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:a,CAT:c,DES:b,TAG:e,PID:g,PPW:r,PLD:u,LTP:l,REC:p,PST:k,PED:m,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:h,
ED:0},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UpdateFileRefTwitterF:"+b.content_id);b&&0<b.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=a,multiFileUploader.content_id=b.content_id,multiFileUploader.tweet=n,multiFileUploader.tweet_image=t,multiFileUploader.delete_tweet=h,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1==n?(UpdateFileOrder(a,b.content_id,null),Tweet(a,
b.content_id,t,h)):UpdateFileOrder(a,b.content_id,"/MyIllustListV.jsp"):errorMsg(b.result)}})}}
function initUpdatePaste(a,d){updateTweetButton();var c=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==c&&$("#EditCategory").val(c)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(b,a){10>$(".InputFile").length&&(b=createPasteElm(a.dataURL),$("#PasteZone").append(b),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(b,a){a.url&&
alert("error data : "+a.url)}).on("pasteText",function(a,c){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:a,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(a,d,c){a.parent().addClass("Done");a=a.attr("src").replace("data:image/png;base64,","");return 0>=a.length?null:$.ajax({type:"post",data:{UID:d,IID:c,DATA:a},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}function UpdateFileRefTwitterFAjax(a,d,c,b,e,f,g,r,p,q,t,h,u,l,k){return $.ajax({type:"post",data:{UID:a,IID:d,CAT:c,DES:b,TAG:e,PID:f,PPW:g,PLD:r,LTP:q,REC:p,PST:t,PED:h,TWT:u,TWI:l,DELTW:k,ED:1},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadFileTweetFAjax(a,d,c,b){return $.ajax({type:"post",data:{UID:a,IID:d,IMG:c,DELTW:b},url:"/f/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var a=!1;return function(d,c){if(!a){a=!0;var b=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&b++});if(0>=b)a=!1;else{var e=$("#EditCategory").val(),f=$.trim($("#EditDescription").val());f=f.substr(0,200);var g=$.trim($("#EditTagList").val());g=g.substr(0,100);var r=$("#ContentOpenId").val(),p=$("#EditPublish").val(),q=$("#EditPassword").val(),t=$("#OptionRecent").prop("checked")?1:0,h=$("#OptionTweet").prop("checked")?1:0,u=$("#OptionImage").prop("checked")?
1:0,l=$("#OptionDeleteTweet").prop("checked")?1:0,k=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),n=null,v=null;if(10==p){if($("#TwitterListNotFound").is(":visible")){a=!1;twitterListNotFoundMsg();return}k=$("#EditTwitterList").val()}if(1==m&&(n=getPublishDateTime($("#EditTimeLimitedStart").val()),v=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(n,
v,!0,strPublishStartPresent,strPublishEndPresent))){a=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99==p&&(h=0);var w=h;1==m&&(w=2==r||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==h&&2!=r&&comparePublishDate(strPublishStartPresent,n)&&comparePublishDate(strPublishEndPresent,v)?1:0:0);startMsg();var x=[],y=null;UpdateFileRefTwitterFAjax(d,c,e,f,g,p,q,k,t,m,n,v,getTweetSetting(),getTweetImageSetting(),
l).done(function(a){var b=null;$(".imgView").each(function(){b=UpdatePasteAppendFAjax($(this),d,a.content_id);null!=b&&x.push(b)});y=1==w?UploadFileTweetFAjax(d,a.content_id,u,l):function(){var a=$.Deferred();a.resolve(1);return a.promise()};$.when.apply($,x).then(function(){var b=[];$.each($("#PasteZone").sortable("toArray"),function(a,c){b.push(parseInt(c))});for(var c=0;c<arguments.length;c++){var e=1==b.length?arguments[0].append_id:arguments[c][0].append_id;0<=e&&(b[c]=e);if(1==b.length)break}return UpdatePasteOrderAjax(d,
a.content_id,b)},function(a){errorMsg(-10)}).then(y,function(a){errorMsg(-11)}).then(function(a){tweetSucceeded(a)},function(a){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
