function UpdateFileOrder(b,d,f){var e=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(a,c){e.push(parseInt(c))});$.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(e)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result);f&&0<f.length&&(completeMsg(),setTimeout(function(){location.href=f},1E3))},error:function(a){console.log(a)}})}
function UpdatePasteOrderAjax(b,d,f){return $.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(f)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(b,d,f,e){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+f,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:b,sizeLimit:1048576*d,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,c){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",a),this.setParams({UID:this.user_id,IID:this.content_id},a))},onComplete:function(a,c,g,h){append_id=g.append_id;$(".qq-file-id-"+a).attr("id",append_id)},onAllComplete:function(a,c){console.log("onAllComplete",a,c,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListPcV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(a){var c=this.getSubmittedSize(),g=this.getSubmittedNum();this.showTotalSize(c,g);c+=a.size;if(c>this.total_size)return!1;this.showTotalSize(c,g+1)},onStatusChange:function(a,c,g){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),c=0;$.each(a,function(){c+=this.size});return c};multiFileUploader.showTotalSize=function(a,c){var g="(jpeg|png|gif, "+b+"files, total "+d+"MByte)";0<a&&(g="("+c+"/"+b+"files "+Math.ceil(a/1024/1024)+"/"+d+"MByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(g)};multiFileUploader.sessionRequestComplete=function(a,c,g,h){alert(c)};multiFileUploader.total_size=52428800}
function Tweet(b,d,f,e){$.ajax({type:"post",data:{UID:b,IID:d,IMG:f,DELTW:e},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(a){tweetSucceeded(a.result)}})}
function UpdateFile(b,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)&&$("#TagInputItemData").length){var f=$("#TagInputItemData").val(),e=$("#EditCategory").val(),a=$.trim($("#EditDescription").val()),c=$.trim($("#EditTagList").val());c=c.substr(0,100);var g=$("#ContentOpenId").val(),h=$("#EditPublish").val(),u=$("#EditPassword").val(),p=$("#OptionCheerNg").prop("checked")?0:1,z=$("#OptionRecent").prop("checked")?1:0,v=$("#OptionTweet").prop("checked")?
1:0,w=$("#OptionImage").prop("checked")?1:0,l=$("#OptionDeleteTweet").prop("checked")?1:0,x=null,q=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),m=null,n=null;if(10==h){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}x=$("#EditTwitterList").val()}if(1==q&&(m=getPublishDateTime($("#EditTimeLimitedStart").val()),n=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),
!checkPublishDatetime(m,n,!0,strPublishStartPresent,strPublishEndPresent)))return;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99==h&&(v=0);var r=v;1==q&&(r=2==g||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==v&&2!=g&&comparePublishDate(strPublishStartPresent,m)&&comparePublishDate(strPublishEndPresent,n)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:b,GD:f,CAT:e,DES:a,TAG:c,PID:h,PPW:u,
PLD:x,LTP:q,REC:z,PST:m,PED:n,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:l,ED:0,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(k){console.log("UpdateFileRefTwitterF:"+k.content_id);k&&0<k.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=b,multiFileUploader.content_id=k.content_id,multiFileUploader.tweet=r,multiFileUploader.tweet_image=w,multiFileUploader.delete_tweet=l,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),
multiFileUploader.uploadStoredFiles()):1==r?(UpdateFileOrder(b,k.content_id,null),Tweet(b,k.content_id,w,l)):UpdateFileOrder(b,k.content_id,"/MyIllustListPcV.jsp"):errorMsg()}})}}
function initUpdatePaste(b,d){updateTweetButton();var f=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==f&&$("#EditCategory").val(f)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(e,a){10>$(".InputFile").length&&(e=createPasteElm(a.dataURL),$("#PasteZone").append(e),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(e,a){a.url&&
alert("error data : "+a.url)}).on("pasteText",function(e,a){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:b,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(e){$.each(e,function(a,c){10>$(".InputFile").length&&(a=createPasteListItem(c.thumbnailUrl,c.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(b,d,f){b.parent().addClass("Done");b=b.attr("src").replace("data:image/png;base64,","");return 0>=b.length?null:$.ajax({type:"post",data:{UID:d,IID:f,DATA:b},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}
function UpdateFileRefTwitterFAjax(b,d,f,e,a,c,g,h,u,p,z,v,w,l,x,q,m){return $.ajax({type:"post",data:{UID:b,IID:d,GD:f,CAT:e,DES:a,TAG:c,PID:g,PPW:h,PLD:u,LTP:v,REC:z,PST:w,PED:l,TWT:x,TWI:q,DELTW:m,ED:1,CNG:p},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadTextRefTwitterFAjax(b,d,f,e,a,c,g,h,u,p,z,v,w,l,x,q,m,n){return $.ajax({type:"post",data:{UID:b,IID:d,GD:f,CAT:e,DES:a,BDY:c,TAG:g,PID:h,PPW:u,PLD:p,LTP:w,REC:v,PST:l,PED:x,TWT:q,TWI:m,DELTW:n,ED:1,CNG:z},url:"/f/UpdateTextRefTwitterF.jsp",dataType:"json"})}function UploadFileTweetFAjax(b,d,f,e){return $.ajax({type:"post",data:{UID:b,IID:d,IMG:f,DELTW:e},url:"/api/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var b=!1;return function(d,f){if(!b){b=!0;var e=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&e++});if(0>=e)b=!1;else if($("#TagInputItemData").length){var a=$("#TagInputItemData").val(),c=$("#EditCategory").val(),g=$.trim($("#EditDescription").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var u=$("#ContentOpenId").val(),p=$("#EditPublish").val(),z=$("#EditPassword").val(),v=$("#OptionCheerNg").prop("checked")?0:1,w=$("#OptionRecent").prop("checked")?
1:0,l=$("#OptionTweet").prop("checked")?1:0,x=$("#OptionImage").prop("checked")?1:0,q=$("#OptionDeleteTweet").prop("checked")?1:0,m=null,n=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,k=null;if(10==p){if($("#TwitterListNotFound").is(":visible")){b=!1;twitterListNotFoundMsg();return}m=$("#EditTwitterList").val()}if(1==n&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),k=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),
strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(r,k,!0,strPublishStartPresent,strPublishEndPresent))){b=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99==p&&(l=0);var A=l;1==n&&(A=2==u||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==l&&2!=u&&comparePublishDate(strPublishStartPresent,r)&&comparePublishDate(strPublishEndPresent,k)?1:0:0);startMsg();var D=[],
B=null;UpdateFileRefTwitterFAjax(d,f,a,c,g,h,p,z,m,v,w,n,r,k,getTweetSetting(),getTweetImageSetting(),q).done(function(C){var y=null;$(".imgView").each(function(){y=UpdatePasteAppendFAjax($(this),d,C.content_id);null!=y&&D.push(y)});B=1==A?UploadFileTweetFAjax(d,C.content_id,x,q):function(){var t=$.Deferred();t.resolve(1);return t.promise()};$.when.apply($,D).then(function(){var t=[];$.each($("#PasteZone").sortable("toArray"),function(H,G){t.push(parseInt(G))});for(var E=0;E<arguments.length;E++){var F=
1==t.length?arguments[0].append_id:arguments[E][0].append_id;0<=F&&(t[E]=F);if(1==t.length)break}return UpdatePasteOrderAjax(d,C.content_id,t)},function(t){errorMsg(-10)}).then(B,function(t){errorMsg(-11)}).then(function(t){tweetSucceeded(t)},function(t){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
function createUpdateText(){var b=!1;return function(d,f){if(!b&&(b=!0,$("#TagInputItemData").length)){var e=$("#TagInputItemData").val(),a=$("#EditCategory").val(),c=$.trim($("#EditDescription").val()),g=$.trim($("#EditTextBody").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var u=$("#ContentOpenId").val(),p=$("#EditPublish").val(),z=$("#EditPassword").val(),v=$("#OptionCheerNg").prop("checked")?0:1,w=$("#OptionRecent").prop("checked")?1:0,l=$("#OptionTweet").prop("checked")?1:0,x=$("#OptionImage").prop("checked")?
1:0,q=$("#OptionDeleteTweet").prop("checked")?1:0,m=null,n=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,k=null;if(10==p){if($("#TwitterListNotFound").is(":visible")){b=!1;twitterListNotFoundMsg();return}m=$("#EditTwitterList").val()}if(1==n&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),k=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(r,
k,!0,strPublishStartPresent,strPublishEndPresent))){b=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99==p&&(l=0);var A=l;1==n&&(A=2==u||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==l&&2!=u&&comparePublishDate(strPublishStartPresent,r)&&comparePublishDate(strPublishEndPresent,k)?1:0:0);startMsg();var D=[],B=null;UploadTextRefTwitterFAjax(d,f,e,a,c,g,h,p,z,m,v,w,n,r,k,getTweetSetting(),getTweetImageSetting(),
q).done(function(C){B=1==A?UploadFileTweetFAjax(d,C.content_id,x,q):function(){var y=$.Deferred();y.resolve(1);return y.promise()};$.when.apply($,D).then(B,function(y){errorMsg(-11)}).then(function(y){tweetSucceeded(y)},function(y){errorMsg(-12)})});return!1}}}var UpdateText=createUpdateText();
