function UpdateFileOrder(b,d,c){var a=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(c,b){a.push(parseInt(b))});$.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(a)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result);c&&0<c.length&&(completeMsg(),setTimeout(function(){location.href=c},1E3))},error:function(a){console.log(a)}})}
function UpdatePasteOrderAjax(b,d,c){return $.ajax({type:"post",data:{UID:b,IID:d,AID:JSON.stringify(c)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(b,d){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+d+"&ID="+b,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(c,a){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",c),this.setParams({UID:this.user_id,IID:this.content_id},c))},onComplete:function(c,a,b,d){append_id=b.append_id;$(".qq-file-id-"+c).attr("id",append_id)},onAllComplete:function(c,a){console.log("onAllComplete",c,a,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(c){var a=this.getSubmittedSize(),b=this.getSubmittedNum();this.showTotalSize(a,b);a+=c.size;if(a>this.total_size)return!1;this.showTotalSize(a,b+1)},onStatusChange:function(c,a,b){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var c=this.getUploads({status:qq.status.SUBMITTED}),a=0;$.each(c,function(){a+=this.size});return a};multiFileUploader.showTotalSize=function(c,a){var b="(jpeg|png|gif, 200files, total 50MByte)";0<c&&(b="("+a+"/200,  "+Math.ceil((multiFileUploader.total_size-c)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(b)};multiFileUploader.sessionRequestComplete=function(b,a,d,e){alert(a)};multiFileUploader.total_size=
52428800}function Tweet(b,d,c,a){$.ajax({type:"post",data:{UID:b,IID:d,IMG:c,DELTW:a},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)}})}
function UpdateFile(b,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var c=$("#EditCategory").val(),a=$.trim($("#EditDescription").val());a=a.substr(0,200);var g=$.trim($("#EditTagList").val());g=g.substr(0,100);var e=$("#EditPublish").val(),m=$("#EditPassword").val(),n=$("#OptionRecent").prop("checked")?1:0,q=$("#OptionTweet").prop("checked")?1:0,r=$("#OptionImage").prop("checked")?1:0,h=$("#OptionDeleteTweet").prop("checked")?1:0,t=null,k=getLimitedTimeFlg("EditPublish",
"OptionLimitedTimePublish"),l=null,f=null;10==e&&(t=$("#EditTwitterList").val());if(1==k&&(l=getPublishDateTime($("#EditTimeLimitedStart").val()),f=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(l,f,!0,strPublishStartPresent,strPublishEndPresent)))return;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));
setLastCategorySetting(c);99==e&&(q=0);var p=q;1==k&&(p=0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:b,CAT:c,DES:a,TAG:g,PID:e,PPW:m,PLD:t,LTP:k,REC:n,PST:l,PED:f,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:h,ED:0},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(a){console.log("UpdateFileRefTwitterF:"+a.content_id);a&&0<a.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=b,multiFileUploader.content_id=d,multiFileUploader.tweet=p,
multiFileUploader.tweet_image=r,multiFileUploader.delete_tweet=h,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1==p?(UpdateFileOrder(b,d,null),Tweet(b,d,r,h)):UpdateFileOrder(b,d,"/MyIllustListV.jsp"):errorMsg(a.result)}})}}
function initUpdatePaste(b,d){updateTweetButton();var c=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==c&&$("#EditCategory").val(c)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&
alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:b,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(b,d,c){b.parent().addClass("Done");b=b.attr("src").replace("data:image/png;base64,","");return 0>=b.length?null:$.ajax({type:"post",data:{UID:d,IID:c,DATA:b},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}function UpdateFileRefTwitterFAjax(b,d,c,a,g,e,m,n,q,r,h,t,k,l,f){return $.ajax({type:"post",data:{UID:b,IID:d,CAT:c,DES:a,TAG:g,PID:e,PPW:m,PLD:n,LTP:r,REC:q,PST:h,PED:t,TWT:k,TWI:l,DELTW:f,ED:1},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadFileTweetFAjax(b,d,c,a){return $.ajax({type:"post",data:{UID:b,IID:d,IMG:c,DELTW:a},url:"/f/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var b=!1;return function(d,c){if(!b){b=!0;var a=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&a++});console.log(a);if(!(0>=a)){var g=$("#EditCategory").val(),e=$.trim($("#EditDescription").val());e=e.substr(0,200);var m=$.trim($("#EditTagList").val());m=m.substr(0,100);var n=$("#EditPublish").val(),q=$("#EditPassword").val(),r=$("#OptionRecent").prop("checked")?1:0,h=$("#OptionTweet").prop("checked")?1:0,t=$("#OptionImage").prop("checked")?1:0,
k=$("#OptionDeleteTweet").prop("checked")?1:0,l=null,f=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),p=null,u=null;10==n&&(l=$("#EditTwitterList").val());if(1==f&&(p=getPublishDateTime($("#EditTimeLimitedStart").val()),u=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(p,u,!0,strPublishStartPresent,strPublishEndPresent)))return;setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(g);99==n&&(h=0);startMsg();var v=h;1==f&&(v=0);var w=[],x=null;UpdateFileRefTwitterFAjax(d,c,g,e,m,n,q,l,r,f,p,u,getTweetSetting(),getTweetImageSetting(),k).done(function(a){var b=null;$(".imgView").each(function(){b=UpdatePasteAppendFAjax($(this),d,a.content_id);null!=b&&w.push(b)});x=1==v?UploadFileTweetFAjax(d,a.content_id,t,k):function(){var a=$.Deferred();a.resolve();return a.promise()};$.when.apply($,w).then(function(){var b=
[];$.each($("#PasteZone").sortable("toArray"),function(a,c){b.push(parseInt(c))});for(var c=0;c<arguments.length;c++){var e=1==b.length?arguments[0].append_id:arguments[c][0].append_id;0<=e&&(b[c]=e);if(1==b.length)break}return UpdatePasteOrderAjax(d,a.content_id,b)},function(a){errorMsg(-10)}).then(x,function(a){errorMsg(-11)}).then(function(){completeMsg();setTimeout(function(){location.href="/MyIllustListV.jsp"},1E3)},function(a){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
