function UpdateFileOrder(c,e,b){var a=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(d,g){a.push(parseInt(g))});$.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(a)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(d){console.log("UploadFileOrderF:"+d.result);b&&0<b.length&&(completeMsg(),setTimeout(function(){location.href=b},1E3))},error:function(d){console.log(d)}})}
function UpdatePasteOrderAjax(c,e,b){return $.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(c,e){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+c,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(b,a){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",b),this.setParams({UID:this.user_id,IID:this.content_id},b))},onComplete:function(b,a,d,g){append_id=d.append_id;$(".qq-file-id-"+b).attr("id",append_id)},onAllComplete:function(b,a){console.log("onAllComplete",b,a,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListPcV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(b){var a=this.getSubmittedSize(),d=this.getSubmittedNum();this.showTotalSize(a,d);a+=b.size;if(a>this.total_size)return!1;this.showTotalSize(a,d+1)},onStatusChange:function(b,a,d){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var b=this.getUploads({status:qq.status.SUBMITTED}),a=0;$.each(b,function(){a+=this.size});return a};multiFileUploader.showTotalSize=function(b,a){var d="(jpeg|png|gif, 200files, total 50MByte)";0<b&&(d="("+a+"/200,  "+Math.ceil((multiFileUploader.total_size-b)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(d)};multiFileUploader.sessionRequestComplete=function(b,a,d,g){alert(a)};multiFileUploader.total_size=
52428800}function Tweet(c,e,b,a){$.ajax({type:"post",data:{UID:c,IID:e,IMG:b,DELTW:a},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(d){tweetSucceeded(d.result)}})}
function UpdateFile(c,e){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var b=$("#EditCategory").val(),a=$.trim($("#EditDescription").val()),d=$.trim($("#EditTagList").val());d=d.substr(0,100);var g=$("#ContentOpenId").val(),h=$("#EditPublish").val(),t=$("#EditPassword").val(),n=$("#OptionCheerNg").prop("checked")?0:1,y=$("#OptionRecent").prop("checked")?1:0,u=$("#OptionTweet").prop("checked")?1:0,v=$("#OptionImage").prop("checked")?1:0,k=$("#OptionDeleteTweet").prop("checked")?
1:0,w=null,p=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),l=null,m=null;if(10==h){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}w=$("#EditTwitterList").val()}if(1==p&&(l=getPublishDateTime($("#EditTimeLimitedStart").val()),m=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(l,m,!0,strPublishStartPresent,strPublishEndPresent)))return;
setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);99==h&&(u=0);var q=u;1==p&&(q=2==g||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==u&&2!=g&&comparePublishDate(strPublishStartPresent,l)&&comparePublishDate(strPublishEndPresent,m)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:e,UID:c,CAT:b,DES:a,TAG:d,PID:h,PPW:t,PLD:w,LTP:p,REC:y,PST:l,PED:m,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:k,
ED:0,CNG:n},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(f){console.log("UpdateFileRefTwitterF:"+f.content_id);f&&0<f.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=c,multiFileUploader.content_id=f.content_id,multiFileUploader.tweet=q,multiFileUploader.tweet_image=v,multiFileUploader.delete_tweet=k,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1==q?(UpdateFileOrder(c,f.content_id,null),Tweet(c,
f.content_id,v,k)):UpdateFileOrder(c,f.content_id,"/MyIllustListPcV.jsp"):errorMsg(f.result)}})}}
function initUpdatePaste(c,e){updateTweetButton();var b=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==b&&$("#EditCategory").val(b)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,d){10>$(".InputFile").length&&(a=createPasteElm(d.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,d){d.url&&
alert("error data : "+d.url)}).on("pasteText",function(a,d){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:c,TD:e},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(d,g){10>$(".InputFile").length&&(d=createPasteListItem(g.thumbnailUrl,g.append_id),$("#PasteZone").append(d),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(c,e,b){c.parent().addClass("Done");c=c.attr("src").replace("data:image/png;base64,","");return 0>=c.length?null:$.ajax({type:"post",data:{UID:e,IID:b,DATA:c},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}
function UpdateFileRefTwitterFAjax(c,e,b,a,d,g,h,t,n,y,u,v,k,w,p,l){return $.ajax({type:"post",data:{UID:c,IID:e,CAT:b,DES:a,TAG:d,PID:g,PPW:h,PLD:t,LTP:u,REC:y,PST:v,PED:k,TWT:w,TWI:p,DELTW:l,ED:1,CNG:n},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadTextRefTwitterFAjax(c,e,b,a,d,g,h,t,n,y,u,v,k,w,p,l,m){return $.ajax({type:"post",data:{UID:c,IID:e,CAT:b,DES:a,BDY:d,TAG:g,PID:h,PPW:t,PLD:n,LTP:v,REC:u,PST:k,PED:w,TWT:p,TWI:l,DELTW:m,ED:1,CNG:y},url:"/f/UpdateTextRefTwitterF.jsp",dataType:"json"})}function UploadFileTweetFAjax(c,e,b,a){return $.ajax({type:"post",data:{UID:c,IID:e,IMG:b,DELTW:a},url:"/api/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var c=!1;return function(e,b){if(!c){c=!0;var a=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&a++});if(0>=a)c=!1;else{var d=$("#EditCategory").val(),g=$.trim($("#EditDescription").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var t=$("#ContentOpenId").val(),n=$("#EditPublish").val(),y=$("#EditPassword").val(),u=$("#OptionCheerNg").prop("checked")?0:1,v=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,w=
$("#OptionImage").prop("checked")?1:0,p=$("#OptionDeleteTweet").prop("checked")?1:0,l=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),q=null,f=null;if(10==n){if($("#TwitterListNotFound").is(":visible")){c=!1;twitterListNotFoundMsg();return}l=$("#EditTwitterList").val()}if(1==m&&(q=getPublishDateTime($("#EditTimeLimitedStart").val()),f=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),
!checkPublishDatetime(q,f,!0,strPublishStartPresent,strPublishEndPresent))){c=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(d);99==n&&(k=0);var z=k;1==m&&(z=2==t||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==k&&2!=t&&comparePublishDate(strPublishStartPresent,q)&&comparePublishDate(strPublishEndPresent,f)?1:0:0);startMsg();var C=[],A=null;UpdateFileRefTwitterFAjax(e,b,d,g,h,n,y,l,u,v,m,q,f,
getTweetSetting(),getTweetImageSetting(),p).done(function(B){var x=null;$(".imgView").each(function(){x=UpdatePasteAppendFAjax($(this),e,B.content_id);null!=x&&C.push(x)});A=1==z?UploadFileTweetFAjax(e,B.content_id,w,p):function(){var r=$.Deferred();r.resolve(1);return r.promise()};$.when.apply($,C).then(function(){var r=[];$.each($("#PasteZone").sortable("toArray"),function(G,F){r.push(parseInt(F))});for(var D=0;D<arguments.length;D++){var E=1==r.length?arguments[0].append_id:arguments[D][0].append_id;
0<=E&&(r[D]=E);if(1==r.length)break}return UpdatePasteOrderAjax(e,B.content_id,r)},function(r){errorMsg(-10)}).then(A,function(r){errorMsg(-11)}).then(function(r){tweetSucceeded(r)},function(r){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
function createUpdateText(){var c=!1;return function(e,b){if(!c){c=!0;var a=$("#EditCategory").val(),d=$.trim($("#EditDescription").val()),g=$.trim($("#EditTextBody").val()),h=$.trim($("#EditTagList").val());h=h.substr(0,100);var t=$("#ContentOpenId").val(),n=$("#EditPublish").val(),y=$("#EditPassword").val(),u=$("#OptionCheerNg").prop("checked")?0:1,v=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,w=$("#OptionImage").prop("checked")?1:0,p=$("#OptionDeleteTweet").prop("checked")?
1:0,l=null,m=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),q=null,f=null;if(10==n){if($("#TwitterListNotFound").is(":visible")){c=!1;twitterListNotFoundMsg();return}l=$("#EditTwitterList").val()}if(1==m&&(q=getPublishDateTime($("#EditTimeLimitedStart").val()),f=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(q,f,!0,strPublishStartPresent,
strPublishEndPresent))){c=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99==n&&(k=0);var z=k;1==m&&(z=2==t||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==k&&2!=t&&comparePublishDate(strPublishStartPresent,q)&&comparePublishDate(strPublishEndPresent,f)?1:0:0);startMsg();var C=[],A=null;UploadTextRefTwitterFAjax(e,b,a,d,g,h,n,y,l,u,v,m,q,f,getTweetSetting(),getTweetImageSetting(),p).done(function(B){A=
1==z?UploadFileTweetFAjax(e,B.content_id,w,p):function(){var x=$.Deferred();x.resolve(1);return x.promise()};$.when.apply($,C).then(A,function(x){errorMsg(-11)}).then(function(x){tweetSucceeded(x)},function(x){errorMsg(-12)})});return!1}}}var UpdateText=createUpdateText();
