function UpdateFileOrder(c,e){var a=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(b,d){a.push(parseInt(d))});$.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(a)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(b){console.log("UploadFileOrderF:"+b.result)}})}
function UpdatePasteOrder(c,e){var a=[];$.each($("#PasteZone").sortable("toArray"),function(b,d){a.push(parseInt(d))});$.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(a)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(b){console.log("UploadFileOrderF:"+b.result)},error:function(b){console.log(b);console.log("hoge")}})}function UpdatePasteOrderAjax(c,e,a){return $.ajax({type:"post",data:{UID:c,IID:e,AID:JSON.stringify(a)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(c,e){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+c,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},
retry:{enableAuto:!1},callbacks:{onUpload:function(a,b){this.newfile_num&&0<this.newfile_num&&(this.setEndpoint("/f/UpdateFileAppendF.jsp",a),this.setParams({UID:this.user_id,IID:this.illust_id},a))},onComplete:function(a,b,d,c){append_id=d.append_id;$(".qq-file-id-"+a).attr("id",append_id)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?$.ajax({type:"post",data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},
url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(b){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)),UpdateFileOrder(this.user_id,this.illust_id)):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(a){var b=this.getSubmittedSize(),d=this.getSubmittedNum();this.showTotalSize(b,
d);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,d+1)},onStatusChange:function(a,b,d){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,
b){var d="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(d="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(d)};multiFileUploader.sessionRequestComplete=function(a,b,d,c){alert(b)};multiFileUploader.total_size=52428800}
function UpdateFile(c,e){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var a=$("#EditCategory").val(),b=$.trim($("#EditDescription").val());b=b.substr(0,200);var d=$.trim($("#EditTagList").val());d=d.substr(0,100);var f=$("#EditPublish").val(),g=$("#EditPassword").val(),h=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,l=$("#OptionImage").prop("checked")?1:0,m=null;10==f&&(m=$("#EditTwitterList").val());setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99==f&&(h=2,k=0);startMsg();$.ajaxSingle({type:"post",data:{UID:c,IID:e,CAT:a,DES:b,TAG:d,PID:f,PPW:g,PLD:m,REC:h,ED:0},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UpdateFileRefTwitterF:"+b.content_id);b&&0<b.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=c,multiFileUploader.illust_id=e,multiFileUploader.recent=h,multiFileUploader.first_file=!0,multiFileUploader.tweet=
k,multiFileUploader.tweet_image=l,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):(UpdateFileOrder(c,e),location.href="/MyHomePcV.jsp"):errorMsg()}})}}
function initUpdatePaste(c,e){console.log("initUpdatePaste");$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(b,a){10>$(".InputFile").length&&
(b=createPasteElm(a.dataURL),$("#PasteZone").append(b),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(b,a){a.url&&alert("error data : "+a.url)}).on("pasteText",function(b,a){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:c,TD:e},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));
updatePasteNum()})}})}function UpdatePasteAppendFAjax(c,e,a){c.parent().addClass("Done");c=c.attr("src").replace("data:image/png;base64,","");return 0>=c.length?null:$.ajax({type:"post",data:{UID:e,IID:a,DATA:c},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}function UpdateFileRefTwitterFAjax(c,e,a,b,d,f,g,h,k){return $.ajax({type:"post",data:{UID:c,IID:e,CAT:a,DES:b,TAG:d,PID:f,PPW:g,PLD:h,REC:k,ED:1},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadFileTweetFAjax(c,e,a){return $.ajax({type:"post",data:{UID:c,IID:e,IMG:a},url:"/f/UploadFileTweetF.jsp",dataType:"json"})}
function UpdatePaste(c,e){var a=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&a++});console.log(a);if(!(0>=a)){var b=$("#EditCategory").val(),d=$.trim($("#EditDescription").val());d=d.substr(0,200);var f=$.trim($("#EditTagList").val());f=f.substr(0,100);var g=$("#EditPublish").val(),h=$("#EditPassword").val(),k=$("#OptionRecent").prop("checked")?1:0,l=$("#OptionTweet").prop("checked")?1:0,m=$("#OptionImage").prop("checked")?1:0,n=null;10==g&&(n=$("#EditTwitterList").val());
setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);99==g&&(k=2,l=0);startMsg();var p=[],q=null;UpdateFileRefTwitterFAjax(c,e,b,d,f,g,h,n,k).done(function(a){var b=null;$(".imgView").each(function(){b=UpdatePasteAppendFAjax($(this),c,a.content_id);null!=b&&p.push(b)});q=1==l?UploadFileTweetFAjax(c,a.content_id,m):function(){var a=$.Deferred();a.resolve();return a.promise()};$.when.apply(null,p).done(function(){var b=
[];$.each($("#PasteZone").sortable("toArray"),function(a,c){b.push(parseInt(c))});for(var d=0;d<arguments.length;d++){var e=1==b.length?arguments[0].append_id:arguments[d][0].append_id;0<=e&&(b[d]=e);if(1==b.length)break}console.log("append_ids"+b);return UpdatePasteOrderAjax(c,a.content_id,b)}).done(q).done(function(){completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)})});return!1}};
