function UpdateFileOrder(d,e){var b=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(a,c){b.push(parseInt(c))});$.ajax({type:"post",data:{UID:d,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result)}})}
function UpdatePasteOrder(d,e){var b=[];$.each($("#PasteZone").sortable("toArray"),function(a,c){b.push(parseInt(c))});$.ajax({type:"post",data:{UID:d,IID:e,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(a){console.log("UploadFileOrderF:"+a.result)}})}
function initUpdateFile(d,e){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+e+"&ID="+d,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},
retry:{enableAuto:!1},callbacks:{onUpload:function(b,a){this.newfile_num&&0<this.newfile_num&&(this.setEndpoint("/f/UpdateFileAppendF.jsp",b),this.setParams({UID:this.user_id,IID:this.illust_id},b))},onComplete:function(b,a,c,d){append_id=c.append_id;$(".qq-file-id-"+b).attr("id",append_id)},onAllComplete:function(b,a){console.log("onAllComplete",b,a,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?$.ajax({type:"post",data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},
url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)),UpdateFileOrder(this.user_id,this.illust_id)):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(b){var a=this.getSubmittedSize(),c=this.getSubmittedNum();this.showTotalSize(a,
c);a+=b.size;if(a>this.total_size)return!1;this.showTotalSize(a,c+1)},onStatusChange:function(b,a,c){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var b=this.getUploads({status:qq.status.SUBMITTED}),a=0;$.each(b,function(){a+=this.size});return a};multiFileUploader.showTotalSize=function(b,
a){var c="(jpeg|png|gif, 200files, total 50MByte)";0<b&&(c="("+a+"/200,  "+Math.ceil((multiFileUploader.total_size-b)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.sessionRequestComplete=function(b,a,c,d){alert(a)};multiFileUploader.total_size=52428800}
function UpdateFile(d,e){if(multiFileUploader){var b=$("#EditCategory").val(),a=$.trim($("#EditDescription").val());a=a.substr(0,200);var c=$.trim($("#EditTagList").val());c=c.substr(0,100);var f=$("#EditPublish").val(),g=$("#EditPassword").val(),h=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,l=$("#OptionImage").prop("checked")?1:0,m=null;10==f&&(m=$("#EditTwitterList").val());setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));
setLastCategorySetting(b);99==f&&(h=2,k=0);startMsg();$.ajaxSingle({type:"post",data:{UID:d,IID:e,CAT:b,DES:a,TAG:c,PID:f,PPW:g,PLD:m,REC:h,ED:0},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(a){console.log("UpdateFileRefTwitterF:"+a.content_id);a&&0<a.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=d,multiFileUploader.illust_id=e,multiFileUploader.recent=h,multiFileUploader.first_file=!0,multiFileUploader.tweet=k,multiFileUploader.tweet_image=l,multiFileUploader.newfile_num=
multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):(UpdateFileOrder(d,e),location.href="/MyHomePcV.jsp"):errorMsg()}})}}
function initUpdatePaste(d,e){console.log("initUpdatePaste");$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var b=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==b&&$("#EditCategory").val(b)});updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&
(a=createPasteElm(b.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:d,TD:e},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));
updatePasteNum()})}})}
function UpdatePaste(d,e){var b=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&b++});console.log(b);if(!(0>=b)){var a=$("#EditCategory").val(),c=$.trim($("#EditDescription").val());c=c.substr(0,200);var f=$.trim($("#EditTagList").val());f=f.substr(0,100);var g=$("#EditPublish").val(),h=$("#EditPassword").val(),k=$("#OptionRecent").prop("checked")?1:0,l=$("#OptionTweet").prop("checked")?1:0,m=$("#OptionImage").prop("checked")?1:0,n=null;10==g&&(n=$("#EditTwitterList").val());setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(a);99==g&&(k=2,l=0);startMsg();$.ajaxSingle({type:"post",data:{UID:d,IID:e,CAT:a,DES:c,TAG:f,PID:g,PPW:h,PLD:n,REC:k,ED:1},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(a){console.log("UpdateFileRefTwitterF",a.content_id);$(".imgView").each(function(){$(this).parent().addClass("Done");var b=$(this).attr("src").replace("data:image/png;base64,","");if(0>=b.length)return!0;$.ajax({type:"post",data:{UID:d,
IID:a.content_id,DATA:b},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteAppendF")}})});1==l?$.ajax({type:"post",data:{UID:d,IID:a.content_id,IMG:m},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UpdateFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}});UpdatePasteOrder(d,e);return!1}};
