function UpdateFileOrder(a,d,c){var b=[];$.each($(".qq-upload-list-selector.qq-upload-list").sortable("toArray"),function(c,a){b.push(parseInt(a))});$.ajax({type:"post",data:{UID:a,IID:d,AID:JSON.stringify(b)},url:"/f/UpdateFileOrderF.jsp",dataType:"json",success:function(b){console.log("UploadFileOrderF:"+b.result);c&&0<c.length&&(completeMsg(),setTimeout(function(){location.href=c},1E3))},error:function(b){console.log(b)}})}
function UpdatePasteOrderAjax(a,d,c){return $.ajax({type:"post",data:{UID:a,IID:d,AID:JSON.stringify(c)},url:"/f/UpdateFileOrderF.jsp",dataType:"json"})}
function initUpdateFile(a,d){updateTweetButton();multiFileUploader=new qq.FineUploader({session:{endpoint:"/f/GetIllustFileListF.jsp?TD="+d+"&ID="+a,refreshOnRequest:!0},element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(c,b){this.newfile_num&&0<this.newfile_num&&
(this.setEndpoint("/f/UpdateFileAppendF.jsp",c),this.setParams({UID:this.user_id,IID:this.content_id},c))},onComplete:function(c,b,a,d){append_id=a.append_id;$(".qq-file-id-"+c).attr("id",append_id)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);this.newfile_num&&0<this.newfile_num?(1==this.tweet?Tweet(this.user_id,this.content_id,this.tweet_image,this.delete_tweet):(completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3)),UpdateFileOrder(this.user_id,
this.content_id,"/MyIllustListPcV.jsp")):($("li.qq-upload-success").removeClass("qq-upload-success"),$("button.qq-upload-cancel").removeClass("qq-hide"))},onValidate:function(a){var b=this.getSubmittedSize(),c=this.getSubmittedNum();this.showTotalSize(b,c);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,c+1)},onStatusChange:function(a,b,d){this.newfile_num&&0<this.newfile_num&&this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var c="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(c="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.sessionRequestComplete=function(a,b,d,p){alert(b)};multiFileUploader.total_size=
52428800}function Tweet(a,d,c,b){$.ajax({type:"post",data:{UID:a,IID:d,IMG:c,DELTW:b},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){tweetSucceeded(a)}})}
function UpdateFile(a,d){if(multiFileUploader&&!(0>=$(".qq-upload-list-selector.qq-upload-list").children("li").length)){var c=$("#EditCategory").val(),b=$.trim($("#EditDescription").val()),n=$.trim($("#EditTagList").val());n=n.substr(0,100);var p=$("#ContentOpenId").val(),e=$("#EditPublish").val(),q=$("#EditPassword").val(),k=$("#OptionCheerNg").prop("checked")?0:1,v=$("#OptionRecent").prop("checked")?1:0,r=$("#OptionTweet").prop("checked")?1:0,t=$("#OptionImage").prop("checked")?1:0,f=$("#OptionDeleteTweet").prop("checked")?
1:0,u=null,l=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),g=null,h=null;if(10==e){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}u=$("#EditTwitterList").val()}if(1==l&&(g=getPublishDateTime($("#EditTimeLimitedStart").val()),h=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(g,h,!0,strPublishStartPresent,strPublishEndPresent)))return;
setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99==e&&(r=0);var m=r;1==l&&(m=2==p||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==r&&2!=p&&comparePublishDate(strPublishStartPresent,g)&&comparePublishDate(strPublishEndPresent,h)?1:0:0);startMsg();$.ajaxSingle({type:"post",data:{IID:d,UID:a,CAT:c,DES:b,TAG:n,PID:e,PPW:q,PLD:u,LTP:l,REC:v,PST:g,PED:h,TWT:getTweetSetting(),TWI:getTweetImageSetting(),DELTW:f,
ED:0,CNG:k},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UpdateFileRefTwitterF:"+b.content_id);b&&0<b.content_id?0<multiFileUploader.getSubmittedNum()?(multiFileUploader.user_id=a,multiFileUploader.content_id=b.content_id,multiFileUploader.tweet=m,multiFileUploader.tweet_image=t,multiFileUploader.delete_tweet=f,multiFileUploader.newfile_num=multiFileUploader.getSubmittedNum(),multiFileUploader.uploadStoredFiles()):1==m?(UpdateFileOrder(a,b.content_id,null),Tweet(a,
b.content_id,t,f)):UpdateFileOrder(a,b.content_id,"/MyIllustListPcV.jsp"):errorMsg(b.result)}})}}
function initUpdatePaste(a,d){updateTweetButton();var c=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==c&&$("#EditCategory").val(c)});g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,c){10>$(".InputFile").length&&(a=createPasteElm(c.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,c){c.url&&
alert("error data : "+c.url)}).on("pasteText",function(a,c){$("#TimeLineAddImage").html(g_strPasteMsg)});$.ajax({type:"post",data:{ID:a,TD:d},url:"/f/GetIllustFileListF.jsp",dataType:"json",success:function(a){$.each(a,function(a,b){10>$(".InputFile").length&&(a=createPasteListItem(b.thumbnailUrl,b.append_id),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()})}})}
function UpdatePasteAppendFAjax(a,d,c){a.parent().addClass("Done");a=a.attr("src").replace("data:image/png;base64,","");return 0>=a.length?null:$.ajax({type:"post",data:{UID:d,IID:c,DATA:a},url:"/f/UpdatePasteAppendF.jsp",dataType:"json",async:!1})}
function UpdateFileRefTwitterFAjax(a,d,c,b,n,p,e,q,k,v,r,t,f,u,l,g){return $.ajax({type:"post",data:{UID:a,IID:d,CAT:c,DES:b,TAG:n,PID:p,PPW:e,PLD:q,LTP:r,REC:v,PST:t,PED:f,TWT:u,TWI:l,DELTW:g,ED:1,CNG:k},url:"/f/UpdateFileRefTwitterF.jsp",dataType:"json"})}
function UploadTextRefTwitterFAjax(a,d,c,b,n,p,e,q,k,v,r,t,f,u,l,g,h){return $.ajax({type:"post",data:{UID:a,IID:d,CAT:c,DES:b,BDY:n,TAG:p,PID:e,PPW:q,PLD:k,LTP:t,REC:r,PST:f,PED:u,TWT:l,TWI:g,DELTW:h,ED:1,CNG:v},url:"/f/UpdateTextRefTwitterF.jsp",dataType:"json"})}function UploadFileTweetFAjax(a,d,c,b){return $.ajax({type:"post",data:{UID:a,IID:d,IMG:c,DELTW:b},url:"/f/UploadFileTweetF.jsp",dataType:"json"})}
function createUpdatePaste(){var a=!1;return function(d,c){if(!a){a=!0;var b=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&b++});if(0>=b)a=!1;else{var n=$("#EditCategory").val(),p=$.trim($("#EditDescription").val()),e=$.trim($("#EditTagList").val());e=e.substr(0,100);var q=$("#ContentOpenId").val(),k=$("#EditPublish").val(),v=$("#EditPassword").val(),r=$("#OptionCheerNg").prop("checked")?0:1,t=$("#OptionRecent").prop("checked")?1:0,f=$("#OptionTweet").prop("checked")?1:0,u=
$("#OptionImage").prop("checked")?1:0,l=$("#OptionDeleteTweet").prop("checked")?1:0,g=null,h=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),m=null,w=null;if(10==k){if($("#TwitterListNotFound").is(":visible")){a=!1;twitterListNotFoundMsg();return}g=$("#EditTwitterList").val()}if(1==h&&(m=getPublishDateTime($("#EditTimeLimitedStart").val()),w=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),
!checkPublishDatetime(m,w,!0,strPublishStartPresent,strPublishEndPresent))){a=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(n);99==k&&(f=0);var x=f;1==h&&(x=2==q||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==f&&2!=q&&comparePublishDate(strPublishStartPresent,m)&&comparePublishDate(strPublishEndPresent,w)?1:0:0);startMsg();var z=[],y=null;UpdateFileRefTwitterFAjax(d,c,n,p,e,k,v,g,r,t,h,m,w,
getTweetSetting(),getTweetImageSetting(),l).done(function(a){var b=null;$(".imgView").each(function(){b=UpdatePasteAppendFAjax($(this),d,a.content_id);null!=b&&z.push(b)});y=1==x?UploadFileTweetFAjax(d,a.content_id,u,l):function(){var a=$.Deferred();a.resolve(1);return a.promise()};$.when.apply($,z).then(function(){var b=[];$.each($("#PasteZone").sortable("toArray"),function(a,c){b.push(parseInt(c))});for(var c=0;c<arguments.length;c++){var e=1==b.length?arguments[0].append_id:arguments[c][0].append_id;
0<=e&&(b[c]=e);if(1==b.length)break}return UpdatePasteOrderAjax(d,a.content_id,b)},function(a){errorMsg(-10)}).then(y,function(a){errorMsg(-11)}).then(function(a){tweetSucceeded(a)},function(a){errorMsg(-12)})});return!1}}}}var UpdatePaste=createUpdatePaste();
function createUpdateText(){var a=!1;return function(d,c){if(!a){a=!0;var b=$("#EditCategory").val(),n=$.trim($("#EditDescription").val()),p=$.trim($("#EditTextBody").val()),e=$.trim($("#EditTagList").val());e=e.substr(0,100);var q=$("#ContentOpenId").val(),k=$("#EditPublish").val(),v=$("#EditPassword").val(),r=$("#OptionCheerNg").prop("checked")?0:1,t=$("#OptionRecent").prop("checked")?1:0,f=$("#OptionTweet").prop("checked")?1:0,u=$("#OptionImage").prop("checked")?1:0,l=$("#OptionDeleteTweet").prop("checked")?
1:0,g=null,h=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),m=null,w=null;if(10==k){if($("#TwitterListNotFound").is(":visible")){a=!1;twitterListNotFoundMsg();return}g=$("#EditTwitterList").val()}if(1==h&&(m=getPublishDateTime($("#EditTimeLimitedStart").val()),w=getPublishDateTime($("#EditTimeLimitedEnd").val()),strPublishStartPresent=$("#EditTimeLimitedStartPresent").val(),strPublishEndPresent=$("#EditTimeLimitedEndPresent").val(),!checkPublishDatetime(m,w,!0,strPublishStartPresent,
strPublishEndPresent))){a=!1;return}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);99==k&&(f=0);var x=f;1==h&&(x=2==q||null!=strPublishStartPresent&&null!=strPublishEndPresent?1==f&&2!=q&&comparePublishDate(strPublishStartPresent,m)&&comparePublishDate(strPublishEndPresent,w)?1:0:0);startMsg();var z=[],y=null;UploadTextRefTwitterFAjax(d,c,b,n,p,e,k,v,g,r,t,h,m,w,getTweetSetting(),getTweetImageSetting(),l).done(function(a){y=
1==x?UploadFileTweetFAjax(d,a.content_id,u,l):function(){var a=$.Deferred();a.resolve(1);return a.promise()};$.when.apply($,z).then(y,function(a){errorMsg(-11)}).then(function(a){tweetSucceeded(a)},function(a){errorMsg(-12)})});return!1}}}var UpdateText=createUpdateText();
