var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var g=a.length,d=0;d<g;d++){var k=a[d];if(c.call(b,k,d,a))return{i:d,v:k}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,g){if(c){b=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var d=a[g];d in b||(b[d]={});b=b[d]}a=a[a.length-1];g=b[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var multiFileUploader=null;$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(a){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return d.mountNonInputable(a)._container};a.fn.pastableNonInputable=function(){var b;var e=0;for(b=this.length;e<b;e++){var h=this[e];h._pastable||a(h).is("textarea, input:text, [contenteditable]")||(d.mountNonInputable(h),h._pastable=!0)}return this};a.fn.pastableTextarea=function(){var b;var e=0;for(b=
this.length;e<b;e++){var h=this[e];h._pastable||a(h).is(":not(textarea, input:text)")||(d.mountTextarea(h),h._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var b;var e=0;for(b=this.length;e<b;e++){var h=this[e];h._pastable||a(h).is(":not([contenteditable])")||(d.mountContenteditable(h),h._pastable=!0)}return this};var c=function(a,e){var b,c,f;null==e&&(e=512);if(!(b=a.match(/^data:([^;]+);base64,(.+)$/)))return null;a=b[1];var m=atob(b[2]);b=[];for(f=0;f<m.length;){var n=m.slice(f,
f+e);var p=Array(n.length);for(c=0;c<n.length;)p[c]=n.charCodeAt(c),c++;p=new Uint8Array(p);b.push(p);f+=e}return new Blob(b,{type:a})};var b=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var g=function(b,e){var c=b.nodeName.toLowerCase();if("area"===c){e=b.parentNode;c=e.name;if(!b.href||!c||"map"!==e.nodeName.toLowerCase())return!1;b=a("img[usemap='#"+
c+"']");return 0<b.length&&b.is(":visible")}/^(input|select|textarea|button|object)$/.test(c)?(c=!b.disabled)&&(e=a(b).closest("fieldset")[0])&&(c=!e.disabled):c="a"===c?b.href||e:e;return(c=c||a(b).is("[contenteditable]"))&&a(b).is(":visible")};var d=function(){function d(b,c){this._container=b;this._target=c;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(a){return function(b){var c,e,d;a.originalEvent=null!==b.originalEvent?
b.originalEvent:null;a._paste_event_fired=!0;if(null!=(null!=(c=b.originalEvent)?c.clipboardData:void 0)){var f=b.originalEvent.clipboardData;if(f.items){var h=null;a.originalEvent.pastedTypes=[];var g=f.items;var l=0;for(e=g.length;l<e;l++)c=g[l],c.type.match(/^text\/(plain|rtf|html)/)&&a.originalEvent.pastedTypes.push(c.type);var k=f.items;l=e=0;for(g=k.length;e<g;l=++e){c=k[l];if(c.type.match(/^image\//)){f=new FileReader;f.onload=function(b){return a._handleImage(b.target.result,a.originalEvent,
h)};try{f.readAsDataURL(c.getAsFile())}catch(v){}b.preventDefault();break}if("text/plain"===c.type){if(0===l&&1<f.items.length&&f.items[1].type.match(/^image\//)){var r=!0;var t=f.items[1].type}c.getAsString(function(b){return r?(h=b,a._target.trigger("pasteText",{text:b,isFilename:!0,fileType:t,originalEvent:a.originalEvent})):a._target.trigger("pasteText",{text:b,originalEvent:a.originalEvent})})}"text/rtf"===c.type&&c.getAsString(function(b){return a._target.trigger("pasteTextRich",{text:b,originalEvent:a.originalEvent})});
"text/html"===c.type&&c.getAsString(function(b){return a._target.trigger("pasteTextHtml",{text:b,originalEvent:a.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(f.types,"text/plain")){var q=f.getData("Text");setTimeout(function(){return a._target.trigger("pasteText",{text:q,originalEvent:a.originalEvent})},1)}a._checkImagesInContainer(function(b){return a._handleImage(b,a.originalEvent)})}}if(f=window.clipboardData)if(null!=(d=q=f.getData("Text"))&&d.length)setTimeout(function(){a._target.trigger("pasteText",
{text:q,originalEvent:a.originalEvent});return a._target.trigger("_pasteCheckContainerDone")},1);else{f=f.files;d=0;for(c=f.length;d<c;d++)b=f[d],a._handleImage(URL.createObjectURL(b),a.originalEvent);a._checkImagesInContainer(function(a){})}return null}}(this))}d.prototype._target=null;d.prototype._container=null;d.mountNonInputable=function(c){var e=new d(b().appendTo(c),c);a(c).on("click",function(a){return function(a){if(!g(a.target,!1)&&!window.getSelection().toString())return e._container.focus()}}(this));
e._container.on("focus",function(b){return function(){return a(c).addClass("pastable-focus")}}(this));return e._container.on("blur",function(b){return function(){return a(c).removeClass("pastable-focus")}}(this))};d.mountTextarea=function(c){var e,g;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(e=Object.getOwnPropertyDescriptor)&&null!=(g=e.call(Object,DataTransfer.prototype,"items"))&&g.get)return this.mountContenteditable(c);var f=new d(b().insertBefore(c),
c);var m=!1;a(c).on("keyup",function(a){var c;if(17===(c=a.keyCode)||224===c)m=!1;return null});a(c).on("keydown",function(b){var e;if(17===(e=b.keyCode)||224===e)m=!0;null!=b.ctrlKey&&null!=b.metaKey&&(m=b.ctrlKey||b.metaKey);m&&86===b.keyCode&&(f._textarea_focus_stolen=!0,f._container.focus(),f._paste_event_fired=!1,setTimeout(function(b){return function(){if(!f._paste_event_fired)return a(c).focus(),f._textarea_focus_stolen=!1}}(this),1));return null});a(c).on("paste",function(a){return function(){}}(this));
a(c).on("focus",function(b){return function(){if(!f._textarea_focus_stolen)return a(c).addClass("pastable-focus")}}(this));a(c).on("blur",function(b){return function(){if(!f._textarea_focus_stolen)return a(c).removeClass("pastable-focus")}}(this));a(f._target).on("_pasteCheckContainerDone",function(b){return function(){a(c).focus();return f._textarea_focus_stolen=!1}}(this));return a(f._target).on("pasteText",function(b){return function(b,e){var f=a(c).prop("selectionStart");var d=a(c).prop("selectionEnd");
b=a(c).val();a(c).val(""+b.slice(0,f)+e.text+b.slice(d));a(c)[0].setSelectionRange(f+e.text.length,f+e.text.length);return a(c).trigger("change")}}(this))};d.mountContenteditable=function(b){new d(b,b);a(b).on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return a(b).on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};d.prototype._handleImage=function(a,b,d){if(a.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var f=new Image;f.crossOrigin="anonymous";f.onload=function(a){return function(){var e=document.createElement("canvas");e.width=f.width;e.height=f.height;e.getContext("2d").drawImage(f,0,0,e.width,e.height);var g=null;try{g=e.toDataURL("image/png");var h=c(g)}catch(u){}g&&a._target.trigger("pasteImage",{blob:h,dataURL:g,width:f.width,height:f.height,originalEvent:b,
name:d});return a._target.trigger("pasteImageEnd")}}(this);f.onerror=function(b){return function(){b._target.trigger("pasteImageError",{message:"Failed to get image from: "+a,url:a});return b._target.trigger("pasteImageEnd")}}(this);return f.src=a};d.prototype._checkImagesInContainer=function(b){var c;var e=Math.floor(1E3*Math.random());var f=this._container.find("img");var d=0;for(c=f.length;d<c;d++){var g=f[d];g["_paste_marked_"+e]=!0}return setTimeout(function(c){return function(){var d;var f=
c._container.find("img");var h=0;for(d=f.length;h<d;h++)g=f[h],g["_paste_marked_"+e]||(b(g.src),a(g).remove());return c._target.trigger("_pasteCheckContainerDone")}}(this),1)};return d}()}).call(this);function DispDescCharNum(){var a=200-$("#EditDescription").val().length;$("#DescriptionCharNum").html(a)}function DispTagListCharNum(){var a=100-$("#EditTagList").val().length;$("#EditTagListCharNum").html(a)}
function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}function setTweetImageSetting(a){setLocalStrage("upload_tweet_image",a)}function getTweetImageSetting(){return getLocalStrage("upload_tweet_image")?!0:!1}function setLastCategorySetting(a){setLocalStrage("last_category",a)}
function getLastCategorySetting(){return getLocalStrage("last_category")}function updateTweetButton(){$("#OptionTweet").prop("checked")?($("#ImageSwitch .OptionLabel").removeClass("disabled"),$("#ImageSwitch .onoffswitch").removeClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!1)):($("#ImageSwitch .OptionLabel").addClass("disabled"),$("#ImageSwitch .onoffswitch").addClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!0))}
function updatePublish(){var a=parseInt($("#EditPublish").val(),10),c=[$("#ItemTwitterList"),$("#ItemPassword"),$("#ItemTimeLimited")];if(4==a||10==a||11==a){var b=null,g=null;switch(a){case 4:g=$("#ItemPassword");break;case 10:g=$("#ItemTwitterList");break;case 11:g=$("#ItemTimeLimited")}for(var d=0;d<c.length;d++){var k=c[d];if(k.is(":visible")){b=k;break}}null==b?g.slideDown(300):b.slideUp(300,function(){g.delay(150).slideDown(300)});11==a&&(a=new Date,a.setMinutes(30*Math.floor((a.getMinutes()+
45)/30)),$(".EditTimeLimited").flatpickr({enableTime:!0,dateFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,minDate:a}))}else for(d=0;d<c.length;d++)k=c[d],k.is(":visible")&&k.slideUp(300)}
function initUploadFile(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();multiFileUploader=new qq.FineUploader({element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg",
"jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,b){this.first_file?(this.first_file=!1,this.setEndpoint("/f/UploadFileFirstF.jsp",a),console.log("UploadFileFirstF")):(this.setEndpoint("/f/UploadFileAppendF.jsp",a),console.log("UploadFileAppendF"));this.setParams({UID:this.user_id,IID:this.illust_id,REC:this.recent},a)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);1==this.tweet?$.ajax({type:"post",
data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3))},onValidate:function(a){var b=this.getSubmittedSize(),c=this.getSubmittedNum();this.showTotalSize(b,c);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,c+1)},onStatusChange:function(a,
b,g){this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var c="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(c="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",
$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.total_size=52428800}
function UploadFile(a){if(multiFileUploader&&!(0>=multiFileUploader.getSubmittedNum())){var c=$("#EditCategory").val(),b=$.trim($("#EditDescription").val());b=b.substr(0,200);var g=$.trim($("#EditTagList").val());g=g.substr(0,100);var d=$("#EditPublish").val(),k=$("#EditPassword").val(),e=$("#OptionRecent").prop("checked")?1:0,h=$("#OptionTweet").prop("checked")?1:0,l=$("#OptionImage").prop("checked")?1:0,f=null;10==d&&(f=$("#EditTwitterList").val());if(11==d){var m=$("#EditTimeLimitedStart").val(),
n=$("#EditTimeLimitedEnd").val();if(""==m||""==n){dateTimeEmptyMsg();return}if(Date.parse(m)>Date.parse(n)){dateTimeReverseMsg();return}}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99==d&&(e=2,h=0);startMsg();console.log("start upload");$.ajaxSingle({type:"post",data:{UID:a,CAT:c,DES:b,TAG:g,PID:d,PPW:k,PLD:f},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF");
b&&b.content_id&&(0<b.content_id?(multiFileUploader.first_file=!0,multiFileUploader.user_id=a,multiFileUploader.illust_id=b.content_id,multiFileUploader.recent=e,multiFileUploader.tweet=h,multiFileUploader.tweet_image=l,multiFileUploader.uploadStoredFiles()):errorMsg())}})}}var g_strPasteMsg="";
function initUploadPaste(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),
$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)})}
function createPasteElm(a){var c=$("<div />").addClass("InputFile"),b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function initPasteElm(a){a.on("pasteImage",function(a,b){$(".OrgMessage",this).hide();$(".imgView",this).attr("src",b.dataURL).show()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){})}function updatePasteNum(){strTotal="("+$(".InputFile").length+"/10)";$("#TotalSize").html(strTotal)}
function UploadPaste(a){var c=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&c++});console.log(c);if(!(0>=c)){var b=$("#EditCategory").val(),g=$.trim($("#EditDescription").val());g=g.substr(0,200);var d=$.trim($("#EditTagList").val());d=d.substr(0,100);var k=$("#EditPublish").val(),e=$("#EditPassword").val(),h=$("#OptionRecent").prop("checked")?1:0,l=$("#OptionTweet").prop("checked")?1:0,f=$("#OptionImage").prop("checked")?1:0;setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);99==k&&(h=2,l=0);startMsg();$.ajaxSingle({type:"post",data:{UID:a,CAT:b,DES:g,TAG:d,PID:k,PPW:e,PLD:""},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF",b.content_id);var c=!0;$(".imgView").each(function(){$(this).parent().addClass("Done");var d=$(this).attr("src").replace("data:image/png;base64,","");if(0>=d.length)return!0;c?(c=!1,$.ajax({type:"post",data:{UID:a,
IID:b.content_id,REC:h,DATA:d},url:"/f/UploadPasteFirstF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteFirstF")}})):$.ajax({type:"post",data:{UID:a,IID:b.content_id,DATA:d},url:"/f/UploadPasteAppendF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteAppendF")}})});1==l?$.ajax({type:"post",data:{UID:a,IID:b.content_id,IMG:f},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href=
"/MyHomePcV.jsp"},1E3)}}):setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}});return!1}};
