var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var e=a.length,f=0;f<e;f++){var g=a[f];if(c.call(b,g,f,a))return{i:f,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in b||(b[f]={});b=b[f]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var multiFileUploader=null;$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(a){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return f.mountNonInputable(a)._container};a.fn.pastableNonInputable=function(){var c;var d=0;for(c=this.length;d<c;d++){var b=this[d];b._pastable||a(b).is("textarea, input:text, [contenteditable]")||(f.mountNonInputable(b),b._pastable=!0)}return this};a.fn.pastableTextarea=function(){var c;var d=0;for(c=
this.length;d<c;d++){var b=this[d];b._pastable||a(b).is(":not(textarea, input:text)")||(f.mountTextarea(b),b._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var b;var d=0;for(b=this.length;d<b;d++){var c=this[d];c._pastable||a(c).is(":not([contenteditable])")||(f.mountContenteditable(c),c._pastable=!0)}return this};var c=function(a,d){var c,b,h;null==d&&(d=512);if(!(c=a.match(/^data:([^;]+);base64,(.+)$/)))return null;a=c[1];var m=atob(c[2]);c=[];for(h=0;h<m.length;){var l=m.slice(h,
h+d);var g=Array(l.length);for(b=0;b<l.length;)g[b]=l.charCodeAt(b),b++;g=new Uint8Array(g);c.push(g);h+=d}return new Blob(c,{type:a})};var b=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var e=function(c,b){var d=c.nodeName.toLowerCase();if("area"===d){b=c.parentNode;d=b.name;if(!c.href||!d||"map"!==b.nodeName.toLowerCase())return!1;c=a("img[usemap='#"+
d+"']");return 0<c.length&&c.is(":visible")}/^(input|select|textarea|button|object)$/.test(d)?(d=!c.disabled)&&(b=a(c).closest("fieldset")[0])&&(d=!b.disabled):d="a"===d?c.href||b:b;return(d=d||a(c).is("[contenteditable]"))&&a(c).is(":visible")};var f=function(){function g(c,b){this._container=c;this._target=b;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(a){return function(c){var b,d,h;a.originalEvent=null!==c.originalEvent?
c.originalEvent:null;a._paste_event_fired=!0;if(null!=(null!=(b=c.originalEvent)?b.clipboardData:void 0)){var e=c.originalEvent.clipboardData;if(e.items){var g=null;a.originalEvent.pastedTypes=[];var f=e.items;var k=0;for(d=f.length;k<d;k++)b=f[k],b.type.match(/^text\/(plain|rtf|html)/)&&a.originalEvent.pastedTypes.push(b.type);var n=e.items;k=d=0;for(f=n.length;d<f;k=++d){b=n[k];if(b.type.match(/^image\//)){e=new FileReader;e.onload=function(b){return a._handleImage(b.target.result,a.originalEvent,
g)};try{e.readAsDataURL(b.getAsFile())}catch(v){}c.preventDefault();break}if("text/plain"===b.type){if(0===k&&1<e.items.length&&e.items[1].type.match(/^image\//)){var r=!0;var t=e.items[1].type}b.getAsString(function(b){return r?(g=b,a._target.trigger("pasteText",{text:b,isFilename:!0,fileType:t,originalEvent:a.originalEvent})):a._target.trigger("pasteText",{text:b,originalEvent:a.originalEvent})})}"text/rtf"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextRich",{text:b,originalEvent:a.originalEvent})});
"text/html"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextHtml",{text:b,originalEvent:a.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(e.types,"text/plain")){var p=e.getData("Text");setTimeout(function(){return a._target.trigger("pasteText",{text:p,originalEvent:a.originalEvent})},1)}a._checkImagesInContainer(function(b){return a._handleImage(b,a.originalEvent)})}}if(e=window.clipboardData)if(null!=(h=p=e.getData("Text"))&&h.length)setTimeout(function(){a._target.trigger("pasteText",
{text:p,originalEvent:a.originalEvent});return a._target.trigger("_pasteCheckContainerDone")},1);else{e=e.files;h=0;for(b=e.length;h<b;h++)c=e[h],a._handleImage(URL.createObjectURL(c),a.originalEvent);a._checkImagesInContainer(function(a){})}return null}}(this))}g.prototype._target=null;g.prototype._container=null;g.mountNonInputable=function(c){var d=new g(b().appendTo(c),c);a(c).on("click",function(a){return function(a){if(!e(a.target,!1)&&!window.getSelection().toString())return d._container.focus()}}(this));
d._container.on("focus",function(b){return function(){return a(c).addClass("pastable-focus")}}(this));return d._container.on("blur",function(b){return function(){return a(c).removeClass("pastable-focus")}}(this))};g.mountTextarea=function(c){var d,e;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(d=Object.getOwnPropertyDescriptor)&&null!=(e=d.call(Object,DataTransfer.prototype,"items"))&&e.get)return this.mountContenteditable(c);var h=new g(b().insertBefore(c),
c);var f=!1;a(c).on("keyup",function(a){var c;if(17===(c=a.keyCode)||224===c)f=!1;return null});a(c).on("keydown",function(b){var d;if(17===(d=b.keyCode)||224===d)f=!0;null!=b.ctrlKey&&null!=b.metaKey&&(f=b.ctrlKey||b.metaKey);f&&86===b.keyCode&&(h._textarea_focus_stolen=!0,h._container.focus(),h._paste_event_fired=!1,setTimeout(function(b){return function(){if(!h._paste_event_fired)return a(c).focus(),h._textarea_focus_stolen=!1}}(this),1));return null});a(c).on("paste",function(a){return function(){}}(this));
a(c).on("focus",function(b){return function(){if(!h._textarea_focus_stolen)return a(c).addClass("pastable-focus")}}(this));a(c).on("blur",function(b){return function(){if(!h._textarea_focus_stolen)return a(c).removeClass("pastable-focus")}}(this));a(h._target).on("_pasteCheckContainerDone",function(b){return function(){a(c).focus();return h._textarea_focus_stolen=!1}}(this));return a(h._target).on("pasteText",function(b){return function(b,d){var e=a(c).prop("selectionStart");var f=a(c).prop("selectionEnd");
b=a(c).val();a(c).val(""+b.slice(0,e)+d.text+b.slice(f));a(c)[0].setSelectionRange(e+d.text.length,e+d.text.length);return a(c).trigger("change")}}(this))};g.mountContenteditable=function(b){new g(b,b);a(b).on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return a(b).on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};g.prototype._handleImage=function(a,b,e){if(a.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var d=new Image;d.crossOrigin="anonymous";d.onload=function(a){return function(){var f=document.createElement("canvas");f.width=d.width;f.height=d.height;f.getContext("2d").drawImage(d,0,0,f.width,f.height);var g=null;try{g=f.toDataURL("image/png");var h=c(g)}catch(u){}g&&a._target.trigger("pasteImage",{blob:h,dataURL:g,width:d.width,height:d.height,originalEvent:b,
name:e});return a._target.trigger("pasteImageEnd")}}(this);d.onerror=function(b){return function(){b._target.trigger("pasteImageError",{message:"Failed to get image from: "+a,url:a});return b._target.trigger("pasteImageEnd")}}(this);return d.src=a};g.prototype._checkImagesInContainer=function(b){var c;var d=Math.floor(1E3*Math.random());var e=this._container.find("img");var f=0;for(c=e.length;f<c;f++){var g=e[f];g["_paste_marked_"+d]=!0}return setTimeout(function(c){return function(){var e;var f=
c._container.find("img");var h=0;for(e=f.length;h<e;h++)g=f[h],g["_paste_marked_"+d]||(b(g.src),a(g).remove());return c._target.trigger("_pasteCheckContainerDone")}}(this),1)};return g}()}).call(this);function DispDescCharNum(){var a=200-$("#EditDescription").val().length;$("#DescriptionCharNum").html(a)}function DispTagListCharNum(){var a=100-$("#EditTagList").val().length;$("#EditTagListCharNum").html(a)}
function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}function setTweetImageSetting(a){setLocalStrage("upload_tweet_image",a)}function getTweetImageSetting(){return getLocalStrage("upload_tweet_image")?!0:!1}function setLastCategorySetting(a){setLocalStrage("last_category",a)}
function getLastCategorySetting(){return getLocalStrage("last_category")}function checkPublishDatetime(a,c){return""==a||""==c?(dateTimeEmptyMsg(),!1):Date.parse(a)<Date.now()?(dateTimePastMsg(),!1):Date.parse(a)>Date.parse(c)?(dateTimeReverseMsg(),!1):!0}
function updateTweetButton(){$("#OptionTweet").prop("checked")?($("#ImageSwitch .OptionLabel").removeClass("disabled"),$("#ImageSwitch .onoffswitch").removeClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!1)):($("#ImageSwitch .OptionLabel").addClass("disabled"),$("#ImageSwitch .onoffswitch").addClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!0))}
function initStartDatetime(a){$("#EditTimeLimitedStart").flatpickr({enableTime:!0,dateFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,defaultDate:a})}function initEndDatetime(a){$("#EditTimeLimitedEnd").flatpickr({enableTime:!0,dateFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,defaultDate:a})}
function updatePublish(){var a=parseInt($("#EditPublish").val(),10),c=[$("#ItemTwitterList"),$("#ItemPassword"),$("#ItemTimeLimited")];if(4==a||10==a||11==a){var b=null,e=null;switch(a){case 4:e=$("#ItemPassword");break;case 10:e=$("#ItemTwitterList");break;case 11:e=$("#ItemTimeLimited")}for(var f=0;f<c.length;f++){var g=c[f];if(g.is(":visible")){b=g;break}}null==b?e.slideDown(300):b.slideUp(300,function(){e.delay(150).slideDown(300)});11==a&&$.each(["#EditTimeLimitedStart","#EditTimeLimitedEnd"],
function(a,b){0>$(b)[0].classList.value.indexOf("flatpickr-input")&&(a=new Date,a.setMinutes(30*Math.floor((a.getMinutes()+45)/30)),$(b).flatpickr({enableTime:!0,dateFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,minDate:a}))})}else for(f=0;f<c.length;f++)g=c[f],g.is(":visible")&&g.slideUp(300)}
function initUploadFile(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();multiFileUploader=new qq.FineUploader({element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg",
"jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,b){this.first_file?(this.first_file=!1,this.setEndpoint("/f/UploadFileFirstF.jsp",a),console.log("UploadFileFirstF")):(this.setEndpoint("/f/UploadFileAppendF.jsp",a),console.log("UploadFileAppendF"));this.setParams({UID:this.user_id,IID:this.illust_id,REC:this.recent},a)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);1==this.tweet?$.ajax({type:"post",
data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3))},onValidate:function(a){var b=this.getSubmittedSize(),c=this.getSubmittedNum();this.showTotalSize(b,c);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,c+1)},onStatusChange:function(a,
b,e){this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var c="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(c="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",
$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.total_size=52428800}
function UploadFile(a){if(multiFileUploader&&!(0>=multiFileUploader.getSubmittedNum())){var c=$("#EditCategory").val(),b=$.trim($("#EditDescription").val());b=b.substr(0,200);var e=$.trim($("#EditTagList").val());e=e.substr(0,100);var f=$("#EditPublish").val(),g=$("#EditPassword").val(),d=$("#OptionRecent").prop("checked")?1:0,k=$("#OptionTweet").prop("checked")?1:0,n=$("#OptionImage").prop("checked")?1:0,h=null,m=$("#EditTimeLimitedStart").val(),l=$("#EditTimeLimitedEnd").val();10==f&&(h=$("#EditTwitterList").val());
if(11!=f||checkPublishDatetime(m,l))setTweetSetting($("#OptionTweet").prop("checked")),setTweetImageSetting($("#OptionImage").prop("checked")),setLastCategorySetting(c),99==f&&(d=2,k=0),startMsg(),console.log("start upload"),$.ajaxSingle({type:"post",data:{UID:a,CAT:c,DES:b,TAG:e,PID:f,PPW:g,PLD:h,PST:m,PED:l},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF");b&&b.content_id&&(0<b.content_id?(multiFileUploader.first_file=!0,multiFileUploader.user_id=
a,multiFileUploader.illust_id=b.content_id,multiFileUploader.recent=d,multiFileUploader.tweet=k,multiFileUploader.tweet_image=n,multiFileUploader.uploadStoredFiles()):errorMsg())}})}}var g_strPasteMsg="";
function initUploadPaste(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),
$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)})}
function createPasteElm(a){var c=$("<div />").addClass("InputFile"),b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function createPasteListItem(a,c){c=$("<li />").addClass("InputFile").attr("id",c);var b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function createPasteListItem(a,c){c=$("<li />").addClass("InputFile").attr("id",c);var b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function initPasteElm(a){a.on("pasteImage",function(a,b){$(".OrgMessage",this).hide();$(".imgView",this).attr("src",b.dataURL).show()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){})}function updatePasteNum(){strTotal="("+$(".InputFile").length+"/10)";$("#TotalSize").html(strTotal)}
function UploadPaste(a){var c=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&c++});console.log(c);if(!(0>=c)){var b=$("#EditCategory").val(),e=$.trim($("#EditDescription").val());e=e.substr(0,200);var f=$.trim($("#EditTagList").val());f=f.substr(0,100);var g=$("#EditPublish").val(),d=$("#EditPassword").val(),k=$("#OptionRecent").prop("checked")?1:0,n=$("#OptionTweet").prop("checked")?1:0,h=$("#OptionImage").prop("checked")?1:0,m=null,l=$("#EditTimeLimitedStart").val(),q=$("#EditTimeLimitedEnd").val();
10==g&&(m=$("#EditTwitterList").val());if(11!=g||checkPublishDatetime(l,q))return setTweetSetting($("#OptionTweet").prop("checked")),setTweetImageSetting($("#OptionImage").prop("checked")),setLastCategorySetting(b),99==g&&(k=2,n=0),startMsg(),$.ajaxSingle({type:"post",data:{UID:a,CAT:b,DES:e,TAG:f,PID:g,PPW:d,PLD:m,PST:l,PED:q,ED:1},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF",b.content_id);var c=!0;$(".imgView").each(function(){$(this).parent().addClass("Done");
var d=$(this).attr("src").replace("data:image/png;base64,","");if(0>=d.length)return!0;c?(c=!1,$.ajax({type:"post",data:{UID:a,IID:b.content_id,REC:k,DATA:d},url:"/f/UploadPasteFirstF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteFirstF")}})):$.ajax({type:"post",data:{UID:a,IID:b.content_id,DATA:d},url:"/f/UploadPasteAppendF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteAppendF")}})});1==n?$.ajax({type:"post",data:{UID:a,IID:b.content_id,IMG:h},
url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}),!1}};
