var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,e){a instanceof String&&(a=String(a));for(var h=a.length,g=0;g<h;g++){var d=a[g];if(b.call(e,d,g,a))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,b,e,h){if(b){e=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var g=a[h];g in e||(e[g]={});e=e[g]}a=a[a.length-1];h=e[a];b=b(h);b!=h&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");var multiFileUploader=null;$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(a){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return g.mountNonInputable(a)._container};a.fn.pastableNonInputable=function(){var d;var c=0;for(d=this.length;c<d;c++){var f=this[c];f._pastable||a(f).is("textarea, input:text, [contenteditable]")||(g.mountNonInputable(f),f._pastable=!0)}return this};a.fn.pastableTextarea=function(){var d;var c=0;for(d=
this.length;c<d;c++){var f=this[c];f._pastable||a(f).is(":not(textarea, input:text)")||(g.mountTextarea(f),f._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var d;var c=0;for(d=this.length;c<d;c++){var f=this[c];f._pastable||a(f).is(":not([contenteditable])")||(g.mountContenteditable(f),f._pastable=!0)}return this};var b=function(a,c){var f,l,b;null==c&&(c=512);if(!(f=a.match(/^data:([^;]+);base64,(.+)$/)))return null;a=f[1];var d=atob(f[2]);f=[];for(b=0;b<d.length;){var e=d.slice(b,
b+c);var m=Array(e.length);for(l=0;l<e.length;)m[l]=e.charCodeAt(l),l++;m=new Uint8Array(m);f.push(m);b+=c}return new Blob(f,{type:a})};var e=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var h=function(b,c){var f=b.nodeName.toLowerCase();if("area"===f){c=b.parentNode;f=c.name;if(!b.href||!f||"map"!==c.nodeName.toLowerCase())return!1;b=a("img[usemap='#"+
f+"']");return 0<b.length&&b.is(":visible")}/^(input|select|textarea|button|object)$/.test(f)?(f=!b.disabled)&&(c=a(b).closest("fieldset")[0])&&(f=!c.disabled):f="a"===f?b.href||c:c;return(f=f||a(b).is("[contenteditable]"))&&a(b).is(":visible")};var g=function(){function d(c,b){this._container=c;this._target=b;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(a){return function(c){var b,f,e;a.originalEvent=null!==c.originalEvent?
c.originalEvent:null;a._paste_event_fired=!0;if(null!=(null!=(b=c.originalEvent)?b.clipboardData:void 0)){var d=c.originalEvent.clipboardData;if(d.items){var k=null;a.originalEvent.pastedTypes=[];var g=d.items;var l=0;for(f=g.length;l<f;l++)b=g[l],b.type.match(/^text\/(plain|rtf|html)/)&&a.originalEvent.pastedTypes.push(b.type);var h=d.items;l=f=0;for(g=h.length;f<g;l=++f){b=h[l];if(b.type.match(/^image\//)){d=new FileReader;d.onload=function(b){return a._handleImage(b.target.result,a.originalEvent,
k)};try{d.readAsDataURL(b.getAsFile())}catch(t){}c.preventDefault();break}if("text/plain"===b.type){if(0===l&&1<d.items.length&&d.items[1].type.match(/^image\//)){var p=!0;var q=d.items[1].type}b.getAsString(function(b){return p?(k=b,a._target.trigger("pasteText",{text:b,isFilename:!0,fileType:q,originalEvent:a.originalEvent})):a._target.trigger("pasteText",{text:b,originalEvent:a.originalEvent})})}"text/rtf"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextRich",{text:b,originalEvent:a.originalEvent})});
"text/html"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextHtml",{text:b,originalEvent:a.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(d.types,"text/plain")){var n=d.getData("Text");setTimeout(function(){return a._target.trigger("pasteText",{text:n,originalEvent:a.originalEvent})},1)}a._checkImagesInContainer(function(b){return a._handleImage(b,a.originalEvent)})}}if(d=window.clipboardData)if(null!=(e=n=d.getData("Text"))&&e.length)setTimeout(function(){a._target.trigger("pasteText",
{text:n,originalEvent:a.originalEvent});return a._target.trigger("_pasteCheckContainerDone")},1);else{d=d.files;e=0;for(b=d.length;e<b;e++)c=d[e],a._handleImage(URL.createObjectURL(c),a.originalEvent);a._checkImagesInContainer(function(a){})}return null}}(this))}d.prototype._target=null;d.prototype._container=null;d.mountNonInputable=function(b){var c=new d(e().appendTo(b),b);a(b).on("click",function(a){return function(a){if(!h(a.target,!1)&&!window.getSelection().toString())return c._container.focus()}}(this));
c._container.on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return c._container.on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};d.mountTextarea=function(b){var f,c;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(f=Object.getOwnPropertyDescriptor)&&null!=(c=f.call(Object,DataTransfer.prototype,"items"))&&c.get)return this.mountContenteditable(b);var k=new d(e().insertBefore(b),
b);var g=!1;a(b).on("keyup",function(a){var b;if(17===(b=a.keyCode)||224===b)g=!1;return null});a(b).on("keydown",function(c){var f;if(17===(f=c.keyCode)||224===f)g=!0;null!=c.ctrlKey&&null!=c.metaKey&&(g=c.ctrlKey||c.metaKey);g&&86===c.keyCode&&(k._textarea_focus_stolen=!0,k._container.focus(),k._paste_event_fired=!1,setTimeout(function(c){return function(){if(!k._paste_event_fired)return a(b).focus(),k._textarea_focus_stolen=!1}}(this),1));return null});a(b).on("paste",function(a){return function(){}}(this));
a(b).on("focus",function(c){return function(){if(!k._textarea_focus_stolen)return a(b).addClass("pastable-focus")}}(this));a(b).on("blur",function(c){return function(){if(!k._textarea_focus_stolen)return a(b).removeClass("pastable-focus")}}(this));a(k._target).on("_pasteCheckContainerDone",function(c){return function(){a(b).focus();return k._textarea_focus_stolen=!1}}(this));return a(k._target).on("pasteText",function(c){return function(c,f){var d=a(b).prop("selectionStart");var e=a(b).prop("selectionEnd");
c=a(b).val();a(b).val(""+c.slice(0,d)+f.text+c.slice(e));a(b)[0].setSelectionRange(d+f.text.length,d+f.text.length);return a(b).trigger("change")}}(this))};d.mountContenteditable=function(b){new d(b,b);a(b).on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return a(b).on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};d.prototype._handleImage=function(a,f,d){if(a.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var c=new Image;c.crossOrigin="anonymous";c.onload=function(a){return function(){var e=document.createElement("canvas");e.width=c.width;e.height=c.height;e.getContext("2d").drawImage(c,0,0,e.width,e.height);var g=null;try{g=e.toDataURL("image/png");var k=b(g)}catch(r){}g&&a._target.trigger("pasteImage",{blob:k,dataURL:g,width:c.width,height:c.height,originalEvent:f,
name:d});return a._target.trigger("pasteImageEnd")}}(this);c.onerror=function(b){return function(){b._target.trigger("pasteImageError",{message:"Failed to get image from: "+a,url:a});return b._target.trigger("pasteImageEnd")}}(this);return c.src=a};d.prototype._checkImagesInContainer=function(b){var c;var e=Math.floor(1E3*Math.random());var d=this._container.find("img");var g=0;for(c=d.length;g<c;g++){var h=d[g];h["_paste_marked_"+e]=!0}return setTimeout(function(c){return function(){var f;var d=
c._container.find("img");var g=0;for(f=d.length;g<f;g++)h=d[g],h["_paste_marked_"+e]||(b(h.src),a(h).remove());return c._target.trigger("_pasteCheckContainerDone")}}(this),1)};return d}()}).call(this);function DispDescCharNum(){var a=200-$("#EditDescription").val().length;$("#DescriptionCharNum").html(a)}function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}
function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}function setTweetImageSetting(a){setLocalStrage("upload_tweet_image",a)}function getTweetImageSetting(){return getLocalStrage("upload_tweet_image")?!0:!1}
function updateTweetButton(){$("#OptionTweet").prop("checked")?($("#ImageSwitch .OptionLabel").removeClass("disabled"),$("#ImageSwitch .onoffswitch").removeClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!1)):($("#ImageSwitch .OptionLabel").addClass("disabled"),$("#ImageSwitch .onoffswitch").addClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!0))}
function updateOneCushionButton(){$("#OptionOneCushion").prop("checked")?($("#R18Switch .OptionLabel").removeClass("disabled"),$("#R18Switch .onoffswitch").removeClass("disabled"),$("#OptionR18:checkbox").prop("disabled",!1)):($("#R18Switch .OptionLabel").addClass("disabled"),$("#R18Switch .onoffswitch").addClass("disabled"),$("#OptionR18:checkbox").prop("disabled",!0))}
function initUploadFile(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());updateOneCushionButton();updateTweetButton();multiFileUploader=new qq.FineUploader({element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,
b){this.first_file?(this.first_file=!1,this.setEndpoint("/f/UploadFileFirstF.jsp",a),console.log("UploadFileFirstF")):(this.setEndpoint("/f/UploadFileAppendF.jsp",a),console.log("UploadFileAppendF"));this.setParams({UID:this.user_id,IID:this.illust_id,REC:this.recent},a)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);1==this.tweet?$.ajax({type:"post",data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");
completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3))},onValidate:function(a){var b=this.getSubmittedSize(),e=this.getSubmittedNum();this.showTotalSize(b,e);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,e+1)},onStatusChange:function(a,b,e){this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};
multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var e="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(e="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(e)};multiFileUploader.total_size=52428800}
function UploadFile(a){if(multiFileUploader&&!(0>=multiFileUploader.getSubmittedNum())){var b=$("#EditCategory").val(),e=$.trim($("#EditDescription").val());e=e.substr(0,200);var h=$("#OptionRecent").prop("checked")?1:0,g=$("#OptionOneCushion").prop("checked")?2:0;0<g&&(g=$("#OptionR18").prop("checked")?4:2);var d=$("#OptionTweet").prop("checked")?1:0,c=$("#OptionImage").prop("checked")?1:0;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));
startMsg();console.log("start upload");$.ajaxSingle({type:"post",data:{UID:a,CAT:b,SAF:g,DES:e},url:"/f/UploadFileReferenceF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF");b&&b.content_id&&(0<b.content_id?(multiFileUploader.first_file=!0,multiFileUploader.user_id=a,multiFileUploader.illust_id=b.content_id,multiFileUploader.recent=h,multiFileUploader.tweet=d,multiFileUploader.tweet_image=c,multiFileUploader.uploadStoredFiles()):errorMsg())}})}}var g_strPasteMsg="";
function initUploadPaste(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());updateOneCushionButton();updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,
b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)})}function createPasteElm(a){var b=$("<div />").addClass("InputFile"),e=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);b.append(e).append(a);return b}
function initPasteElm(a){a.on("pasteImage",function(a,e){$(".OrgMessage",this).hide();$(".imgView",this).attr("src",e.dataURL).show()}).on("pasteImageError",function(a,e){e.url&&alert("error data : "+e.url)}).on("pasteText",function(a,e){})}function updatePasteNum(){strTotal="("+$(".InputFile").length+"/10)";$("#TotalSize").html(strTotal)}
function UploadPaste(a){var b=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&b++});console.log(b);if(!(0>=b)){startMsg();var e=$("#EditCategory").val(),h=$.trim($("#EditDescription").val());h=h.substr(0,200);var g=$("#OptionRecent").prop("checked")?1:0,d=$("#OptionOneCushion").prop("checked")?2:0;0<d&&(d=$("#OptionR18").prop("checked")?4:2);$("#OptionTweet").prop("checked");var c=$("#OptionImage").prop("checked")?1:0;setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));
$.ajaxSingle({type:"post",data:{UID:a,CAT:e,SAF:d,DES:h},url:"/f/UploadFileReferenceF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF",b.content_id);var d=!0;$(".imgView").each(function(){$(this).parent().addClass("Done");var c=$(this).attr("src").replace("data:image/png;base64,","");if(0>=c.length)return!0;d?(d=!1,$.ajax({type:"post",data:{UID:a,IID:b.content_id,REC:g,DATA:c},url:"/f/UploadPasteFirstF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteFirstF")}})):
$.ajax({type:"post",data:{UID:a,IID:b.content_id,DATA:c},url:"/f/UploadPasteAppendF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteAppendF")}})});$.ajax({type:"post",data:{UID:a,IID:b.content_id,IMG:c},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}})}});return!1}};
