var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,f,h){a instanceof String&&(a=String(a));for(var l=a.length,g=0;g<l;g++){var d=a[g];if(f.call(h,d,g,a))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,f,h){a!=Array.prototype&&a!=Object.prototype&&(a[f]=h.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,f,h,l){if(f){h=$jscomp.global;a=a.split(".");for(l=0;l<a.length-1;l++){var g=a[l];g in h||(h[g]={});h=h[g]}a=a[a.length-1];l=h[a];f=f(l);f!=l&&null!=f&&$jscomp.defineProperty(h,a,{configurable:!0,writable:!0,value:f})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,h){return $jscomp.findInternal(this,a,h).v}},"es6","es3");$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(a){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return g.mountNonInputable(a)._container};a.fn.pastableNonInputable=function(){var d;var b=0;for(d=this.length;b<d;b++){var c=this[b];c._pastable||a(c).is("textarea, input:text, [contenteditable]")||(g.mountNonInputable(c),c._pastable=!0)}return this};a.fn.pastableTextarea=function(){var d;var b=0;for(d=
this.length;b<d;b++){var c=this[b];c._pastable||a(c).is(":not(textarea, input:text)")||(g.mountTextarea(c),c._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var d;var b=0;for(d=this.length;b<d;b++){var c=this[b];c._pastable||a(c).is(":not([contenteditable])")||(g.mountContenteditable(c),c._pastable=!0)}return this};var f=function(a,b){var c,m,e;null==b&&(b=512);if(!(c=a.match(/^data:([^;]+);base64,(.+)$/)))return null;a=c[1];var d=atob(c[2]);c=[];for(e=0;e<d.length;){var p=d.slice(e,
e+b);var n=Array(p.length);for(m=0;m<p.length;)n[m]=p.charCodeAt(m),m++;n=new Uint8Array(n);c.push(n);e+=b}return new Blob(c,{type:a})};var h=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var l=function(d,b){var c=d.nodeName.toLowerCase();if("area"===c){b=d.parentNode;c=b.name;if(!d.href||!c||"map"!==b.nodeName.toLowerCase())return!1;d=a("img[usemap='#"+
c+"']");return 0<d.length&&d.is(":visible")}/^(input|select|textarea|button|object)$/.test(c)?(c=!d.disabled)&&(b=a(d).closest("fieldset")[0])&&(c=!b.disabled):c="a"===c?d.href||b:b;return(c=c||a(d).is("[contenteditable]"))&&a(d).is(":visible")};var g=function(){function d(b,c){this._container=b;this._target=c;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(a){return function(b){var c,d,e;a.originalEvent=null!==b.originalEvent?
b.originalEvent:null;a._paste_event_fired=!0;if(null!=(null!=(c=b.originalEvent)?c.clipboardData:void 0)){var k=b.originalEvent.clipboardData;if(k.items){var f=null;a.originalEvent.pastedTypes=[];var h=k.items;var m=0;for(d=h.length;m<d;m++)c=h[m],c.type.match(/^text\/(plain|rtf|html)/)&&a.originalEvent.pastedTypes.push(c.type);var g=k.items;m=d=0;for(h=g.length;d<h;m=++d){c=g[m];if(c.type.match(/^image\//)){k=new FileReader;k.onload=function(b){return a._handleImage(b.target.result,a.originalEvent,
f)};try{k.readAsDataURL(c.getAsFile())}catch(u){}b.preventDefault();break}if("text/plain"===c.type){if(0===m&&1<k.items.length&&k.items[1].type.match(/^image\//)){var l=!0;var r=k.items[1].type}c.getAsString(function(b){return l?(f=b,a._target.trigger("pasteText",{text:b,isFilename:!0,fileType:r,originalEvent:a.originalEvent})):a._target.trigger("pasteText",{text:b,originalEvent:a.originalEvent})})}"text/rtf"===c.type&&c.getAsString(function(b){return a._target.trigger("pasteTextRich",{text:b,originalEvent:a.originalEvent})});
"text/html"===c.type&&c.getAsString(function(b){return a._target.trigger("pasteTextHtml",{text:b,originalEvent:a.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(k.types,"text/plain")){var q=k.getData("Text");setTimeout(function(){return a._target.trigger("pasteText",{text:q,originalEvent:a.originalEvent})},1)}a._checkImagesInContainer(function(b){return a._handleImage(b,a.originalEvent)})}}if(k=window.clipboardData)if(null!=(e=q=k.getData("Text"))&&e.length)setTimeout(function(){a._target.trigger("pasteText",
{text:q,originalEvent:a.originalEvent});return a._target.trigger("_pasteCheckContainerDone")},1);else{k=k.files;e=0;for(c=k.length;e<c;e++)b=k[e],a._handleImage(URL.createObjectURL(b),a.originalEvent);a._checkImagesInContainer(function(a){})}return null}}(this))}d.prototype._target=null;d.prototype._container=null;d.mountNonInputable=function(b){var c=new d(h().appendTo(b),b);a(b).on("click",function(a){return function(a){if(!l(a.target,!1)&&!window.getSelection().toString())return c._container.focus()}}(this));
c._container.on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return c._container.on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};d.mountTextarea=function(b){var c,f;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(c=Object.getOwnPropertyDescriptor)&&null!=(f=c.call(Object,DataTransfer.prototype,"items"))&&f.get)return this.mountContenteditable(b);var e=new d(h().insertBefore(b),
b);var g=!1;a(b).on("keyup",function(a){var b;if(17===(b=a.keyCode)||224===b)g=!1;return null});a(b).on("keydown",function(c){var d;if(17===(d=c.keyCode)||224===d)g=!0;null!=c.ctrlKey&&null!=c.metaKey&&(g=c.ctrlKey||c.metaKey);g&&86===c.keyCode&&(e._textarea_focus_stolen=!0,e._container.focus(),e._paste_event_fired=!1,setTimeout(function(c){return function(){if(!e._paste_event_fired)return a(b).focus(),e._textarea_focus_stolen=!1}}(this),1));return null});a(b).on("paste",function(a){return function(){}}(this));
a(b).on("focus",function(c){return function(){if(!e._textarea_focus_stolen)return a(b).addClass("pastable-focus")}}(this));a(b).on("blur",function(c){return function(){if(!e._textarea_focus_stolen)return a(b).removeClass("pastable-focus")}}(this));a(e._target).on("_pasteCheckContainerDone",function(c){return function(){a(b).focus();return e._textarea_focus_stolen=!1}}(this));return a(e._target).on("pasteText",function(c){return function(c,d){var e=a(b).prop("selectionStart");var f=a(b).prop("selectionEnd");
c=a(b).val();a(b).val(""+c.slice(0,e)+d.text+c.slice(f));a(b)[0].setSelectionRange(e+d.text.length,e+d.text.length);return a(b).trigger("change")}}(this))};d.mountContenteditable=function(b){new d(b,b);a(b).on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return a(b).on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};d.prototype._handleImage=function(a,c,d){if(a.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var b=new Image;b.crossOrigin="anonymous";b.onload=function(a){return function(){var e=document.createElement("canvas");e.width=b.width;e.height=b.height;e.getContext("2d").drawImage(b,0,0,e.width,e.height);var g=null;try{g=e.toDataURL("image/png");var k=f(g)}catch(t){}g&&a._target.trigger("pasteImage",{blob:k,dataURL:g,width:b.width,height:b.height,originalEvent:c,
name:d});return a._target.trigger("pasteImageEnd")}}(this);b.onerror=function(b){return function(){b._target.trigger("pasteImageError",{message:"Failed to get image from: "+a,url:a});return b._target.trigger("pasteImageEnd")}}(this);return b.src=a};d.prototype._checkImagesInContainer=function(b){var c;var d=Math.floor(1E3*Math.random());var e=this._container.find("img");var f=0;for(c=e.length;f<c;f++){var g=e[f];g["_paste_marked_"+d]=!0}return setTimeout(function(c){return function(){var e;var f=
c._container.find("img");var h=0;for(e=f.length;h<e;h++)g=f[h],g["_paste_marked_"+d]||(b(g.src),a(g).remove());return c._target.trigger("_pasteCheckContainerDone")}}(this),1)};return d}()}).call(this);function DispDescCharNum(){var a=200-$("#EditDescription").val().length;$("#DescriptionCharNum").html(a)}function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}
function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}
function initUploadFile(){$("#OptionTweet").prop("checked",getTweetSetting());$("#file_thumb").on("change",function(){DispMsgStatic("loading...");var a=$(this).prop("files")[0];this.files.length&&a.type.match("image.*")?EXIF.getData(a,function(){var f=a.exifdata.Orientation;(new MegaPixImage(a)).render($("#imgView")[0],{orientation:f});$(".OrgMessage").hide();$("#imgView").css("display","block");HideMsgStatic()}):HideMsgStatic()})}
function initUploadPaste(){$("#OptionTweet").prop("checked",getTweetSetting());$("#InputFile").pastableNonInputable();$("#InputFile").on("pasteImage",function(a,f){$(".OrgMessage").hide();$("#imgView").attr("src",f.dataURL).show()}).on("pasteImageError",function(a,f){f.url&&alert("error data : "+f.url)}).on("pasteText",function(a,f){})};
