var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var g=a.length,e=0;e<g;e++){var h=a[e];if(c.call(b,h,e,a))return{i:e,v:h}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,g){if(c){b=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var e=a[g];e in b||(b[e]={});b=b[e]}a=a[a.length-1];g=b[a];c=c(g);c!=g&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var multiFileUploader=null;$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(a){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return e.mountNonInputable(a)._container};a.fn.pastableNonInputable=function(){var c;var d=0;for(c=this.length;d<c;d++){var b=this[d];b._pastable||a(b).is("textarea, input:text, [contenteditable]")||(e.mountNonInputable(b),b._pastable=!0)}return this};a.fn.pastableTextarea=function(){var b;var d=0;for(b=
this.length;d<b;d++){var c=this[d];c._pastable||a(c).is(":not(textarea, input:text)")||(e.mountTextarea(c),c._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var c;var d=0;for(c=this.length;d<c;d++){var b=this[d];b._pastable||a(b).is(":not([contenteditable])")||(e.mountContenteditable(b),b._pastable=!0)}return this};var c=function(a,b){var c,d,f;null==b&&(b=512);if(!(c=a.match(/^data:([^;]+);base64,(.+)$/)))return null;a=c[1];var k=atob(c[2]);c=[];for(f=0;f<k.length;){var n=k.slice(f,
f+b);var h=Array(n.length);for(d=0;d<n.length;)h[d]=n.charCodeAt(d),d++;h=new Uint8Array(h);c.push(h);f+=b}return new Blob(c,{type:a})};var b=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var g=function(c,b){var d=c.nodeName.toLowerCase();if("area"===d){b=c.parentNode;d=b.name;if(!c.href||!d||"map"!==b.nodeName.toLowerCase())return!1;c=a("img[usemap='#"+
d+"']");return 0<c.length&&c.is(":visible")}/^(input|select|textarea|button|object)$/.test(d)?(d=!c.disabled)&&(b=a(c).closest("fieldset")[0])&&(d=!b.disabled):d="a"===d?c.href||b:b;return(d=d||a(c).is("[contenteditable]"))&&a(c).is(":visible")};var e=function(){function e(c,b){this._container=c;this._target=b;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(a){return function(c){var b,d,e;a.originalEvent=null!==c.originalEvent?
c.originalEvent:null;a._paste_event_fired=!0;if(null!=(null!=(b=c.originalEvent)?b.clipboardData:void 0)){var f=c.originalEvent.clipboardData;if(f.items){var g=null;a.originalEvent.pastedTypes=[];var h=f.items;var l=0;for(d=h.length;l<d;l++)b=h[l],b.type.match(/^text\/(plain|rtf|html)/)&&a.originalEvent.pastedTypes.push(b.type);var m=f.items;l=d=0;for(h=m.length;d<h;l=++d){b=m[l];if(b.type.match(/^image\//)){f=new FileReader;f.onload=function(b){return a._handleImage(b.target.result,a.originalEvent,
g)};try{f.readAsDataURL(b.getAsFile())}catch(u){}c.preventDefault();break}if("text/plain"===b.type){if(0===l&&1<f.items.length&&f.items[1].type.match(/^image\//)){var q=!0;var r=f.items[1].type}b.getAsString(function(b){return q?(g=b,a._target.trigger("pasteText",{text:b,isFilename:!0,fileType:r,originalEvent:a.originalEvent})):a._target.trigger("pasteText",{text:b,originalEvent:a.originalEvent})})}"text/rtf"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextRich",{text:b,originalEvent:a.originalEvent})});
"text/html"===b.type&&b.getAsString(function(b){return a._target.trigger("pasteTextHtml",{text:b,originalEvent:a.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(f.types,"text/plain")){var p=f.getData("Text");setTimeout(function(){return a._target.trigger("pasteText",{text:p,originalEvent:a.originalEvent})},1)}a._checkImagesInContainer(function(b){return a._handleImage(b,a.originalEvent)})}}if(f=window.clipboardData)if(null!=(e=p=f.getData("Text"))&&e.length)setTimeout(function(){a._target.trigger("pasteText",
{text:p,originalEvent:a.originalEvent});return a._target.trigger("_pasteCheckContainerDone")},1);else{f=f.files;e=0;for(b=f.length;e<b;e++)c=f[e],a._handleImage(URL.createObjectURL(c),a.originalEvent);a._checkImagesInContainer(function(a){})}return null}}(this))}e.prototype._target=null;e.prototype._container=null;e.mountNonInputable=function(c){var d=new e(b().appendTo(c),c);a(c).on("click",function(a){return function(a){if(!g(a.target,!1)&&!window.getSelection().toString())return d._container.focus()}}(this));
d._container.on("focus",function(b){return function(){return a(c).addClass("pastable-focus")}}(this));return d._container.on("blur",function(b){return function(){return a(c).removeClass("pastable-focus")}}(this))};e.mountTextarea=function(c){var d,g;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(d=Object.getOwnPropertyDescriptor)&&null!=(g=d.call(Object,DataTransfer.prototype,"items"))&&g.get)return this.mountContenteditable(c);var f=new e(b().insertBefore(c),
c);var k=!1;a(c).on("keyup",function(a){var c;if(17===(c=a.keyCode)||224===c)k=!1;return null});a(c).on("keydown",function(b){var d;if(17===(d=b.keyCode)||224===d)k=!0;null!=b.ctrlKey&&null!=b.metaKey&&(k=b.ctrlKey||b.metaKey);k&&86===b.keyCode&&(f._textarea_focus_stolen=!0,f._container.focus(),f._paste_event_fired=!1,setTimeout(function(b){return function(){if(!f._paste_event_fired)return a(c).focus(),f._textarea_focus_stolen=!1}}(this),1));return null});a(c).on("paste",function(a){return function(){}}(this));
a(c).on("focus",function(b){return function(){if(!f._textarea_focus_stolen)return a(c).addClass("pastable-focus")}}(this));a(c).on("blur",function(b){return function(){if(!f._textarea_focus_stolen)return a(c).removeClass("pastable-focus")}}(this));a(f._target).on("_pasteCheckContainerDone",function(b){return function(){a(c).focus();return f._textarea_focus_stolen=!1}}(this));return a(f._target).on("pasteText",function(b){return function(b,d){var f=a(c).prop("selectionStart");var e=a(c).prop("selectionEnd");
b=a(c).val();a(c).val(""+b.slice(0,f)+d.text+b.slice(e));a(c)[0].setSelectionRange(f+d.text.length,f+d.text.length);return a(c).trigger("change")}}(this))};e.mountContenteditable=function(b){new e(b,b);a(b).on("focus",function(c){return function(){return a(b).addClass("pastable-focus")}}(this));return a(b).on("blur",function(c){return function(){return a(b).removeClass("pastable-focus")}}(this))};e.prototype._handleImage=function(a,b,e){if(a.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var d=new Image;d.crossOrigin="anonymous";d.onload=function(a){return function(){var f=document.createElement("canvas");f.width=d.width;f.height=d.height;f.getContext("2d").drawImage(d,0,0,f.width,f.height);var g=null;try{g=f.toDataURL("image/png");var h=c(g)}catch(t){}g&&a._target.trigger("pasteImage",{blob:h,dataURL:g,width:d.width,height:d.height,originalEvent:b,
name:e});return a._target.trigger("pasteImageEnd")}}(this);d.onerror=function(b){return function(){b._target.trigger("pasteImageError",{message:"Failed to get image from: "+a,url:a});return b._target.trigger("pasteImageEnd")}}(this);return d.src=a};e.prototype._checkImagesInContainer=function(b){var c;var d=Math.floor(1E3*Math.random());var e=this._container.find("img");var g=0;for(c=e.length;g<c;g++){var h=e[g];h["_paste_marked_"+d]=!0}return setTimeout(function(c){return function(){var e;var f=
c._container.find("img");var g=0;for(e=f.length;g<e;g++)h=f[g],h["_paste_marked_"+d]||(b(h.src),a(h).remove());return c._target.trigger("_pasteCheckContainerDone")}}(this),1)};return e}()}).call(this);function DispDescCharNum(){var a=200-$("#EditDescription").val().length;$("#DescriptionCharNum").html(a)}function DispTagListCharNum(){var a=100-$("#EditTagList").val().length;$("#EditTagListCharNum").html(a)}
function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}function setTweetImageSetting(a){setLocalStrage("upload_tweet_image",a)}function getTweetImageSetting(){return getLocalStrage("upload_tweet_image")?!0:!1}function setLastCategorySetting(a){setLocalStrage("last_category",a)}
function getLastCategorySetting(){return getLocalStrage("last_category")}function updateTweetButton(){$("#OptionTweet").prop("checked")?($("#ImageSwitch .OptionLabel").removeClass("disabled"),$("#ImageSwitch .onoffswitch").removeClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!1)):($("#ImageSwitch .OptionLabel").addClass("disabled"),$("#ImageSwitch .onoffswitch").addClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!0))}
function updatePublish(){var a=parseInt($("#EditPublish").val(),10),c=[$("#ItemTwitterList"),$("#ItemPassword"),$("#ItemTimeLimited")];if(4==a||10==a||11==a){var b=null,g=null;switch(a){case 4:g=$("#ItemPassword");break;case 10:g=$("#ItemTwitterList");break;case 11:g=$("#ItemTimeLimited")}for(var e=0;e<c.length;e++){var h=c[e];if(h.is(":visible")){b=h;break}}null==b?g.slideDown(300):b.slideUp(300,function(){g.delay(150).slideDown(300)});11==a&&(a=new Date,a.setMinutes(30*Math.floor((a.getMinutes()+
45)/30)),$(".EditTimeLimited").flatpickr({enableTime:!0,dateFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,minDate:a}))}else for(e=0;e<c.length;e++)h=c[e],h.is(":visible")&&h.slideUp(300)}
function initUploadFile(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();multiFileUploader=new qq.FineUploader({element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg",
"jpg","gif","png"],itemLimit:200,sizeLimit:2E7,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(a,b){this.first_file?(this.first_file=!1,this.setEndpoint("/f/UploadFileFirstF.jsp",a),console.log("UploadFileFirstF")):(this.setEndpoint("/f/UploadFileAppendF.jsp",a),console.log("UploadFileAppendF"));this.setParams({UID:this.user_id,IID:this.illust_id,REC:this.recent},a)},onAllComplete:function(a,b){console.log("onAllComplete",a,b,this.tweet);1==this.tweet?$.ajax({type:"post",
data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}}):(completeMsg(),setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3))},onValidate:function(a){var b=this.getSubmittedSize(),c=this.getSubmittedNum();this.showTotalSize(b,c);b+=a.size;if(b>this.total_size)return!1;this.showTotalSize(b,c+1)},onStatusChange:function(a,
b,g){this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var a=this.getUploads({status:qq.status.SUBMITTED}),b=0;$.each(a,function(){b+=this.size});return b};multiFileUploader.showTotalSize=function(a,b){var c="(jpeg|png|gif, 200files, total 50MByte)";0<a&&(c="("+b+"/200,  "+Math.ceil((multiFileUploader.total_size-a)/1024)+" KByte)",
$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(c)};multiFileUploader.total_size=52428800}
function UploadFile(a){if(multiFileUploader&&!(0>=multiFileUploader.getSubmittedNum())){var c=$("#EditCategory").val(),b=$.trim($("#EditDescription").val());b=b.substr(0,200);var g=$.trim($("#EditTagList").val());g=g.substr(0,100);var e=$("#EditPublish").val(),h=$("#EditPassword").val(),d=$("#OptionRecent").prop("checked")?1:0,l=$("#OptionTweet").prop("checked")?1:0,m=$("#OptionImage").prop("checked")?1:0,f=null,k=$("#EditTimeLimitedStart").val(),n=$("#EditTimeLimitedEnd").val();10==e&&(f=$("#EditTwitterList").val());
if(11==e){if(""==k||""==n){dateTimeEmptyMsg();return}if(Date.parse(k)<Date.now()){dateTimePastMsg();return}if(Date.parse(k)>Date.parse(n)){dateTimeReverseMsg();return}}setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(c);99==e&&(d=2,l=0);startMsg();console.log("start upload");$.ajaxSingle({type:"post",data:{UID:a,CAT:c,DES:b,TAG:g,PID:e,PPW:h,PLD:f,PST:k,PED:n},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF");
b&&b.content_id&&(0<b.content_id?(multiFileUploader.first_file=!0,multiFileUploader.user_id=a,multiFileUploader.illust_id=b.content_id,multiFileUploader.recent=d,multiFileUploader.tweet=l,multiFileUploader.tweet_image=m,multiFileUploader.uploadStoredFiles()):errorMsg())}})}}var g_strPasteMsg="";
function initUploadPaste(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){console.log($(this).val());$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton();g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),
$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)})}
function createPasteElm(a){var c=$("<div />").addClass("InputFile"),b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function createPasteListItem(a,c){c=$("<li />").addClass("InputFile").attr("id",c);var b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function createPasteListItem(a,c){c=$("<li />").addClass("InputFile").attr("id",c);var b=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);c.append(b).append(a);return c}
function initPasteElm(a){a.on("pasteImage",function(a,b){$(".OrgMessage",this).hide();$(".imgView",this).attr("src",b.dataURL).show()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){})}function updatePasteNum(){strTotal="("+$(".InputFile").length+"/10)";$("#TotalSize").html(strTotal)}
function UploadPaste(a){var c=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&c++});console.log(c);if(!(0>=c)){var b=$("#EditCategory").val(),g=$.trim($("#EditDescription").val());g=g.substr(0,200);var e=$.trim($("#EditTagList").val());e=e.substr(0,100);var h=$("#EditPublish").val(),d=$("#EditPassword").val(),l=$("#OptionRecent").prop("checked")?1:0,m=$("#OptionTweet").prop("checked")?1:0,f=$("#OptionImage").prop("checked")?1:0,k=null;10==h&&(k=$("#EditTwitterList").val());setTweetSetting($("#OptionTweet").prop("checked"));
setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(b);99==h&&(l=2,m=0);startMsg();$.ajaxSingle({type:"post",data:{UID:a,CAT:b,DES:g,TAG:e,PID:h,PPW:d,PLD:k,ED:1},url:"/f/UploadFileRefTwitterF.jsp",dataType:"json",success:function(b){console.log("UploadFileReferenceF",b.content_id);var c=!0;$(".imgView").each(function(){$(this).parent().addClass("Done");var d=$(this).attr("src").replace("data:image/png;base64,","");if(0>=d.length)return!0;c?(c=!1,$.ajax({type:"post",data:{UID:a,
IID:b.content_id,REC:l,DATA:d},url:"/f/UploadPasteFirstF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteFirstF")}})):$.ajax({type:"post",data:{UID:a,IID:b.content_id,DATA:d},url:"/f/UploadPasteAppendF.jsp",dataType:"json",async:!1,success:function(a){console.log("UploadPasteAppendF")}})});1==m?$.ajax({type:"post",data:{UID:a,IID:b.content_id,IMG:f},url:"/f/UploadFileTweetF.jsp",dataType:"json",success:function(a){console.log("UploadFileTweetF");completeMsg();setTimeout(function(){location.href=
"/MyHomePcV.jsp"},1E3)}}):setTimeout(function(){location.href="/MyHomePcV.jsp"},1E3)}});return!1}};
