var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,g=0;g<e;g++){var f=a[g];if(b.call(c,f,g,a))return{i:g,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))return;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var g=a.split(".");a=1===g.length;e=g[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<g.length-1;f++){var d=g[f];if(!(d in e))return;e=e[d]}g=g[g.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[g]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+g,g=
$jscomp.propertyToPolyfillSymbol[g],$jscomp.defineProperty(e,g,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");var multiFileUploader=null;$.ajaxSetup({cache:!1});
(function(){var a=window.jQuery;a.paste=function(f){"undefined"!==typeof console&&null!==console&&console.log("DEPRECATED: This method is deprecated. Please use $.fn.pastableNonInputable() instead.");return g.mountNonInputable(f)._container};a.fn.pastableNonInputable=function(){var f;var d=0;for(f=this.length;d<f;d++){var h=this[d];h._pastable||a(h).is("textarea, input:text, [contenteditable]")||(g.mountNonInputable(h),h._pastable=!0)}return this};a.fn.pastableTextarea=function(){var f;var d=0;for(f=
this.length;d<f;d++){var h=this[d];h._pastable||a(h).is(":not(textarea, input:text)")||(g.mountTextarea(h),h._pastable=!0)}return this};a.fn.pastableContenteditable=function(){var f;var d=0;for(f=this.length;d<f;d++){var h=this[d];h._pastable||a(h).is(":not([contenteditable])")||(g.mountContenteditable(h),h._pastable=!0)}return this};var b=function(f,d){var h,k,l;null==d&&(d=512);if(!(h=f.match(/^data:([^;]+);base64,(.+)$/)))return null;f=h[1];var n=atob(h[2]);h=[];for(l=0;l<n.length;){var m=n.slice(l,
l+d);var q=Array(m.length);for(k=0;k<m.length;)q[k]=m.charCodeAt(k),k++;q=new Uint8Array(q);h.push(q);l+=d}return new Blob(h,{type:f})};var c=function(){return a(document.createElement("div")).attr("contenteditable",!0).attr("aria-hidden",!0).attr("tabindex",-1).css({width:1,height:1,position:"fixed",left:-100,overflow:"hidden",opacity:1E-17})};var e=function(f,d){var h=f.nodeName.toLowerCase();if("area"===h){d=f.parentNode;h=d.name;if(!f.href||!h||"map"!==d.nodeName.toLowerCase())return!1;f=a("img[usemap='#"+
h+"']");return 0<f.length&&f.is(":visible")}/^(input|select|textarea|button|object)$/.test(h)?(h=!f.disabled)&&(d=a(f).closest("fieldset")[0])&&(h=!d.disabled):h="a"===h?f.href||d:d;return(h=h||a(f).is("[contenteditable]"))&&a(f).is(":visible")};var g=function(){function f(d,h){this._container=d;this._target=h;this._container=a(this._container);this._target=a(this._target).addClass("pastable");this._container.on("paste",function(k){return function(l){var n,m,q;k.originalEvent=null!==l.originalEvent?
l.originalEvent:null;k._paste_event_fired=!0;if(null!=(null!=(n=l.originalEvent)?n.clipboardData:void 0)){var p=l.originalEvent.clipboardData;if(p.items){var r=null;k.originalEvent.pastedTypes=[];var t=p.items;var v=0;for(m=t.length;v<m;v++)n=t[v],n.type.match(/^text\/(plain|rtf|html)/)&&k.originalEvent.pastedTypes.push(n.type);var u=p.items;v=m=0;for(t=u.length;m<t;v=++m){n=u[v];if(n.type.match(/^image\//)){p=new FileReader;p.onload=function(w){return k._handleImage(w.target.result,k.originalEvent,
r)};try{p.readAsDataURL(n.getAsFile())}catch(w){}l.preventDefault();break}if("text/plain"===n.type){if(0===v&&1<p.items.length&&p.items[1].type.match(/^image\//)){var y=!0;var x=p.items[1].type}n.getAsString(function(w){return y?(r=w,k._target.trigger("pasteText",{text:w,isFilename:!0,fileType:x,originalEvent:k.originalEvent})):k._target.trigger("pasteText",{text:w,originalEvent:k.originalEvent})})}"text/rtf"===n.type&&n.getAsString(function(w){return k._target.trigger("pasteTextRich",{text:w,originalEvent:k.originalEvent})});
"text/html"===n.type&&n.getAsString(function(w){return k._target.trigger("pasteTextHtml",{text:w,originalEvent:k.originalEvent})})}}else{if(-1!==Array.prototype.indexOf.call(p.types,"text/plain")){var z=p.getData("Text");setTimeout(function(){return k._target.trigger("pasteText",{text:z,originalEvent:k.originalEvent})},1)}k._checkImagesInContainer(function(w){return k._handleImage(w,k.originalEvent)})}}if(p=window.clipboardData)if(null!=(q=z=p.getData("Text"))&&q.length)setTimeout(function(){k._target.trigger("pasteText",
{text:z,originalEvent:k.originalEvent});return k._target.trigger("_pasteCheckContainerDone")},1);else{p=p.files;q=0;for(n=p.length;q<n;q++)l=p[q],k._handleImage(URL.createObjectURL(l),k.originalEvent);k._checkImagesInContainer(function(w){})}return null}}(this))}f.prototype._target=null;f.prototype._container=null;f.mountNonInputable=function(d){var h=new f(c().appendTo(d),d);a(d).on("click",function(k){return function(l){if(!e(l.target,!1)&&!window.getSelection().toString())return h._container.focus()}}(this));
h._container.on("focus",function(k){return function(){return a(d).addClass("pastable-focus")}}(this));return h._container.on("blur",function(k){return function(){return a(d).removeClass("pastable-focus")}}(this))};f.mountTextarea=function(d){var h,k;if("undefined"!==typeof DataTransfer&&null!==DataTransfer&&DataTransfer.prototype&&null!=(h=Object.getOwnPropertyDescriptor)&&null!=(k=h.call(Object,DataTransfer.prototype,"items"))&&k.get)return this.mountContenteditable(d);var l=new f(c().insertBefore(d),
d);var n=!1;a(d).on("keyup",function(m){var q;if(17===(q=m.keyCode)||224===q)n=!1;return null});a(d).on("keydown",function(m){var q;if(17===(q=m.keyCode)||224===q)n=!0;null!=m.ctrlKey&&null!=m.metaKey&&(n=m.ctrlKey||m.metaKey);n&&86===m.keyCode&&(l._textarea_focus_stolen=!0,l._container.focus(),l._paste_event_fired=!1,setTimeout(function(p){return function(){if(!l._paste_event_fired)return a(d).focus(),l._textarea_focus_stolen=!1}}(this),1));return null});a(d).on("paste",function(m){return function(){}}(this));
a(d).on("focus",function(m){return function(){if(!l._textarea_focus_stolen)return a(d).addClass("pastable-focus")}}(this));a(d).on("blur",function(m){return function(){if(!l._textarea_focus_stolen)return a(d).removeClass("pastable-focus")}}(this));a(l._target).on("_pasteCheckContainerDone",function(m){return function(){a(d).focus();return l._textarea_focus_stolen=!1}}(this));return a(l._target).on("pasteText",function(m){return function(q,p){var r=a(d).prop("selectionStart");var t=a(d).prop("selectionEnd");
q=a(d).val();a(d).val(""+q.slice(0,r)+p.text+q.slice(t));a(d)[0].setSelectionRange(r+p.text.length,r+p.text.length);return a(d).trigger("change")}}(this))};f.mountContenteditable=function(d){new f(d,d);a(d).on("focus",function(h){return function(){return a(d).addClass("pastable-focus")}}(this));return a(d).on("blur",function(h){return function(){return a(d).removeClass("pastable-focus")}}(this))};f.prototype._handleImage=function(d,h,k){if(d.match(/^webkit\-fake\-url:\/\//))return this._target.trigger("pasteImageError",
{message:"You are trying to paste an image in Safari, however we are unable to retieve its data."});this._target.trigger("pasteImageStart");var l=new Image;l.crossOrigin="anonymous";l.onload=function(n){return function(){var m=document.createElement("canvas");m.width=l.width;m.height=l.height;m.getContext("2d").drawImage(l,0,0,m.width,m.height);var q=null;try{q=m.toDataURL("image/png");var p=b(q)}catch(r){}q&&n._target.trigger("pasteImage",{blob:p,dataURL:q,width:l.width,height:l.height,originalEvent:h,
name:k});return n._target.trigger("pasteImageEnd")}}(this);l.onerror=function(n){return function(){n._target.trigger("pasteImageError",{message:"Failed to get image from: "+d,url:d});return n._target.trigger("pasteImageEnd")}}(this);return l.src=d};f.prototype._checkImagesInContainer=function(d){var h;var k=Math.floor(1E3*Math.random());var l=this._container.find("img");var n=0;for(h=l.length;n<h;n++){var m=l[n];m["_paste_marked_"+k]=!0}return setTimeout(function(q){return function(){var p;var r=
q._container.find("img");var t=0;for(p=r.length;t<p;t++)m=r[t],m["_paste_marked_"+k]||(d(m.src),a(m).remove());return q._target.trigger("_pasteCheckContainerDone")}}(this),1)};return f}()}).call(this);function DispTagListCharNum(){var a=100-$("#EditTagList").val().length;$("#EditTagListCharNum").html(a)}function OnChangeTab(a){setCookie("MOD",a);window.location.href=0==a?"/UploadFilePcV.jsp":"/UploadPastePcV.jsp"}function setTweetSetting(a){setLocalStrage("upload_tweet",a)}
function getTweetSetting(){return getLocalStrage("upload_tweet")?!0:!1}function setTweetImageSetting(a){setLocalStrage("upload_tweet_image",a)}function getTweetImageSetting(){return getLocalStrage("upload_tweet_image")?!0:!1}function setLastCategorySetting(a){setLocalStrage("last_category",a)}function getLastCategorySetting(){return getLocalStrage("last_category")}function comparePublishDate(a,b){return null==a&&null==b?!1:null==a&&null==b?!0:a.substr(0,16)===b.substr(0,16)}
function checkPublishDatetime(a,b,c,e,g){e=void 0===e?null:e;g=void 0===g?null:g;if(""==a||""==b)return dateTimeEmptyMsg(),!1;if(Date.parse(a)>Date.parse(b))return dateTimeReverseMsg(),!1;if(c&&null!=e&&null!=g){if(c=comparePublishDate(e,a),g=comparePublishDate(g,b),!c||!g)if(!c){if(Date.parse(a)<Date.now())return dateTimePastMsg(),!1}else if(!g&&Date.parse(b)<Date.now())return dateTimePastMsg(),!1}else if(Date.parse(a)<Date.now()||Date.parse(b)<Date.now())return dateTimePastMsg(),!1;return!0}
function updateTweetButton(){var a=$("#OptionTweet").prop("checked");$("#ImageSwitc").length&&(a?($("#ImageSwitch .OptionLabel").removeClass("disabled"),$("#ImageSwitch .onoffswitch").removeClass("disabled"),$("#OptionImage:checkbox").prop("disabled",!1),$("#DeleteTweetSwitch .OptionLabel").removeClass("disabled"),$("#DeleteTweetSwitch .onoffswitch").removeClass("disabled"),$("#OptionDeleteTweet:checkbox").prop("disabled",!1)):($("#ImageSwitch .OptionLabel").addClass("disabled"),$("#ImageSwitch .onoffswitch").addClass("disabled"),
$("#OptionImage:checkbox").prop("disabled",!0),$("#DeleteTweetSwitch .OptionLabel").addClass("disabled"),$("#DeleteTweetSwitch .onoffswitch").addClass("disabled"),$("#OptionDeleteTweet:checkbox").prop("disabled",!0)))}function initStartDatetime(a){$("#EditTimeLimitedStart").flatpickr({enableTime:!0,dateFormat:"Z",altInput:!0,altFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,defaultDate:a})}
function initEndDatetime(a){$("#EditTimeLimitedEnd").flatpickr({enableTime:!0,dateFormat:"Z",altInput:!0,altFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,defaultDate:a})}
function updateOptionLimitedTimePublish(){var a=$("#ItemTimeLimitedVal");$("#OptionLimitedTimePublish").prop("checked")?a.slideDown(300,function(){$.each(["#EditTimeLimitedStart","#EditTimeLimitedEnd"],function(b,c){if(0>$(c)[0].classList.value.indexOf("flatpickr-input")){b=new Date;b.setSeconds(0);var e=new Date;e.setMinutes(30*Math.floor((e.getMinutes()-30)/30));$(c).flatpickr({enableTime:!0,dateFormat:"Z",altInput:!0,altFormat:"Y/m/d H:i",time_24hr:!0,minuteIncrement:30,minDate:e,defaultDate:b})}})}):
a.slideUp(300)}function updateAreaLimitedTimePublish(a){var b=$("#ItemTimeLimitedFlg"),c=$("#ItemTimeLimitedVal");99!=a?b.slideDown(300,function(){updateOptionLimitedTimePublish()}):$("#OptionLimitedTimePublish").prop("checked")?c.slideUp(300,function(){b.slideUp(300)}):b.slideUp(300)}
function udpateMyTwitterList(){function a(){b||(0<$("#EditTwitterList").children().length?b=!0:(b=!0,$("#TwitterListLoading").hide(),0!=c.result||0==c.result&&0==c.twitter_open_list.length?($("#TwitterListNotFound").show(),$("#EditTwitterList").hide(),-102==c.result?twtterListRateLimiteExceededMsg():-103==c.result?twtterListInvalidTokenMsg():0>c.result&&twtterListOtherErrMsg()):($("#TwitterListNotFound").hide(),$("#EditTwitterList").show(),c.twitter_open_list.forEach(function(e,g,f){$("#EditTwitterList").append('<option value="'+
e.id+'">'+e.name+"</option>")}))))}var b=!1,c=null;return function(e){null!=c?a():$.ajax({type:"post",data:{ID:e},url:"/f/TwitterMyListF.jsp",dataType:"json",success:function(g){c=g;a()}})}}var updateMyTwitterListF=udpateMyTwitterList();
function updatePublish(a){var b=parseInt($("#EditPublish").val(),10);updateAreaLimitedTimePublish(b);var c=[$("#ItemTwitterList"),$("#ItemPassword")];if(4==b||10==b||11==b){var e=null,g=null;switch(b){case 4:g=$("#ItemPassword");break;case 10:g=$("#ItemTwitterList")}for(var f=0;f<c.length;f++){var d=c[f];if(d.is(":visible")){e=d;break}}null==e?g.slideDown(300):e.slideUp(300,function(){g.delay(150).slideDown(300)});10==b&&updateMyTwitterListF(a)}else for(f=0;f<c.length;f++)d=c[f],d.is(":visible")&&
d.slideUp(300)}function tweetSucceeded(a){if(null!=a)if(0<=a)completeMsg(),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3);else{var b=5E3;-103==a||-203==a?twtterTweetInvalidTokenMsg():-102==a?twtterTweetRateLimitMsg():-104==a?twtterTweetTooMuchMsg():twtterTweetOtherErrMsg(a);setTimeout(function(){location.href="/MyIllustListPcV.jsp"},b)}else twtterTweetOtherErrMsg(a),setTimeout(function(){location.href="/MyIllustListPcV.jsp"},b)}
function initUploadFile(a,b){multiFileUploader=new qq.FineUploader({element:document.getElementById("file-drop-area"),autoUpload:!1,button:document.getElementById("TimeLineAddImage"),maxConnections:1,validation:{allowedExtensions:["jpeg","jpg","gif","png"],itemLimit:a,sizeLimit:1048576*b,stopOnFirstInvalidFile:!1},retry:{enableAuto:!1},callbacks:{onUpload:function(c,e){this.first_file?(this.first_file=!1,this.setEndpoint("/api/UploadFileFirstF.jsp",c),console.log("UploadFileFirstF")):(this.setEndpoint("/api/UploadFileAppendF.jsp",
c),console.log("UploadFileAppendF"));this.setParams({UID:this.user_id,IID:this.illust_id,PID:this.publish_id,REC:this.recent},c)},onAllComplete:function(c,e){console.log("onAllComplete",c,e,this.tweet);1==this.tweet?$.ajax({type:"post",data:{UID:this.user_id,IID:this.illust_id,IMG:this.tweet_image},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(g){tweetSucceeded(g.result)}}):(completeMsg(),setTimeout(onCompleteUpload,1E3))},onValidate:function(c){var e=this.getSubmittedSize(),g=
this.getSubmittedNum();this.showTotalSize(e,g);e+=c.size;if(e>this.total_size)return!1;this.showTotalSize(e,g+1)},onStatusChange:function(c,e,g){this.showTotalSize(this.getSubmittedSize(),this.getSubmittedNum())}}});multiFileUploader.getSubmittedNum=function(){return this.getUploads({status:qq.status.SUBMITTED}).length};multiFileUploader.getSubmittedSize=function(){var c=this.getUploads({status:qq.status.SUBMITTED}),e=0;$.each(c,function(){e+=this.size});return e};multiFileUploader.showTotalSize=
function(c,e){var g="(jpeg|png|gif, "+a+"files, total "+b+"MByte)";0<c&&(g="("+e+"/"+a+"files "+Math.ceil(c/1024/1024)+"/"+b+"MByte)",$("#TimeLineAddImage").removeClass("Light"),completeAddFile());$("#TotalSize").html(g)};multiFileUploader.total_size=52428800}function getPublishDateTime(a){return""==a?"":(new Date(a)).toISOString()}function getLimitedTimeFlg(a,b){return 99==$("#"+a).val()?0:$("#"+b).prop("checked")?1:0}
function UploadFile(a,b){if(multiFileUploader&&!(0>=multiFileUploader.getSubmittedNum())){var c=$("#TagInputItemData").val(),e=$("#EditCategory").val(),g=$.trim($("#EditDescription").val()),f=$.trim($("#EditTagList").val());f=f.substr(0,100);var d=parseInt($("#EditPublish").val(),10),h=$("#EditPassword").val(),k=$("#OptionCheerNg").prop("checked")?0:1,l=$("#OptionRecent").prop("checked")?1:0,n=$("#OptionTweet").prop("checked")?1:0,m=$("#OptionImage").prop("checked")?1:0,q=null,p=getLimitedTimeFlg("EditPublish",
"OptionLimitedTimePublish"),r=null,t=null;if(10===d){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}q=$("#EditTwitterList").val()}if(1===p&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),t=getPublishDateTime($("#EditTimeLimitedEnd").val()),!checkPublishDatetime(r,t,!1)))return;$("#TagInputItemData").length||(c=1);setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99===d&&(n=0);
startMsg();var v=n;1===p&&(v=0);$.ajaxSingle({type:"post",data:{UID:a,GD:c,CAT:e,DES:g,TAG:f,PID:d,PPW:h,PLD:q,LTP:p,PST:r,PED:t,TWT:getTweetSetting(),TWI:getTweetImageSetting(),ED:0,CNG:k,RID:b},url:"/api/UploadFileRefTwitterF.jsp",dataType:"json",success:function(u){console.log("UploadFileRefTwitterF");u&&u.content_id&&(0<u.content_id?(multiFileUploader.first_file=!0,multiFileUploader.user_id=a,multiFileUploader.illust_id=u.content_id,multiFileUploader.recent=l,multiFileUploader.tweet=v,multiFileUploader.tweet_image=
m,multiFileUploader.publish_id=d,multiFileUploader.uploadStoredFiles()):errorMsg())}})}}var g_strPasteMsg="";
function initUploadPaste(){g_strPasteMsg=$("#TimeLineAddImage").html();$("#TimeLineAddImage").pastableContenteditable();$("#TimeLineAddImage").on("pasteImage",function(a,b){10>$(".InputFile").length&&(a=createPasteElm(b.dataURL),$("#PasteZone").append(a),$("#TimeLineAddImage").html(g_strPasteMsg));updatePasteNum()}).on("pasteImageError",function(a,b){b.url&&alert("error data : "+b.url)}).on("pasteText",function(a,b){$("#TimeLineAddImage").html(g_strPasteMsg)})}
function createPasteElm(a){var b=$("<div />").addClass("InputFile"),c=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);b.append(c).append(a);return b}
function createPasteListItem(a,b){b=$("<li />").addClass("InputFile").attr("id",b);var c=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);b.append(c).append(a);return b}
function createPasteListItem(a,b){b=$("<li />").addClass("InputFile").attr("id",b);var c=$("<div />").addClass("DeletePaste").html('<i class="fas fa-times"></i>').on("click",function(){$(this).parent().remove();updatePasteNum()});a=$("<img />").addClass("imgView").attr("src",a);b.append(c).append(a);return b}
function initPasteElm(a){a.on("pasteImage",function(b,c){$(".OrgMessage",this).hide();$(".imgView",this).attr("src",c.dataURL).show()}).on("pasteImageError",function(b,c){c.url&&alert("error data : "+c.url)}).on("pasteText",function(b,c){})}function updatePasteNum(){strTotal="("+$(".InputFile").length+"/10)";$("#TotalSize").html(strTotal)}
function UploadPaste(a){var b=0;$(".imgView").each(function(){0<$.trim($(this).attr("src")).length&&b++});if(!(0>=b)){var c=$("#TagInputItemData").val(),e=$("#EditCategory").val(),g=$.trim($("#EditDescription").val()),f=$.trim($("#EditTagList").val());f=f.substr(0,100);var d=$("#EditPublish").val(),h=$("#EditPassword").val(),k=$("#OptionCheerNg").prop("checked")?0:1,l=$("#OptionRecent").prop("checked")?1:0,n=$("#OptionTweet").prop("checked")?1:0,m=$("#OptionImage").prop("checked")?1:0,q=null,p=getLimitedTimeFlg("EditPublish",
"OptionLimitedTimePublish"),r=null,t=null;if(10==d){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();return}q=$("#EditTwitterList").val()}if(1==p&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),t=getPublishDateTime($("#EditTimeLimitedEnd").val()),!checkPublishDatetime(r,t,!1)))return;$("#TagInputItemData").length||(c=1);setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99==d&&(n=0);startMsg();
var v=n;1==p&&(v=0);$.ajaxSingle({type:"post",data:{UID:a,GD:c,CAT:e,DES:g,TAG:f,PID:d,PPW:h,PLD:q,LTP:p,PST:r,PED:t,TWT:getTweetSetting(),TWI:getTweetImageSetting(),ED:1,CNG:k},url:"/api/UploadFileRefTwitterF.jsp",dataType:"json",success:function(u){console.log("UploadFileReferenceF",u.content_id);var y=!0;$(".imgView").each(function(){$(this).parent().addClass("Done");var x=$(this).attr("src").replace("data:image/png;base64,","");if(0>=x.length)return!0;y?(y=!1,$.ajax({type:"post",data:{UID:a,IID:u.content_id,
REC:l,DATA:x},url:"/f/UploadPasteFirstF.jsp",dataType:"json",async:!1,success:function(z){console.log("UploadPasteFirstF")}})):$.ajax({type:"post",data:{UID:a,IID:u.content_id,DATA:x},url:"/f/UploadPasteAppendF.jsp",dataType:"json",async:!1,success:function(z){console.log("UploadPasteAppendF")}})});1==v?$.ajax({type:"post",data:{UID:a,IID:u.content_id,IMG:m},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(x){tweetSucceeded(x.result)}}):setTimeout(function(){location.href="/MyIllustListPcV.jsp"},
1E3)}});return!1}}
function UploadText(a,b){var c=$("#TagInputItemData").val(),e=$("#EditCategory").val(),g=$.trim($("#EditDescription").val()),f=$.trim($("#EditTextBody").val()),d=$.trim($("#EditTagList").val());d=d.substr(0,100);var h=$("#EditPublish").val(),k=$("#EditPassword").val(),l=$("#OptionCheerNg").prop("checked")?0:1,n=$("#OptionRecent").prop("checked")?1:0,m=$("#OptionTweet").prop("checked")?1:0,q=null,p=getLimitedTimeFlg("EditPublish","OptionLimitedTimePublish"),r=null,t=null;if(10===h){if($("#TwitterListNotFound").is(":visible")){twitterListNotFoundMsg();
return}q=$("#EditTwitterList").val()}if(1===p&&(r=getPublishDateTime($("#EditTimeLimitedStart").val()),t=getPublishDateTime($("#EditTimeLimitedEnd").val()),!checkPublishDatetime(r,t,!1)))return;$("#TagInputItemData").length||(c=1);setTweetSetting($("#OptionTweet").prop("checked"));setTweetImageSetting($("#OptionImage").prop("checked"));setLastCategorySetting(e);99===h&&(m=0);startMsg();var v=m;1===p&&(v=0);$.ajaxSingle({type:"post",data:{UID:a,GD:c,CAT:e,DES:g,BDY:f,TAG:d,PID:h,PPW:k,PLD:q,LTP:p,
PST:r,PED:t,TWT:getTweetSetting(),TWI:getTweetImageSetting(),ED:3,CNG:l,REC:n,RID:b},url:"/f/UploadTextRefTwitterF.jsp",dataType:"json",success:function(u){console.log("UploadTextRefTwitterF");u&&u.content_id&&0<u.content_id&&(1==v?$.ajax({type:"post",data:{UID:a,IID:u.content_id,IMG:0},url:"/api/UploadFileTweetF.jsp",dataType:"json",success:function(y){tweetSucceeded(y.result)}}):setTimeout(function(){location.href="/MyIllustListPcV.jsp"},1E3))}})}
function initOption(){$("#OptionTweet").prop("checked",getTweetSetting());$("#OptionImage").prop("checked",getTweetImageSetting());var a=getLastCategorySetting();$("#EditCategory option").each(function(){$(this).val()==a&&$("#EditCategory").val(a)});updateTweetButton()};
